// English Grade 1 — 20 subjects × 30 questions
function q(c, opts, k, e) {
  return { content: c, options: [{key:'A',text:opts[0]},{key:'B',text:opts[1]},{key:'C',text:opts[2]},{key:'D',text:opts[3]}], correctAnswer: k, explanation: e };
}

module.exports = [
  { name: 'Hello! Chào hỏi & tự giới thiệu', questions: [
    q('"Hello" nghĩa là?',['Tạm biệt','Xin chào','Cảm ơn','Xin lỗi'],'B','Hello = Xin chào.'),
    q('"My name is Nam" — câu này đúng không?',['Sai','Đúng','Thiếu từ','Không hiểu'],'B','"My name is + tên" là cấu trúc đúng.'),
    q('"Goodbye" nghĩa là?',['Xin chào','Cảm ơn','Tạm biệt','Xin lỗi'],'C','Goodbye = Tạm biệt.'),
    q('Buổi sáng bạn chào bằng?',['Good night','Good morning','Good evening','Goodbye'],'B','Good morning = Chào buổi sáng.'),
    q('"How are you?" nghĩa là?',['Bạn bao nhiêu tuổi?','Bạn có khỏe không?','Bạn tên gì?','Bạn ở đâu?'],'B','How are you? = Bạn có khỏe không?'),
    q('Trả lời "How are you?" đúng nhất?',['I am five','I am fine, thank you','My name is Lan','I am a student'],'B','I am fine, thank you = Tôi khỏe, cảm ơn.'),
    q('"Good afternoon" dùng vào buổi nào?',['Buổi sáng','Buổi tối','Buổi chiều','Ban đêm'],'C','Good afternoon = Chào buổi chiều.'),
    q('"I am 6 years old" nghĩa là?',['Tôi học lớp 6','Tôi 6 tuổi','Tôi có 6 bạn','Tôi cao 6 cm'],'B','I am 6 years old = Tôi 6 tuổi.'),
    q('"Nice to meet you!" nghĩa là?',['Tôi không thích bạn','Hẹn gặp lại','Rất vui được gặp bạn','Cảm ơn bạn'],'C','Nice to meet you! = Rất vui được gặp bạn!'),
    q('Từ nào là lời chào?',['Cat','Hi','Red','Run'],'B','Hi = lời chào thân thiện.'),
    q('Điền vào: "My ___ is Minh."',['age','color','name','school'],'C','My name is Minh = Tên tôi là Minh.'),
    q('"I am a student" nghĩa là?',['Tôi là giáo viên','Tôi là học sinh','Tôi là bác sĩ','Tôi là bố'],'B','student = học sinh.'),
    q('"Good night!" — nói lúc nào?',['Đi học','Đi ngủ','Đi chơi','Ăn cơm'],'B','Good night = Chúc ngủ ngon.'),
    q('"Good evening" dùng lúc mấy giờ?',['7 sáng','12 trưa','7 tối','12 đêm'],'C','Good evening dùng buổi tối.'),
    q('"I am eight years old" — Tom bao nhiêu tuổi?',['6','7','8','9'],'C','eight = 8.'),
    q('Sắp xếp đúng: My / name / is / Mai',['My name is Mai','Name My is Mai','Is My name Mai','Mai My name is'],'A','My name is Mai = đúng.'),
    q('Khi ra về bạn nói?',['Good morning','Hello','Goodbye','How are you?'],'C','Goodbye = Tạm biệt khi ra về.'),
    q('"I am from Vietnam." "from" chỉ điều gì?',['Tuổi','Tên','Quê hương','Lớp học'],'C','from = đến từ (quê hương).'),
    q('Câu nào đúng?',['I name am Tuan','My am name Tuan','My name is Tuan','Name I is Tuan'],'C','My name is + tên = đúng.'),
    q('Gặp thầy cô buổi sáng, nói gì?',['Goodbye!','Good morning, teacher!','Good night!','See you!'],'B','Good morning, teacher! = chuẩn mực.'),
    q('Từ trái nghĩa với Hello khi chia tay?',['Hi','Hey','Goodbye','Howdy'],'C','Goodbye = tạm biệt ↔ Hello = xin chào.'),
    q('Điền vào: "___, My name is Lan. I am 6."',['Goodbye','Good night','Hello','Sorry'],'C','Hello bắt đầu lời chào.'),
    q('Câu nói tuổi đúng?',['I have 7 years','My years are 7','I am 7 years old','I years old 7'],'C','I am + tuổi + years old = đúng.'),
    q('"See you tomorrow!" nghĩa là?',['Gặp nhau hôm nay','Hẹn gặp ngày mai','Chúc ngủ ngon','Xin chào'],'B','See you tomorrow = Hẹn gặp ngày mai.'),
    q('Từ nào KHÔNG phải lời chào?',['Hello','Hi','Apple','Good morning'],'C','Apple = táo, không phải lời chào.'),
    q('Lan 7 tuổi. Cô ấy nói?',['I am seven years old','I have seven years','Seven years I am','My age have seven'],'A','I am seven years old = đúng.'),
    q('"Good night" → nói khi nào?',['Buổi sáng','Buổi chiều','Trước khi ngủ','Buổi trưa'],'C','Good night = trước khi đi ngủ.'),
    q('Bạn hắt hơi, người kia nói?',['Good morning!','Bless you!','Goodbye!','See you!'],'B','Bless you! = nói khi ai hắt hơi.'),
    q('Thầy: "Good morning!" Trò đáp lại?',['OK','Hi','Good morning, teacher!','Yeah'],'C','Lịch sự đáp: Good morning, teacher!'),
    q('Sửa lỗi: "My name am Cuong."',['My name were Cuong','My name is Cuong','I name am Cuong','My name are Cuong'],'B','My name IS Cuong = đúng.'),
  ]},

  { name: 'Numbers 1-20 — Số đếm', questions: [
    q('"Five" là số mấy?',['3','4','5','6'],'C','Five = 5.'),
    q('"Ten" nghĩa là?',['Một','Mười','Mười lăm','Hai'],'B','Ten = 10.'),
    q('1, 2, 3, ___, 5. Số còn thiếu?',['Four','Six','Seven','Two'],'A','Four = 4.'),
    q('Bạn có bao nhiêu ngón tay?',['Eight','Nine','Ten','Eleven'],'C','Ten = 10 ngón tay.'),
    q('"Twelve" = ?',['11','12','13','20'],'B','Twelve = 12.'),
    q('Số nào đến sau "fifteen"?',['Fourteen','Sixteen','Seventeen','Twenty'],'B','Sixteen = 16.'),
    q('7 bằng tiếng Anh là?',['Six','Eight','Seven','Nine'],'C','Seven = 7.'),
    q('"Twenty" = ?',['12','15','18','20'],'D','Twenty = 20.'),
    q('11 bằng tiếng Anh là?',['Eleven','Twelve','Thirteen','Ten'],'A','Eleven = 11.'),
    q('Đếm ngược: 5, 4, ___, 2, 1',['Six','Three','Zero','Seven'],'B','Three = 3.'),
    q('Một tuần có bao nhiêu ngày?',['Five','Six','Seven','Eight'],'C','Seven days = 7 ngày/tuần.'),
    q('Số nào nằm giữa 13 và 15?',['Twelve','Fourteen','Sixteen','Eleven'],'B','Fourteen = 14.'),
    q('Nam có 3 táo, Lan cho thêm 4. Tổng?',['Six','Seven','Eight','Nine'],'B','3+4=7 = Seven.'),
    q('"Nineteen" = ?',['17','18','19','20'],'C','Nineteen = 19.'),
    q('Số nhỏ nhất trong: 15, 3, 10, 18?',['Fifteen','Three','Ten','Eighteen'],'B','Three = 3 nhỏ nhất.'),
    q('20 học sinh, 8 về nhà. Còn lại?',['Ten','Eleven','Twelve','Thirteen'],'C','20-8=12 = Twelve.'),
    q('"Seventeen" = ?',['16','17','18','19'],'B','Seventeen = 17.'),
    q('Số chẵn trong: 3, 7, 11, 16?',['Three','Seven','Eleven','Sixteen'],'D','Sixteen=16 chia hết cho 2.'),
    q('Xếp tăng dần: 9, 3, 17, 5',['3,5,9,17','17,9,5,3','3,9,5,17','5,3,9,17'],'A','3<5<9<17.'),
    q('Số nào nằm giữa 18 và 20?',['Seventeen','Sixteen','Nineteen','Twenty-one'],'C','Nineteen = 19.'),
    q('2 tay × 5 ngón = bao nhiêu ngón?',['Seven','Eight','Nine','Ten'],'D','2×5=10 = Ten.'),
    q('14 đánh vần là?',['Forty','Fourteen','Four','Thirteen'],'B','14 = Fourteen.'),
    q('Trước "sixteen" là số nào?',['Seventeen','Fifteen','Fourteen','Eighteen'],'B','Fifteen = 15.'),
    q('10, 12, ___, 16. Số còn thiếu?',['Thirteen','Fourteen','Eleven','Fifteen'],'B','Fourteen = 14 (cách 2).'),
    q('Số lẻ trong: 4, 6, 9, 8?',['Four','Six','Nine','Eight'],'C','Nine = 9 là số lẻ.'),
    q('4 chân/mèo. 3 mèo có bao nhiêu chân?',['Ten','Eleven','Twelve','Thirteen'],'C','4×3=12 = Twelve.'),
    q('Số nào có cả chục và đơn vị?',['Five','Thirteen','Nine','One'],'B','Thirteen=13 có 1 chục 3 đơn vị.'),
    q('Đếm cách 2: 2, 4, 6, ___, 10',['Seven','Eight','Nine','Eleven'],'B','Eight = 8.'),
    q('Eighteen > Fifteen. Đúng hay sai?',['Đúng: 18>15','Sai: 18<15','Bằng nhau','Không so được'],'A','18>15 = đúng.'),
    q('1 tuần = 7 ngày. 2 tuần = bao nhiêu ngày?',['Twelve','Thirteen','Fourteen','Fifteen'],'C','7×2=14 = Fourteen.'),
  ]},

  { name: 'Colors — Màu sắc yêu thích', questions: [
    q('Mặt trời màu gì?',['Blue','Green','Yellow','Red'],'C','Mặt trời = Yellow.'),
    q('"Red" nghĩa là?',['Xanh lá','Đỏ','Vàng','Tím'],'B','Red = đỏ.'),
    q('Bầu trời màu gì?',['Red','Blue','Pink','Brown'],'B','Bầu trời = Blue.'),
    q('"Green" nghĩa là?',['Màu vàng','Màu trắng','Màu xanh lá','Màu đen'],'C','Green = xanh lá.'),
    q('Chuối chín màu gì?',['Red','Green','Yellow','Purple'],'C','Chuối chín = Yellow.'),
    q('"White" nghĩa là?',['Đen','Nâu','Trắng','Xám'],'C','White = trắng.'),
    q('Quả dâu tây màu gì?',['Blue','Red','Green','White'],'B','Dâu tây = Red.'),
    q('"Black" nghĩa là?',['Màu đen','Màu trắng','Màu xám','Màu nâu'],'A','Black = đen.'),
    q('Cỏ màu gì?',['Yellow','Red','Green','Blue'],'C','Cỏ = Green.'),
    q('"Orange" chỉ màu gì?',['Màu hồng','Màu cam','Màu nâu','Màu tím'],'B','Orange = màu cam.'),
    q('Cà chua chín màu gì?',['Blue','White','Red','Green'],'C','Cà chua = Red.'),
    q('"Purple" nghĩa là?',['Màu xanh','Màu vàng','Màu tím','Màu đỏ'],'C','Purple = tím.'),
    q('Gấu Bắc Cực màu gì?',['Black','Brown','White','Gray'],'C','Gấu Bắc Cực = White.'),
    q('"The sky is ___."',['Green','Red','Blue','Pink'],'C','Bầu trời xanh = Blue.'),
    q('Sô-cô-la màu gì?',['Yellow','Brown','Pink','Orange'],'B','Sô-cô-la = Brown.'),
    q('Đỏ + Trắng = ?',['Purple','Orange','Pink','Gray'],'C','Red + White = Pink.'),
    q('"Gray" nghĩa là?',['Màu đen','Màu xám','Màu nâu','Màu trắng'],'B','Gray = xám.'),
    q('Cà rốt màu gì?',['Green','Red','Orange','Yellow'],'C','Cà rốt = Orange.'),
    q('Màu nào KHÔNG phải màu cơ bản?',['Red','Blue','Green','Orange'],'D','Orange = đỏ+vàng, không phải màu cơ bản.'),
    q('Xanh dương + Vàng = ?',['Red','Purple','Green','Orange'],'C','Blue + Yellow = Green.'),
    q('"Pink" nghĩa là?',['Màu cam','Màu hồng','Màu tím','Màu đỏ'],'B','Pink = hồng.'),
    q('Cầu vồng có bao nhiêu màu?',['Five','Six','Seven','Eight'],'C','Cầu vồng có 7 màu.'),
    q('Bầu trời ban đêm màu gì?',['Blue','Black','Gray','White'],'B','Ban đêm = Black.'),
    q('Màu ấm là?',['Blue','Green','Red','Purple'],'C','Red = màu ấm.'),
    q('Ếch thường màu gì?',['Red','White','Green','Blue'],'C','Ếch = Green.'),
    q('Chanh vàng màu gì?',['Green','Red','Yellow','Orange'],'C','Lemon = Yellow.'),
    q('"Brown" nghĩa là?',['Màu xám','Màu nâu','Màu đen','Màu đỏ'],'B','Brown = nâu.'),
    q('Đỏ + Xanh dương = ?',['Green','Orange','Purple','Brown'],'C','Red + Blue = Purple.'),
    q('Câu nào đúng về màu táo?',['Táo chỉ có màu đỏ','Táo chỉ có màu xanh','Táo có thể đỏ hoặc xanh','Táo màu vàng'],'C','Táo có thể đỏ (red) hoặc xanh (green).'),
    q('Màu trời yêu thích của Nam = màu bầu trời. Là màu gì?',['Green','Yellow','Blue','Red'],'C','Bầu trời = Blue.'),
  ]},

  { name: 'Shapes — Hình dạng xung quanh ta', questions: [
    q('Quả bóng có hình gì?',['Square','Circle','Triangle','Rectangle'],'B','Quả bóng tròn = Circle.'),
    q('"Square" nghĩa là?',['Hình tròn','Hình tam giác','Hình vuông','Hình chữ nhật'],'C','Square = hình vuông.'),
    q('Tam giác có mấy cạnh?',['Two','Three','Four','Five'],'B','Triangle = 3 cạnh.'),
    q('Cái cửa hình gì?',['Circle','Triangle','Rectangle','Star'],'C','Cửa = Rectangle.'),
    q('"Star" nghĩa là?',['Hình tròn','Hình sao','Hình tim','Hình vuông'],'B','Star = hình sao.'),
    q('Hình vuông có mấy cạnh bằng nhau?',['Two','Three','Four','Five'],'C','Square = 4 cạnh bằng nhau.'),
    q('Pizza nguyên cái hình gì?',['Square','Triangle','Circle','Rectangle'],'C','Pizza nguyên = Circle.'),
    q('"Rectangle" nghĩa là?',['Hình vuông','Hình thang','Hình chữ nhật','Hình tròn'],'C','Rectangle = hình chữ nhật.'),
    q('Hình nào không có góc?',['Square','Triangle','Circle','Rectangle'],'C','Circle = không có góc.'),
    q('Quyển sách hình gì?',['Circle','Triangle','Rectangle','Star'],'C','Sách = Rectangle.'),
    q('Hình vuông có mấy góc?',['Three','Four','Five','Six'],'B','Square = 4 góc.'),
    q('Bánh xe hình gì?',['Square','Circle','Triangle','Diamond'],'B','Bánh xe = Circle.'),
    q('"Diamond" trông như thế nào?',['Hình vuông xoay 45°','Hình tam giác','Hình tròn','Hình chữ nhật'],'A','Diamond = hình thoi, như vuông xoay nghiêng.'),
    q('Lá cờ Việt Nam hình gì?',['Circle','Triangle','Rectangle','Square'],'C','Cờ Việt Nam = Rectangle.'),
    q('Tam giác có mấy góc?',['Two','Three','Four','Five'],'B','Triangle = 3 góc.'),
    q('Hình nào có 6 cạnh?',['Pentagon','Hexagon','Octagon','Square'],'B','Hexagon = lục giác = 6 cạnh.'),
    q('Biển báo STOP hình gì?',['Circle','Triangle','Octagon','Rectangle'],'C','STOP sign = Octagon (8 cạnh).'),
    q('Rectangle có mấy cạnh?',['Three','Four','Five','Six'],'B','Rectangle = 4 cạnh.'),
    q('Hình nào trông như quả trứng?',['Circle','Oval','Square','Triangle'],'B','Oval = bầu dục.'),
    q('Pentagon có mấy cạnh?',['Four','Five','Six','Seven'],'B','Pentagon = ngũ giác = 5 cạnh.'),
    q('Các cạnh hình vuông như thế nào với nhau?',['Khác nhau','Bằng nhau','Dài hơn','Ngắn hơn'],'B','Hình vuông: 4 cạnh bằng nhau.'),
    q('Cạnh dài hình chữ nhật gọi là?',['Width','Length','Height','Diagonal'],'B','Length = chiều dài.'),
    q('Hình nào lăn dễ dàng nhất?',['Square','Triangle','Circle','Rectangle'],'C','Circle lăn dễ vì không có góc.'),
    q('Hình vuông là dạng đặc biệt của?',['Triangle','Circle','Rectangle','Pentagon'],'C','Square là rectangle đặc biệt (4 cạnh bằng).'),
    q('Tam giác có ___ cạnh, hình vuông có ___ cạnh.',['3, 4','4, 3','3, 3','4, 4'],'A','Tam giác=3, vuông=4.'),
    q('Hình nào có nhiều cạnh nhất trong: Pentagon, Triangle, Square?',['Triangle (3)','Square (4)','Pentagon (5)','Bằng nhau'],'C','Pentagon=5 > Square=4 > Triangle=3.'),
    q('Hình tròn có mấy cạnh?',['Zero','One','Two','Four'],'A','Circle không có cạnh thẳng.'),
    q('3 cạnh bằng nhau tạo hình gì?',['Square','Equilateral triangle','Rectangle','Pentagon'],'B','3 cạnh bằng = tam giác đều.'),
    q('4 cạnh bằng + 4 góc vuông = hình gì?',['Rectangle','Rhombus','Square','Triangle'],'C','Square = hình vuông.'),
    q('Hình 2D nào không có đường thẳng?',['Triangle','Square','Circle','Pentagon'],'C','Circle = không có đường thẳng.'),
  ]},

  { name: 'Animals — Các con vật', questions: [
    q('Con chó kêu thế nào?',['Meow','Woof/Bark','Moo','Oink'],'B','Chó kêu Woof.'),
    q('"Cat" nghĩa là?',['Con chó','Con mèo','Con bò','Con cá'],'B','Cat = con mèo.'),
    q('Con vật nào sống dưới nước?',['Dog','Cat','Fish','Cow'],'C','Fish sống dưới nước.'),
    q('"Bird" có thể làm gì?',['Swim','Fly','Bark','Roar'],'B','Bird = bay (fly).'),
    q('Con bò cho ta thứ gì?',['Eggs','Wool','Milk','Honey'],'C','Bò = Milk.'),
    q('"Rabbit" nghĩa là?',['Con thỏ','Con vịt','Con lợn','Con ngựa'],'A','Rabbit = con thỏ.'),
    q('Con vật nào kêu "Moo"?',['Cat','Dog','Cow','Pig'],'C','Bò kêu Moo.'),
    q('Gà đẻ ra?',['Milk','Eggs','Honey','Wool'],'B','Gà đẻ trứng = Eggs.'),
    q('"Elephant" nghĩa là?',['Con voi','Con hổ','Con sư tử','Con gấu'],'A','Elephant = con voi.'),
    q('Con vật nào lớn nhất: Rabbit, Cat, Elephant, Mouse?',['Rabbit','Cat','Elephant','Mouse'],'C','Elephant = con voi, lớn nhất.'),
    q('Ong làm ra?',['Milk','Honey','Eggs','Wool'],'B','Ong làm Honey = mật ong.'),
    q('Con vật nào cũng có thể bơi: Dog hay Fish?',['Chỉ Dog','Chỉ Fish','Cả hai','Không con nào'],'C','Fish bơi được; một số Dog cũng bơi.'),
    q('"Tiger" nghĩa là?',['Con sư tử','Con báo','Con hổ','Con gấu'],'C','Tiger = con hổ.'),
    q('Con vật nào có sọc?',['Elephant','Tiger','Rabbit','Cow'],'B','Hổ có sọc.'),
    q('Nhện có mấy chân?',['Four','Six','Eight','Ten'],'C','Nhện có 8 chân.'),
    q('Con vật hoang dã trong: Dog, Cat, Lion, Cow?',['Dog','Cat','Lion','Cow'],'C','Lion = sư tử, thú hoang.'),
    q('Cá thở bằng?',['Lungs','Gills','Skin','Nose'],'B','Cá thở bằng mang = Gills.'),
    q('"Horse" nghĩa là?',['Con dê','Con ngựa','Con bò','Con lừa'],'B','Horse = con ngựa.'),
    q('Con vật nào là bò sát?',['Cat','Bird','Crocodile','Rabbit'],'C','Crocodile = cá sấu, bò sát.'),
    q('Động vật chỉ ăn thực vật gọi là?',['Carnivores','Herbivores','Omnivores','Predators'],'B','Herbivores = ăn cỏ.'),
    q('Chim cánh cụt sống ở đâu?',['Rừng nhiệt đới','Sa mạc','Nam/Bắc Cực','Chỉ dưới biển'],'C','Penguin sống ở Nam/Bắc Cực.'),
    q('Con vật cho ta len?',['Cow','Pig','Sheep','Chicken'],'C','Sheep = cừu cho len = Wool.'),
    q('Động vật có vú nuôi con bằng?',['Seeds','Insects','Milk','Fish'],'C','Mammals nuôi con bằng Milk.'),
    q('Con vật có thể ngụy trang đổi màu?',['Dog','Chameleon','Rabbit','Horse'],'B','Chameleon = tắc kè hoa.'),
    q('Sâu bướm (caterpillar) biến thành?',['Bee','Butterfly','Ant','Spider'],'B','Caterpillar → Butterfly.'),
    q('Con vật nào hoạt động ban đêm?',['Rooster','Owl','Cow','Horse'],'B','Owl = cú mèo, nocturnal.'),
    q('Cá và cá voi khác nhau thế nào?',['Cá thở nước, cá voi thở không khí','Cả hai thở không khí','Cả hai thở nước','Không khác'],'A','Whale = động vật có vú, thở không khí.'),
    q('Con vật nào là lưỡng cư?',['Snake','Frog','Turtle','Crocodile'],'B','Frog = ếch, lưỡng cư.'),
    q('Cơ thể chim được phủ bởi?',['Scales','Fur','Feathers','Skin'],'C','Bird = Feathers = lông vũ.'),
    q('Nhóm động vật có vú đúng?',['Snake, Turtle, Frog','Dog, Whale, Human','Eagle, Parrot, Penguin','Salmon, Shark, Clownfish'],'B','Dog, Whale, Human = mammals.'),
  ]},

  { name: 'My Family — Gia đình tôi', questions: [
    q('"Mother" nghĩa là?',['Bố','Mẹ','Anh','Em'],'B','Mother = mẹ.'),
    q('Mẹ của bố gọi là gì?',['Aunt','Grandmother','Sister','Cousin'],'B','Bà nội/ngoại = Grandmother.'),
    q('"Brother" nghĩa là?',['Chị gái','Anh/em trai','Em gái','Anh họ'],'B','Brother = anh hoặc em trai.'),
    q('"Grandfather" là ai?',['Bố của bố/mẹ = ông','Bác trai','Chú','Anh trai'],'A','Grandfather = ông.'),
    q('"Sister" nghĩa là?',['Anh trai','Em trai','Chị/em gái','Cô'],'C','Sister = chị hoặc em gái.'),
    q('Bố và mẹ của Nam là?',['Father and mother','Brother and sister','Grandfather and grandmother','Uncle and aunt'],'A','Bố mẹ = father and mother.'),
    q('"Uncle" nghĩa là?',['Ông','Chú/bác trai','Anh trai','Em trai'],'B','Uncle = chú, bác trai.'),
    q('Lan có 1 anh trai và 1 em gái. Có mấy siblings?',['One','Two','Three','Four'],'B','2 anh chị em = two siblings.'),
    q('"Aunt" nghĩa là?',['Cô/dì/bác gái','Bà','Chị gái','Em gái'],'A','Aunt = cô, dì, bác gái.'),
    q('Bố của em bé là?',['Uncle','Grandfather','Dad','Brother'],'C','Bố = Dad/Father.'),
    q('Điền vào: "I live with my ___, ___, and sister."',['Father and mother','Uncle and aunt','Grandfather and grandmother','Brother and cousin'],'A','Father and mother = bố mẹ.'),
    q('"Cousin" nghĩa là?',['Anh trai','Bạn thân','Anh/em họ','Chú'],'C','Cousin = anh/em họ.'),
    q('Chị gái của mẹ Tom là gì của Tom?',['Grandmother','Sister','Aunt','Cousin'],'C','Chị/em gái của mẹ = Aunt.'),
    q('Từ nào chỉ nữ trong gia đình?',['Father, Brother, Grandfather','Mother, Sister, Grandmother, Aunt','Uncle, Cousin, Brother','Father, Uncle, Grandfather'],'B','Mother, Sister, Grandmother, Aunt đều là nữ.'),
    q('Gia đình hạt nhân thường có mấy người?',['Chỉ 1','Thường 3-4 (bố mẹ + con)','Ít nhất 10','Hơn 20'],'B','Gia đình hạt nhân = bố mẹ + 1-2 con.'),
    q('"Grandparents" gồm?',['Father and mother','Grandfather and grandmother','Uncle and aunt','Brother and sister'],'B','Grandparents = ông và bà.'),
    q('Lan là nữ. Người anh/em nam của Lan là?',['Sister','Brother','Cousin','Uncle'],'B','Anh/em trai = Brother.'),
    q('Bố của mẹ là gì của tôi?',['Uncle','Father','Grandfather','Brother'],'C','Bố mẹ = Grandfather.'),
    q('Bố và mẹ cùng gọi là?',['Siblings','Parents','Relatives','Cousins'],'B','Parents = bố mẹ.'),
    q('Nam có 2 anh trai. Có mấy male siblings?',['One','Two','Three','Zero'],'B','Two brothers.'),
    q('Anh/em trai của bố là gì của tôi?',['Grandfather','Cousin','Uncle','Brother'],'C','Anh/em trai của bố = Uncle.'),
    q('Ai thường lớn tuổi nhất trong gia đình?',['Baby sister','Grandfather','Mother','Big brother'],'B','Grandfather = ông, thường lớn tuổi nhất.'),
    q('Con của chú/cô của tôi là?',['Siblings','Cousins','Nephews','Parents'],'B','Con của chú/cô = Cousins.'),
    q('Câu nào đúng?',['My mother name is Lan','My mother\'s name is Lan','My mother name\'s is Lan','Mother my name is Lan'],'B','My mother\'s name = đúng sở hữu cách.'),
    q('Lan có bà 70 tuổi. Đó là?',['Mother','Aunt','Grandmother','Sister'],'C','Bà = Grandmother.'),
    q('Con gái của chị gái tôi là?',['Cousin','Niece','Aunt','Sister'],'B','Con gái chị/em gái = Niece = cháu gái.'),
    q('Câu mô tả gia đình đúng?',['I have a mother, a father, and a sister.','I have a sister a brother and.','Mother father I have a.','Family have I a sister.'],'A','Câu A đúng ngữ pháp.'),
    q('Bố của bố Tom là gì của Tom?',['Uncle','Great grandfather','Grandfather','Brother'],'C','Bố của bố = Grandfather.'),
    q('Ai KHÔNG phải sibling?',['Brother','Sister','Cousin','Twin brother'],'C','Cousin = anh/em họ, không phải anh/em ruột.'),
    q('Gia đình 5 người: bố, mẹ, 2 trai, 1 gái. Bao nhiêu nữ?',['One','Two','Three','Five'],'B','Mẹ + 1 con gái = 2 nữ.'),
  ]},

  { name: 'Body Parts — Các bộ phận cơ thể', questions: [
    q('"Head" nghĩa là?',['Tay','Chân','Đầu','Mắt'],'C','Head = đầu.'),
    q('Bạn dùng ___ để nhìn.',['Ears','Eyes','Nose','Mouth'],'B','Eyes = mắt để nhìn.'),
    q('"Nose" nghĩa là?',['Mắt','Tai','Mũi','Miệng'],'C','Nose = mũi.'),
    q('Bạn nghe bằng?',['Eyes','Nose','Ears','Mouth'],'C','Ears = tai để nghe.'),
    q('"Hand" nghĩa là?',['Chân','Tay','Vai','Lưng'],'B','Hand = bàn tay.'),
    q('Mỗi bàn tay có mấy ngón?',['Four','Five','Six','Ten'],'B','Five fingers = 5 ngón/tay.'),
    q('"Foot/Feet" nghĩa là?',['Bàn tay','Ngón tay','Bàn chân','Đầu gối'],'C','Foot = bàn chân.'),
    q('Bạn cười bằng?',['Eyes','Nose','Mouth','Ears'],'C','Mouth = miệng để cười.'),
    q('"Arm" nghĩa là?',['Chân','Cánh tay','Ngón chân','Ngực'],'B','Arm = cánh tay.'),
    q('Bộ phận nào để đá bóng?',['Hand','Arm','Foot/Leg','Head'],'C','Foot/Leg = chân để đá.'),
    q('"Knee" nghĩa là?',['Cổ tay','Đầu gối','Khuỷu tay','Mắt cá chân'],'B','Knee = đầu gối.'),
    q('Bạn nếm vị bằng?',['Nose','Tongue','Eyes','Ear'],'B','Tongue = lưỡi để nếm.'),
    q('"Shoulder" nghĩa là?',['Lưng','Ngực','Vai','Bụng'],'C','Shoulder = vai.'),
    q('Bộ phận nào bơm máu?',['Lungs','Brain','Heart','Stomach'],'C','Heart = tim bơm máu.'),
    q('"Stomach" nghĩa là?',['Ngực','Bụng/Dạ dày','Lưng','Hông'],'B','Stomach = bụng/dạ dày.'),
    q('Người có mấy mắt?',['One','Two','Three','Four'],'B','Two eyes = 2 mắt.'),
    q('Bạn thở bằng?',['Stomach','Heart','Lungs','Brain'],'C','Lungs = phổi để thở.'),
    q('"Elbow" nghĩa là?',['Đầu gối','Mắt cá','Khuỷu tay','Cổ tay'],'C','Elbow = khuỷu tay.'),
    q('Cơ quan nào giúp ta suy nghĩ?',['Heart','Brain','Lungs','Stomach'],'B','Brain = não để suy nghĩ.'),
    q('Đếm các bộ phận: head, arm, leg, eye, nose',['Three','Four','Five','Six'],'C','5 bộ phận.'),
    q('Ngón tay thuộc về?',['Feet','Hands','Head','Shoulders'],'B','Fingers thuộc Hands.'),
    q('"Ankle" nghĩa là?',['Đầu gối','Khuỷu tay','Mắt cá chân','Cổ tay'],'C','Ankle = mắt cá chân.'),
    q('Bộ phận nào ở trên mặt?',['Knee','Elbow','Shoulder','Eyebrow'],'D','Eyebrow = lông mày, ở trên mặt.'),
    q('Ngón chân : bàn chân = Ngón tay : ?',['Arms','Hands','Legs','Head'],'B','Ngón tay gắn với Hands.'),
    q('Tổng ngón chân của người?',['Eight','Nine','Ten','Twelve'],'C','5×2 = 10 ngón chân.'),
    q('"Wrist" nghĩa là?',['Cổ tay','Khuỷu tay','Đầu gối','Mắt cá chân'],'A','Wrist = cổ tay.'),
    q('Bộ phận nối đầu với thân?',['Shoulder','Neck','Chest','Waist'],'B','Neck = cổ.'),
    q('Mũi dùng để?',['See','Hear','Smell','Touch'],'C','Nose = Smell = ngửi.'),
    q('Cơ quan tiêu hóa thức ăn?',['Heart','Stomach','Brain','Lungs'],'B','Stomach tiêu hóa thức ăn.'),
    q('Người có mấy chi (tay+chân)?',['Two','Three','Four','Six'],'C','2 tay + 2 chân = 4 chi.'),
  ]},

  { name: 'Food & Drinks — Đồ ăn và đồ uống', questions: [
    q('"Water" nghĩa là?',['Sữa','Nước','Nước ép','Trà'],'B','Water = nước.'),
    q('Cái nào là đồ uống?',['Rice','Bread','Milk','Egg'],'C','Milk = sữa, đồ uống.'),
    q('"Rice" nghĩa là?',['Bánh mì','Cơm/Gạo','Mì','Khoai'],'B','Rice = cơm/gạo.'),
    q('Buổi sáng thường uống gì?',['Juice or milk','Salt water','Cooking oil','Vinegar'],'A','Sáng uống nước ép hoặc sữa.'),
    q('"Bread" nghĩa là?',['Cơm','Mì','Bánh mì','Xôi'],'C','Bread = bánh mì.'),
    q('Thức ăn nào cho năng lượng?',['Water','Rice and bread','Salt','Ice'],'B','Cơm và bánh mì = carbohydrate.'),
    q('"Egg" nghĩa là?',['Thịt','Trứng','Cá','Tôm'],'B','Egg = trứng.'),
    q('Cái nào là hoa quả?',['Carrot','Onion','Apple','Potato'],'C','Apple = táo, hoa quả.'),
    q('"Chicken" nghĩa là?',['Thịt bò','Thịt heo','Thịt gà','Thịt dê'],'C','Chicken = thịt gà.'),
    q('Đồ uống nào tốt cho sức khỏe?',['Soda','Water','Energy drink','Sweetened juice'],'B','Water = nước lọc, tốt nhất.'),
    q('"Soup" nghĩa là?',['Cơm','Canh/Súp','Bánh','Mì xào'],'B','Soup = súp hoặc canh.'),
    q('Từ bò ta có?',['Eggs','Honey','Milk and cheese','Fish'],'C','Bò cho Milk và Cheese.'),
    q('"Vegetables" gồm?',['Apple, orange, mango','Carrot, spinach, broccoli','Chicken, beef, pork','Rice, bread, noodles'],'B','Rau củ = carrot, spinach, broccoli.'),
    q('Bữa ăn buổi sáng gọi là?',['Lunch','Dinner','Breakfast','Supper'],'C','Breakfast = bữa sáng.'),
    q('"Juice" nghĩa là?',['Nước lọc','Sữa','Nước ép hoa quả','Trà'],'C','Juice = nước ép hoa quả.'),
    q('Thực phẩm giàu protein?',['Rice','Candy','Fish and eggs','Oil'],'C','Cá và trứng giàu đạm.'),
    q('"Ice cream" nghĩa là?',['Bánh kem','Kem que/tươi','Kẹo','Chocolate'],'B','Ice cream = kem.'),
    q('Đồ ăn nhẹ lành mạnh?',['Chips','Candy bar','Apple slices','Fried food'],'C','Táo tươi = lành mạnh.'),
    q('"Noodles" nghĩa là?',['Cơm','Xôi','Mì/Bún','Bánh mì'],'C','Noodles = mì, bún, phở.'),
    q('Calo cung cấp cho cơ thể?',['Vitamins','Energy','Water','Fiber'],'B','Calo = năng lượng.'),
    q('"Breakfast" nghĩa là?',['Bữa trưa','Bữa tối','Bữa phụ','Bữa sáng'],'D','Breakfast = bữa sáng.'),
    q('Đồ uống không có đường?',['Soda','Lemonade','Water','Sweet tea'],'C','Water = không đường.'),
    q('"Cheese" làm từ?',['Fish','Chicken eggs','Milk','Honey'],'C','Cheese làm từ Milk.'),
    q('Thức ăn nào ngọt?',['Salt','Lemon','Honey','Pepper'],'C','Honey = mật ong, ngọt.'),
    q('Nên ăn mấy bữa mỗi ngày?',['One','Two','Three','Six'],'C','3 bữa: sáng, trưa, tối.'),
    q('"Dinner" là bữa ăn lúc nào?',['Buổi sáng','Buổi trưa','Buổi tối','Nửa đêm'],'C','Dinner = bữa tối.'),
    q('Nhóm thực phẩm giúp xương chắc?',['Sweets','Dairy (milk, cheese)','Fried food','Sugary drinks'],'B','Sữa và chế phẩm = canxi cho xương.'),
    q('Cơm + cá + rau là bữa ăn như thế nào?',['Unhealthy','Balanced and healthy','Only snacks','Only dessert'],'B','Cân bằng và lành mạnh.'),
    q('Cái nào KHÔNG phải đồ uống?',['Tea','Milk','Bread','Water'],'C','Bread = thức ăn.'),
    q('Ăn nhiều đường dẫn đến?',['Xương chắc hơn','Mắt tốt hơn','Sâu răng','Chạy nhanh hơn'],'C','Đường → Tooth decay = sâu răng.'),
  ]},

  { name: 'School Items — Đồ dùng học tập', questions: [
    q('"Pencil" nghĩa là?',['Bút bi','Bút chì','Thước kẻ','Kéo'],'B','Pencil = bút chì.'),
    q('Bạn viết lên đâu?',['Ruler','Eraser','Book/Paper','Scissors'],'C','Book/Paper = sách/giấy.'),
    q('"Ruler" nghĩa là?',['Cục tẩy','Thước kẻ','Bút màu','Compa'],'B','Ruler = thước kẻ.'),
    q('Vật nào xóa chữ bút chì?',['Pencil','Pen','Eraser','Ruler'],'C','Eraser = cục tẩy.'),
    q('"Bag/Schoolbag" nghĩa là?',['Hộp bút','Cặp sách','Sách giáo khoa','Thước'],'B','Schoolbag = cặp sách.'),
    q('Cắt giấy bằng?',['Ruler','Eraser','Scissors','Pencil'],'C','Scissors = kéo.'),
    q('"Crayon" nghĩa là?',['Bút bi','Bút chì','Bút sáp màu','Bút lông'],'C','Crayon = bút sáp màu.'),
    q('Vật nào để đọc?',['Scissors','Book','Glue','Stapler'],'B','Book = sách để đọc.'),
    q('"Glue" nghĩa là?',['Kéo','Hồ dán/Keo dán','Thước','Tẩy'],'B','Glue = keo dán.'),
    q('Vật nào đo độ dài?',['Eraser','Pencil','Ruler','Crayon'],'C','Ruler đo độ dài.'),
    q('"Notebook" nghĩa là?',['Sách giáo khoa','Tập/vở học sinh','Từ điển','Truyện'],'B','Notebook = tập/vở.'),
    q('Dán giấy lại với nhau bằng?',['Scissors','Glue or tape','Ruler','Pen'],'B','Glue or tape = keo dán hoặc băng keo.'),
    q('"Pen" nghĩa là?',['Bút chì','Bút bi/mực','Bút sáp','Bút lông'],'B','Pen = bút bi.'),
    q('Cái nào KHÔNG phải dụng cụ viết?',['Pencil','Pen','Crayon','Scissors'],'D','Scissors = kéo, không viết.'),
    q('"Sharpener" nghĩa là?',['Cục tẩy','Gọt bút chì','Thước kẻ','Kẹp giấy'],'B','Sharpener = đồ gọt bút.'),
    q('Bảng đen (chalkboard) thường màu gì?',['White','Black or green','Blue','Red'],'B','Bảng đen thường đen hoặc xanh lá.'),
    q('"Compass" dùng để?',['Vẽ đường thẳng','Vẽ đường tròn','Đo góc','Cắt giấy'],'B','Compass = vẽ hình tròn.'),
    q('Hộp bút chứa?',['Cặp sách','Ghế','Bút, tẩy, thước','Hộp cơm'],'C','Hộp bút = bút, tẩy, thước.'),
    q('"Dictionary" nghĩa là?',['Tập vở','Từ điển','Sách bài tập','Truyện'],'B','Dictionary = từ điển.'),
    q('Bút lông bảng trắng dùng trên?',['Paper','Whiteboard','Blackboard','Book'],'B','Dùng trên Whiteboard.'),
    q('Vật nào sắp xếp giấy tờ?',['Pencil','Folder/Binder','Eraser','Sharpener'],'B','Folder/Binder = bìa kẹp.'),
    q('"Tape" (dính) nghĩa là?',['Kéo','Keo dán','Băng keo dính','Ghim'],'C','Tape = băng keo.'),
    q('Nam mất tẩy. Nam không thể làm gì?',['Đọc sách','Sửa lỗi bút chì','Đo độ dài','Cắt giấy'],'B','Không có tẩy → không sửa lỗi.'),
    q('Cặp đôi nào đi cùng nhau?',['Pencil – Scissors','Pencil – Sharpener','Ruler – Glue','Book – Eraser'],'B','Bút chì cần gọt bút.'),
    q('"Stapler" dùng để?',['Cắt','Viết','Ghim giấy','Vẽ tròn'],'C','Stapler = máy ghim giấy.'),
    q('Cần ___ để vẽ đường thẳng.',['Crayon','Eraser','Ruler','Scissors'],'C','Ruler giúp vẽ đường thẳng.'),
    q('Vật nào KHÔNG nên mang vào trường?',['Textbook','Notebook','Dao bếp','Pencil case'],'C','Dao bếp nguy hiểm.'),
    q('"Highlighter" nghĩa là?',['Bút chì','Bút dạ quang','Bút lông','Bút bi'],'B','Highlighter = bút tô sáng.'),
    q('Lan có 3 bút chì, mua thêm 2. Tổng?',['Three','Four','Five','Six'],'C','3+2=5.'),
    q('Vật quan trọng nhất trong hộp bút?',['Food','Toys','Bút để viết','Mirror'],'C','Quan trọng nhất = bút để viết.'),
  ]},

  { name: 'Days of the Week — Các ngày trong tuần', questions: [
    q('"Monday" nghĩa là?',['Thứ Ba','Thứ Hai','Thứ Tư','Chủ Nhật'],'B','Monday = Thứ Hai.'),
    q('Sau Chủ Nhật là ngày gì?',['Saturday','Friday','Monday','Tuesday'],'C','Sau Sunday = Monday.'),
    q('"Wednesday" = ?',['Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Ba'],'A','Wednesday = Thứ Tư.'),
    q('Một tuần có mấy ngày?',['Five','Six','Seven','Eight'],'C','Seven days.'),
    q('"Friday" nghĩa là?',['Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'],'B','Friday = Thứ Sáu.'),
    q('Ngày cuối tuần là?',['Monday','Wednesday','Saturday','Thursday'],'C','Saturday = Thứ Bảy, cuối tuần.'),
    q('"Tuesday" = ?',['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm'],'B','Tuesday = Thứ Ba.'),
    q('Trước Thứ Sáu là ngày gì?',['Wednesday','Saturday','Thursday','Tuesday'],'C','Thursday = Thứ Năm.'),
    q('"Sunday" nghĩa là?',['Thứ Bảy','Chủ Nhật','Thứ Sáu','Thứ Năm'],'B','Sunday = Chủ Nhật.'),
    q('Học sinh đi học mấy ngày?',['Saturday, Sunday','Monday to Friday','Mon to Wed only','Sunday only'],'B','Học Mon-Fri = 5 ngày.'),
    q('Ngày đầu tuần ở Việt Nam?',['Sunday','Monday','Saturday','Tuesday'],'B','Monday = Thứ Hai, đầu tuần.'),
    q('"Thursday" = ?',['Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu'],'C','Thursday = Thứ Năm.'),
    q('Ngày nào nằm giữa Thứ Ba và Thứ Năm?',['Monday','Wednesday','Friday','Sunday'],'B','Wednesday = Thứ Tư.'),
    q('"Saturday" nghĩa là?',['Thứ Sáu','Chủ Nhật','Thứ Bảy','Thứ Năm'],'C','Saturday = Thứ Bảy.'),
    q('Nam đi bơi mỗi cuối tuần. Anh đi vào?',['Monday, Tuesday','Wednesday, Thursday','Saturday, Sunday','Thursday, Friday'],'C','Cuối tuần = Saturday, Sunday.'),
    q('Weekdays có bao nhiêu ngày?',['Two','Three','Four','Five'],'D','Mon,Tue,Wed,Thu,Fri = 5.'),
    q('Hôm nay Thứ Tư. Ngày mai là?',['Tuesday','Thursday','Friday','Monday'],'B','Sau Wed = Thursday.'),
    q('Hôm nay Thứ Sáu. Hôm qua là?',['Saturday','Wednesday','Thursday','Sunday'],'C','Trước Fri = Thursday.'),
    q('Viết tắt của Monday?',['Mo','Mon','Mn','MD'],'B','Mon = cách viết tắt phổ biến.'),
    q('Lan học đàn Thứ Ba và Thứ Năm. Mấy ngày/tuần?',['One','Two','Three','Four'],'B','2 ngày/tuần.'),
    q('Thứ tự đúng: Sunday, Friday, Monday',['Sunday, Monday, Friday','Monday, Friday, Sunday','Friday, Sunday, Monday','Monday, Sunday, Friday'],'B','Mon→Fri→Sun.'),
    q('Ngày giữa tuần học (Mon-Fri) là?',['Monday','Tuesday','Wednesday','Friday'],'C','Wed = giữa Mon-Fri.'),
    q('Hôm nay Chủ Nhật. Bao nhiêu ngày nữa tới Thứ Hai?',['One','Two','Three','Four'],'A','Sun→Mon = 1 ngày.'),
    q('Đếm ngày học Mon→Fri (gồm cả hai đầu).',['Four','Five','Six','Seven'],'B','Mon,Tue,Wed,Thu,Fri = 5.'),
    q('Ngày làm việc cuối cùng trong tuần?',['Thursday','Friday','Saturday','Sunday'],'B','Friday = Thứ Sáu.'),
    q('Sau 7 ngày ta hoàn thành một?',['Month','Year','Week','Day'],'C','7 ngày = 1 tuần.'),
    q('Ngày 6 và 7 trong tuần gọi là?',['Weekdays','School days','Weekend','Holidays'],'C','Weekend = Sat + Sun.'),
    q('Nam học Mon-Fri. Nghỉ vào?',['Thursday, Friday','Saturday, Sunday','Monday, Tuesday','Wednesday, Thursday'],'B','Nghỉ Sat + Sun.'),
    q('Hôm nay Thứ Ba. 2 ngày trước là ngày gì?',['Thursday','Wednesday','Sunday','Monday'],'C','Tue - 2 = Sun.'),
    q('Xếp thứ tự: Wed, Mon, Fri, Tue, Thu, Sat, Sun',['Mon,Tue,Wed,Thu,Fri,Sat,Sun','Sun,Sat,Fri,Thu,Wed,Tue,Mon','Mon,Wed,Fri,Tue,Thu,Sat,Sun','Sun,Mon,Wed,Fri,Tue,Thu,Sat'],'A','Mon,Tue,Wed,Thu,Fri,Sat,Sun.'),
  ]},

  { name: 'Weather — Thời tiết hôm nay', questions: [
    q('"Sunny" nghĩa là?',['Mưa','Nắng','Tuyết','Gió'],'B','Sunny = trời nắng.'),
    q('Khi mưa bạn dùng?',['Sunglasses','Umbrella','Fan','Scarf'],'B','Umbrella = ô.'),
    q('"Cold" nghĩa là?',['Nóng','Ấm','Lạnh','Mát'],'C','Cold = lạnh.'),
    q('Trời lạnh mặc gì?',['T-shirt and shorts','Swimsuit','Coat and scarf','Sandals'],'C','Coat and scarf = áo khoác + khăn.'),
    q('"Windy" nghĩa là?',['Trời mưa','Trời gió','Trời nắng','Trời sương mù'],'B','Windy = trời có gió.'),
    q('Thời tiết nào tốt để thả diều?',['Rainy','Snowy','Windy','Foggy'],'C','Windy = gió, thả diều tốt.'),
    q('"Rainy" nghĩa là?',['Trời gió','Trời nắng','Trời mưa','Trời lạnh'],'C','Rainy = trời mưa.'),
    q('Sấm chớp xảy ra khi?',['Sunny day','Storm','Snowy day','Foggy morning'],'B','Storm = bão có sấm chớp.'),
    q('"Hot" nghĩa là?',['Lạnh','Mát','Nóng','Ấm'],'C','Hot = nóng.'),
    q('Mùa hè thường như thế nào?',['Cold and snowy','Rainy and windy','Hot and sunny','Foggy and cool'],'C','Hè = Hot and sunny.'),
    q('"Cloudy" nghĩa là?',['Trời nắng','Trời nhiều mây','Trời mưa','Trời tuyết'],'B','Cloudy = trời nhiều mây.'),
    q('Tuyết (snow) như thế nào?',['Hot','Warm','Cold and white','Wet and invisible'],'C','Tuyết lạnh và trắng.'),
    q('"Warm" nghĩa là?',['Lạnh','Nóng','Ấm áp','Mát mẻ'],'C','Warm = ấm áp.'),
    q('Tuyết rơi vào mùa nào?',['Summer','Spring','Autumn','Winter'],'D','Winter = mùa đông có tuyết.'),
    q('"Foggy" nghĩa là?',['Trời gió to','Trời sương mù','Trời mưa đá','Trời nóng'],'B','Foggy = sương mù.'),
    q('Sau mưa đôi khi có?',['Snowstorm','Rainbow','Sandstorm','Tornado'],'B','Rainbow = cầu vồng sau mưa.'),
    q('Dụng cụ đo nhiệt độ?',['Ruler','Thermometer','Scale','Compass'],'B','Thermometer = nhiệt kế.'),
    q('Quần áo trời lạnh?',['Swimwear','Shorts and sandals','Coat, gloves, and boots','T-shirt and flip-flops'],'C','Coat, gloves, boots.'),
    q('Dự báo có mưa → mang theo?',['Toy','Kite','Umbrella','Scarf'],'C','Umbrella = ô.'),
    q('"Storm" nghĩa là?',['Cơn bão','Trận lũ','Sương mù','Sấm'],'A','Storm = cơn bão.'),
    q('Thời tiết nào tốt để picnic?',['Stormy','Sunny and warm','Very hot 40°C','Blizzard'],'B','Sunny and warm = nắng ấm.'),
    q('Mùa mưa ở miền Nam Việt Nam?',['Winter','Spring','May-Nov','All year equally'],'C','Mùa mưa miền Nam tháng 5-11.'),
    q('Sấm là ___, chớp là ___.',['Sound; light','Light; sound','Wind; rain','Cloud; fog'],'A','Thunder=âm thanh; lightning=ánh sáng.'),
    q('Mưa đá (hail) là?',['Soft snow','Ice pellets từ trời','Heavy rain','Frozen fog'],'B','Hail = viên đá nhỏ từ trời.'),
    q('Thời tiết lặp lại mỗi năm gọi là?',['Climate','Wind','Storm','Forecast'],'A','Climate = khí hậu.'),
    q('"Breeze" nghĩa là?',['Bão lớn','Gió mạnh','Làn gió nhẹ','Lốc xoáy'],'C','Breeze = gió nhẹ.'),
    q('Mặt trời cho ta?',['Rain and snow','Light and heat','Wind and clouds','Fog and mist'],'B','Mặt trời = light and heat.'),
    q('-5°C là?',['Hot','Warm','Cool','Very cold (freezing)'],'D','-5°C = dưới 0, rất lạnh.'),
    q('Nhà khí tượng học làm gì?',['Tạo ra thời tiết','Dự đoán thời tiết','Kiểm soát mưa','Vẽ bầu trời'],'B','Dự đoán thời tiết tương lai.'),
    q('Mây được tạo từ?',['Dust','Smoke','Tiny water droplets','Car gas'],'C','Mây = hạt nước li ti.'),
  ]},

  { name: 'Toys — Đồ chơi của tôi', questions: [
    q('"Ball" nghĩa là?',['Búp bê','Quả bóng','Xe đồ chơi','Xếp hình'],'B','Ball = quả bóng.'),
    q('Đồ chơi nào phổ biến với bé gái?',['Toy car','Doll','Robot','Train set'],'B','Doll = búp bê.'),
    q('"Puzzle" nghĩa là?',['Kéo đàn','Xếp hình/Ghép hình','Bóng bay','Con quay'],'B','Puzzle = ghép hình.'),
    q('Đồ chơi nào cần pin?',['Wooden blocks','Remote-control car','Clay','Paper airplane'],'B','Ô tô điều khiển xa cần pin.'),
    q('"Kite" nghĩa là?',['Con quay','Bong bóng','Diều','Trống'],'C','Kite = con diều.'),
    q('Đồ chơi nào tốt để xây dựng?',['Doll','Ball','LEGO/Building blocks','Kite'],'C','LEGO = xếp hình xây dựng.'),
    q('"Bicycle" nghĩa là?',['Xe ô tô','Xe đạp','Xe máy','Xe đẩy'],'B','Bicycle = xe đạp.'),
    q('Bóng dùng để làm gì?',['Đọc','Ném, bắt, đá','Ăn','Bay'],'B','Ball = throw, catch, kick.'),
    q('"Jump rope" nghĩa là?',['Dây leo','Dây thừng','Nhảy dây','Dây buộc'],'C','Jump rope = nhảy dây.'),
    q('Đồ chơi nào chơi ngoài trời?',['Puzzle','Crayon set','Kite','Board game'],'C','Kite = diều, chơi ngoài trời.'),
    q('"Teddy bear" nghĩa là?',['Gấu trúc thật','Gấu bông đồ chơi','Mèo nhồi bông','Chó thật'],'B','Teddy bear = gấu bông.'),
    q('Đồ chơi nào phát ra âm thanh?',['Clay','Puzzle','Music box/electronic toy','Cardboard box'],'C','Đồ chơi điện tử phát âm thanh.'),
    q('"Robot toy" nghĩa là?',['Người máy đồ chơi','Búp bê','Ô tô đồ chơi','Xếp hình'],'A','Robot toy = đồ chơi người máy.'),
    q('Đồ chơi nào giúp sáng tạo?',['TV remote','Clay/Play-Doh','Broken toy','Nothing'],'B','Clay = đất nặn giúp sáng tạo.'),
    q('"Toy car" nghĩa là?',['Máy bay đồ chơi','Ô tô đồ chơi','Tàu hoả đồ chơi','Thuyền đồ chơi'],'B','Toy car = ô tô đồ chơi.'),
    q('Nhảy dây cần mấy người?',['One','Two or more','No one','Only adults'],'B','Thường cần 2+ người.'),
    q('"Board game" nghĩa là?',['Trò chơi điện tử','Trò chơi trên bàn (cờ vua...)','Trò ngoài trời','Trò âm nhạc'],'B','Board game = cờ vua, cá ngựa...'),
    q('Đồ chơi nào bay trên không?',['Ball','Doll','Kite','Puzzle'],'C','Kite = diều bay.'),
    q('"Con quay" bằng tiếng Anh là?',['Kite','Spinning top','Yo-yo','Hula hoop'],'B','Con quay = spinning top.'),
    q('Ngày mưa trong nhà chơi gì?',['Kite','Bicycle','Puzzle or board game','Jump rope ngoài công viên'],'C','Mưa → chơi trong nhà: puzzle.'),
    q('Đồ chơi giúp trẻ?',['Kém vui hơn','Phát triển kỹ năng và sáng tạo','Không có ích gì','Chỉ làm trẻ lười'],'B','Đồ chơi giúp phát triển kỹ năng.'),
    q('"Toy train" nghĩa là?',['Tàu hoả đồ chơi','Xe đạp đồ chơi','Máy bay đồ chơi','Thuyền đồ chơi'],'A','Toy train = tàu hoả đồ chơi.'),
    q('Đồ chơi nào phát triển trí tuệ?',['Spinning top only','Puzzle and building blocks','Only dolls','Only balls'],'B','Puzzle và xếp hình phát triển trí tuệ.'),
    q('"Balloon" nghĩa là?',['Diều','Bong bóng','Con quay','Trống'],'B','Balloon = bong bóng.'),
    q('Đồ chơi nào không cần pin?',['Remote-control car','Electronic robot','Wooden puzzle','Electronic pet'],'C','Wooden puzzle = không cần pin.'),
    q('"Hula hoop" được dùng thế nào?',['Ném lên không','Xoay quanh hông','Bơi dưới nước','Đá như bóng'],'B','Hula hoop = vòng xoay quanh người.'),
    q('Nam thích xây tháp cao. Đồ chơi phù hợp?',['Doll','LEGO blocks','Kite','Jump rope'],'B','LEGO = xây dựng.'),
    q('Đồ chơi nào an toàn nhất cho trẻ 1 tuổi?',['Small LEGO pieces','Soft plush toy','Sharp toy car','Balloon'],'B','Đồ chơi mềm an toàn nhất cho bé nhỏ.'),
    q('Lan thích ngoài trời. Đồ chơi nào phù hợp?',['Puzzle','Board game','Kite or ball','Crayon set'],'C','Kite hoặc ball = ngoài trời.'),
    q('Đồ chơi nào giúp phát triển thể chất?',['Puzzle only','Board game only','Ball, bicycle, jump rope','Crayons only'],'C','Ball, bicycle, jump rope = vận động.'),
  ]},

  { name: 'Action Words — Từ chỉ hành động', questions: [
    q('"Run" nghĩa là?',['Đi bộ','Chạy','Nhảy','Ngồi'],'B','Run = chạy.'),
    q('"Jump" nghĩa là?',['Bơi','Đá','Nhảy','Bay'],'C','Jump = nhảy.'),
    q('"Eat" nghĩa là?',['Uống','Ăn','Ngủ','Học'],'B','Eat = ăn.'),
    q('"Sleep" nghĩa là?',['Chơi','Chạy','Ngủ','Đọc'],'C','Sleep = ngủ.'),
    q('"Read" nghĩa là?',['Viết','Vẽ','Đọc','Nói'],'C','Read = đọc.'),
    q('"Write" nghĩa là?',['Đọc','Viết','Tô màu','Cắt'],'B','Write = viết.'),
    q('"Draw" nghĩa là?',['Viết','Đọc','Vẽ','Hát'],'C','Draw = vẽ.'),
    q('"Sing" nghĩa là?',['Nhảy','Hát','Chạy','Bơi'],'B','Sing = hát.'),
    q('"Swim" nghĩa là?',['Bay','Chạy','Nhảy','Bơi'],'D','Swim = bơi.'),
    q('"Play" nghĩa là?',['Học','Ăn','Chơi','Ngủ'],'C','Play = chơi.'),
    q('I ___ to school every day. (đi)',['run','jump','walk','sleep'],'C','Walk = đi bộ.'),
    q('"Climb" nghĩa là?',['Nhảy','Leo trèo','Lăn','Trượt'],'B','Climb = leo trèo.'),
    q('"Throw" nghĩa là?',['Bắt','Ném','Đá','Chạy'],'B','Throw = ném.'),
    q('"Catch" nghĩa là?',['Ném','Chạy','Bắt','Đá'],'C','Catch = bắt.'),
    q('"Kick" nghĩa là?',['Ném','Bắt','Đá','Đẩy'],'C','Kick = đá.'),
    q('Lan đang đọc sách. Lan is ___ a book.',['writing','drawing','reading','singing'],'C','Reading = đọc.'),
    q('"Dance" nghĩa là?',['Hát','Nhảy múa','Vẽ','Chạy'],'B','Dance = nhảy múa.'),
    q('"Listen" nghĩa là?',['Nói','Nhìn','Nghe','Hát'],'C','Listen = lắng nghe.'),
    q('"Talk/Speak" nghĩa là?',['Nghe','Nói','Nhìn','Viết'],'B','Talk/Speak = nói.'),
    q('Nam đang bơi trong hồ. Nam is ___ in the pool.',['running','jumping','swimming','walking'],'C','Swimming = bơi.'),
    q('"Open" nghĩa là?',['Đóng','Mở','Cầm','Bỏ'],'B','Open = mở.'),
    q('"Close" nghĩa là?',['Mở','Cầm','Đóng','Đặt'],'C','Close = đóng.'),
    q('"Push" nghĩa là?',['Kéo','Đẩy','Nhấc','Đặt'],'B','Push = đẩy.'),
    q('"Pull" nghĩa là?',['Đẩy','Kéo','Đặt','Ném'],'B','Pull = kéo.'),
    q('Từ hành động nào liên quan đến âm nhạc?',['Run','Jump','Sing','Swim'],'C','Sing = hát, liên quan âm nhạc.'),
    q('I am ___ a picture. (Tôi đang vẽ)',['singing','drawing','running','eating'],'B','Drawing = đang vẽ.'),
    q('"Shout" nghĩa là?',['Thì thầm','La hét','Nói chuyện','Hát'],'B','Shout = la hét.'),
    q('"Whisper" nghĩa là?',['La hét','Thì thầm','Hát to','Nói lớn'],'B','Whisper = thì thầm.'),
    q('Opposite of "sit" là?',['Lie','Stand','Sleep','Cry'],'B','Sit ↔ Stand.'),
    q('Từ hành động nào dùng với "in the water"?',['Run','Climb','Swim','Fly'],'C','Swim = bơi trong nước.'),
  ]},

  { name: 'My House — Nhà của tôi', questions: [
    q('"Kitchen" nghĩa là?',['Phòng ngủ','Bếp','Phòng tắm','Phòng khách'],'B','Kitchen = bếp.'),
    q('"Bedroom" nghĩa là?',['Bếp','Phòng tắm','Phòng ngủ','Nhà kho'],'C','Bedroom = phòng ngủ.'),
    q('Bạn ngủ ở phòng nào?',['Kitchen','Bathroom','Bedroom','Garden'],'C','Ngủ ở Bedroom.'),
    q('"Living room" nghĩa là?',['Bếp','Phòng ngủ','Phòng khách','Nhà để xe'],'C','Living room = phòng khách.'),
    q('Bạn tắm ở đâu?',['Kitchen','Bedroom','Garden','Bathroom'],'D','Bathroom = phòng tắm.'),
    q('"Door" nghĩa là?',['Cửa sổ','Cửa ra vào','Tường','Sàn nhà'],'B','Door = cửa ra vào.'),
    q('"Window" nghĩa là?',['Cửa chính','Cửa sổ','Bức tường','Trần nhà'],'B','Window = cửa sổ.'),
    q('Bạn nấu ăn ở đâu?',['Bedroom','Bathroom','Kitchen','Garage'],'C','Kitchen = bếp để nấu ăn.'),
    q('"Table" nghĩa là?',['Ghế','Bàn','Tủ','Giường'],'B','Table = bàn.'),
    q('"Chair" nghĩa là?',['Bàn','Ghế','Đèn','Tủ'],'B','Chair = ghế.'),
    q('"Bed" nghĩa là?',['Ghế','Bàn','Giường','Tủ'],'C','Bed = giường.'),
    q('Đồ vật nào trong phòng ngủ?',['Stove','Toilet','Bed and wardrobe','Sofa'],'C','Bed and wardrobe = giường và tủ.'),
    q('"Garden" nghĩa là?',['Sân garage','Sân thượng','Khu vườn','Tầng hầm'],'C','Garden = khu vườn.'),
    q('Bạn xem TV ở đâu?',['Kitchen','Bathroom','Living room','Attic'],'C','Living room = phòng khách.'),
    q('"Roof" nghĩa là?',['Sàn nhà','Tường','Mái nhà','Cửa'],'C','Roof = mái nhà.'),
    q('"Floor" nghĩa là?',['Trần nhà','Mái nhà','Sàn nhà','Tường'],'C','Floor = sàn nhà.'),
    q('"Wall" nghĩa là?',['Cửa','Tường','Sàn','Mái'],'B','Wall = tường.'),
    q('Bạn rửa tay ở đâu?',['Kitchen or bathroom','Garden','Bedroom','Garage'],'A','Kitchen/Bathroom đều có bồn rửa.'),
    q('"Sofa/Couch" nghĩa là?',['Ghế đơn','Ghế sofa','Ghế học','Ghế bập bênh'],'B','Sofa = ghế sofa phòng khách.'),
    q('"Lamp" nghĩa là?',['Quạt','Đèn','Tủ lạnh','Điều hòa'],'B','Lamp = đèn.'),
    q('"Stairs" nghĩa là?',['Thang máy','Cầu thang bộ','Lối đi','Cổng'],'B','Stairs = cầu thang.'),
    q('Nhà nào có nhiều tầng cần gì?',['Roof','Stairs','Garden','Garage'],'B','Nhà nhiều tầng cần Stairs.'),
    q('"Garage" nghĩa là?',['Nhà kho','Nhà để xe','Phòng tắm','Tầng hầm'],'B','Garage = nhà để xe.'),
    q('Đồ vật nào ở bếp?',['Bed','Sofa','Refrigerator','Wardrobe'],'C','Refrigerator = tủ lạnh ở bếp.'),
    q('"Ceiling" nghĩa là?',['Sàn nhà','Tường','Trần nhà','Mái nhà'],'C','Ceiling = trần nhà.'),
    q('Ngôi nhà thường có mấy tầng?',['Always 1','Always 2','Varies (1, 2, 3+)','Always 10'],'C','Nhà có thể 1, 2, 3+ tầng.'),
    q('Phòng nào thường nhỏ nhất?',['Living room','Bedroom','Bathroom','Kitchen'],'C','Bathroom thường nhỏ nhất.'),
    q('"Front door" vs "back door" khác nhau thế nào?',['Cùng là cửa ra vào, vị trí khác','Hoàn toàn giống nhau','Front door không có ổ khoá','Back door không có tay cầm'],'A','Front door = cửa trước, back door = cửa sau.'),
    q('Nhà ở nông thôn thường có?',['Elevator','Large garden','Subway station','Shopping mall'],'B','Nhà nông thôn thường có sân vườn lớn.'),
    q('Phòng khách (living room) dùng để?',['Ngủ','Nấu ăn','Tụ họp gia đình, xem TV','Tắm'],'C','Living room = tụ họp, xem TV.'),
  ]},

  { name: 'Clothes — Quần áo', questions: [
    q('"T-shirt" nghĩa là?',['Quần jean','Áo phông','Váy','Áo khoác'],'B','T-shirt = áo phông.'),
    q('"Pants/Trousers" nghĩa là?',['Áo','Quần dài','Váy','Tất'],'B','Pants = quần dài.'),
    q('Trời lạnh mặc gì?',['T-shirt and shorts','Coat and gloves','Swimsuit','Sandals'],'B','Coat and gloves = áo khoác và găng tay.'),
    q('"Shoes" nghĩa là?',['Tất','Dép','Giày','Mũ'],'C','Shoes = giày.'),
    q('"Hat" nghĩa là?',['Khăn','Mũ/Nón','Kính','Cài tóc'],'B','Hat = mũ/nón.'),
    q('Đi bơi mặc gì?',['Coat','Jeans','Swimsuit','School uniform'],'C','Swimsuit = đồ bơi.'),
    q('"Socks" nghĩa là?',['Giày','Tất','Dép','Mũ'],'B','Socks = tất.'),
    q('"Dress" nghĩa là?',['Quần dài','Áo phông','Váy liền','Áo khoác'],'C','Dress = váy liền thân.'),
    q('"Jacket" nghĩa là?',['Áo phông','Áo khoác ngắn','Quần đùi','Váy'],'B','Jacket = áo khoác.'),
    q('Trời nắng nóng mặc gì?',['Coat and boots','T-shirt and shorts','Heavy sweater','Gloves'],'B','T-shirt and shorts = áo phông + quần đùi.'),
    q('"Scarf" nghĩa là?',['Mũ','Găng tay','Khăn quàng cổ','Ủng'],'C','Scarf = khăn quàng cổ.'),
    q('"Gloves" nghĩa là?',['Tất','Mũ','Khăn','Găng tay'],'D','Gloves = găng tay.'),
    q('"Boots" nghĩa là?',['Giày thể thao','Dép','Ủng','Tất'],'C','Boots = ủng.'),
    q('Mặc đồng phục trường học gọi là?',['School jacket','School uniform','School bag','School cap'],'B','School uniform = đồng phục.'),
    q('"Jeans" nghĩa là?',['Quần vải','Quần jean','Váy','Quần đùi'],'B','Jeans = quần jean.'),
    q('Trời mưa nên mặc/mang gì?',['Swimsuit','Raincoat and boots','Sandals','Shorts'],'B','Raincoat + boots = áo mưa + ủng.'),
    q('"Sweater" nghĩa là?',['Áo phông','Áo len','Áo khoác ngoài','Áo sơ mi'],'B','Sweater = áo len.'),
    q('"Skirt" nghĩa là?',['Quần dài','Váy rời','Áo liền váy','Áo phông'],'B','Skirt = váy rời.'),
    q('Mặc gì để ngủ?',['School uniform','Pajamas','Raincoat','Swimsuit'],'B','Pajamas = đồ ngủ.'),
    q('"Uniform" nghĩa là?',['Quần áo tự chọn','Đồng phục','Đồ ngủ','Đồ bơi'],'B','Uniform = đồng phục.'),
    q('"Button" trên quần áo là?',['Dây kéo','Nút cài áo','Túi áo','Cổ áo'],'B','Button = cúc/nút cài.'),
    q('"Zipper" nghĩa là?',['Nút cài','Dây kéo','Túi','Cổ'],'B','Zipper = dây kéo khoá.'),
    q('Quần áo nào thường mặc ở nhà thôi?',['Jeans','Pajamas/Sleepwear','School uniform','Swimsuit'],'B','Pajamas thường mặc ở nhà.'),
    q('Chọn quần áo mùa đông đúng?',['T-shirt, shorts, sandals','Heavy coat, boots, gloves, scarf','Swimsuit','Thin dress'],'B','Mùa đông: Heavy coat, boots, gloves, scarf.'),
    q('"Pocket" nghĩa là?',['Cổ áo','Túi áo','Tay áo','Gấu áo'],'B','Pocket = túi áo.'),
    q('Quần áo được làm từ vật liệu nào?',['Plastic, glass','Cotton, wool, polyester','Wood, metal','Paper, cardboard'],'B','Quần áo thường từ cotton, len, polyester.'),
    q('Đi học mặc gì?',['Pajamas','School uniform or neat clothes','Swimsuit','Sports gear only'],'B','Đi học = đồng phục hoặc quần áo gọn gàng.'),
    q('Mặc ___ khi trời quá nắng để bảo vệ đầu.',['Boots','Gloves','Hat/Cap','Scarf'],'C','Hat/Cap = mũ che nắng.'),
    q('"Raincoat" nghĩa là?',['Áo len','Áo mưa','Áo khoác da','Áo phao'],'B','Raincoat = áo mưa.'),
    q('Mặc gì phù hợp khi đi dự tiệc?',['Pajamas','Old torn clothes','Neat dress or shirt','Swimsuit'],'C','Tiệc = mặc đẹp, gọn gàng.'),
  ]},

  { name: 'Transport — Phương tiện giao thông', questions: [
    q('"Car" nghĩa là?',['Xe đạp','Ô tô','Xe máy','Xe buýt'],'B','Car = ô tô.'),
    q('"Bus" nghĩa là?',['Xe tải','Xe buýt','Tàu hỏa','Máy bay'],'B','Bus = xe buýt.'),
    q('Phương tiện nào bay trên không?',['Car','Boat','Airplane','Train'],'C','Airplane = máy bay, bay trên không.'),
    q('"Bicycle" nghĩa là?',['Ô tô','Xe máy','Xe đạp','Xe buýt'],'C','Bicycle = xe đạp.'),
    q('"Train" nghĩa là?',['Xe buýt','Ô tô','Tàu hỏa','Tàu thủy'],'C','Train = tàu hỏa.'),
    q('Phương tiện nào đi trên biển?',['Plane','Car','Train','Ship/Boat'],'D','Ship/Boat = tàu thủy đi biển.'),
    q('"Motorcycle" nghĩa là?',['Xe đạp','Xe máy','Ô tô','Xe buýt'],'B','Motorcycle = xe máy.'),
    q('"Truck" nghĩa là?',['Xe buýt','Xe tải','Xe máy','Xe đạp'],'B','Truck = xe tải.'),
    q('Phương tiện nào thân thiện với môi trường?',['Car','Motorcycle','Bicycle','Truck'],'C','Bicycle = xe đạp, không xăng.'),
    q('"Helicopter" nghĩa là?',['Máy bay thông thường','Trực thăng','Khinh khí cầu','Tàu vũ trụ'],'B','Helicopter = trực thăng.'),
    q('Phương tiện nào đi trên đường ray?',['Car','Bus','Train','Bicycle'],'C','Train đi trên đường ray.'),
    q('"Taxi" nghĩa là?',['Xe buýt','Xe taxi','Xe tải','Tàu hỏa'],'B','Taxi = xe taxi.'),
    q('Đi học gần nhà, bạn có thể đi bằng?',['Airplane','Ship','Bicycle or walking','Train'],'C','Gần = đi bộ hoặc xe đạp.'),
    q('"Traffic light" nghĩa là?',['Đèn đường','Đèn giao thông','Đèn pin','Đèn chiếu sáng'],'B','Traffic light = đèn giao thông.'),
    q('Đèn đỏ nghĩa là?',['Đi','Chú ý','Dừng lại','Chạy nhanh'],'C','Đèn đỏ = dừng lại (Stop).'),
    q('"Crosswalk" nghĩa là?',['Đường cao tốc','Ngã tư','Vạch qua đường','Vỉa hè'],'C','Crosswalk = vạch qua đường (vạch ngựa vằn).'),
    q('Phương tiện nào chở nhiều hành khách nhất?',['Car','Motorcycle','Airplane','Bicycle'],'C','Airplane chở nhiều hành khách.'),
    q('"Subway/Metro" nghĩa là?',['Xe buýt','Tàu điện ngầm','Tàu hỏa trên cao','Tàu thủy'],'B','Subway/Metro = tàu điện ngầm.'),
    q('"Ambulance" nghĩa là?',['Xe cảnh sát','Xe cứu thương','Xe cứu hỏa','Xe buýt'],'B','Ambulance = xe cứu thương.'),
    q('"Fire truck" nghĩa là?',['Xe buýt','Xe cứu thương','Xe cứu hỏa','Xe tải thường'],'C','Fire truck = xe cứu hỏa.'),
    q('Bạn đi qua đường ở đâu?',['Anywhere','Only on crosswalk','In the middle of the road','Between cars'],'B','Qua đường ở vạch qua đường (crosswalk).'),
    q('"Seatbelt" nghĩa là?',['Dây an toàn xe hơi','Thắt lưng thường','Dây đeo ba lô','Xích xe đạp'],'A','Seatbelt = dây an toàn.'),
    q('Tại sao phải đội mũ khi đi xe đạp?',['Cho đẹp','Bảo vệ đầu khi ngã','Giữ ấm','Cho mát'],'B','Mũ bảo hiểm bảo vệ đầu.'),
    q('"Road sign" nghĩa là?',['Đèn giao thông','Biển báo giao thông','Vạch qua đường','Dải phân cách'],'B','Road sign = biển báo giao thông.'),
    q('Phương tiện nào không cần xăng?',['Car','Motorcycle','Truck','Bicycle'],'D','Bicycle = xe đạp, không cần xăng.'),
    q('"Pilot" là người?',['Lái tàu thủy','Lái tàu hỏa','Lái máy bay','Lái xe buýt'],'C','Pilot = phi công lái máy bay.'),
    q('"Driver" nghĩa là?',['Phi công','Tài xế lái xe','Thuyền trưởng','Thợ cơ khí'],'B','Driver = tài xế.'),
    q('Ở Việt Nam, đi bên nào của đường?',['Bên trái','Bên phải','Giữa đường','Tùy ý'],'B','Việt Nam đi bên phải đường.'),
    q('Phương tiện nào an toàn nhất trong bão?',['Motorcycle','Bicycle','Car','Stay indoors (not travel)'],'D','Bão nên ở trong nhà, không di chuyển.'),
    q('Đèn xanh (green light) nghĩa là?',['Dừng lại','Chú ý','Được đi','Chạy thật nhanh'],'C','Green light = được đi (Go).'),
  ]},

  { name: 'Fruits & Veggies — Hoa quả và rau củ', questions: [
    q('"Apple" nghĩa là?',['Chuối','Táo','Cam','Xoài'],'B','Apple = táo.'),
    q('"Banana" nghĩa là?',['Táo','Dứa','Chuối','Dưa hấu'],'C','Banana = chuối.'),
    q('"Orange" (quả) nghĩa là?',['Táo','Nho','Quả cam','Dâu'],'C','Orange = quả cam.'),
    q('"Carrot" nghĩa là?',['Khoai tây','Hành','Cà rốt','Bắp'],'C','Carrot = cà rốt.'),
    q('"Tomato" là rau hay quả?',['Chỉ là rau','Chỉ là quả','Vừa là quả vừa được xếp vào rau','Không phải rau cũng không phải quả'],'C','Tomato = thực vật dạng quả nhưng thường dùng như rau.'),
    q('"Mango" nghĩa là?',['Ổi','Xoài','Đu đủ','Vải'],'B','Mango = xoài.'),
    q('"Potato" nghĩa là?',['Khoai tây','Khoai lang','Sắn','Ngô'],'A','Potato = khoai tây.'),
    q('"Watermelon" nghĩa là?',['Dưa leo','Dưa hấu','Bí ngô','Bí đao'],'B','Watermelon = dưa hấu.'),
    q('"Grapes" nghĩa là?',['Dâu tây','Nho','Cherry','Việt quất'],'B','Grapes = nho.'),
    q('"Onion" nghĩa là?',['Tỏi','Hành tây','Gừng','Ớt'],'B','Onion = hành tây.'),
    q('Quả nào có màu vàng?',['Apple','Watermelon','Banana','Grapes'],'C','Banana = chuối vàng.'),
    q('"Pineapple" nghĩa là?',['Dừa','Đu đủ','Dứa/Thơm','Khế'],'C','Pineapple = dứa/thơm.'),
    q('"Cabbage" nghĩa là?',['Cải xanh','Bắp cải','Rau bina','Xà lách'],'B','Cabbage = bắp cải.'),
    q('Rau củ tốt cho sức khoẻ vì?',['Chứa nhiều đường','Chứa vitamin và chất xơ','Có nhiều chất béo','Không có gì đặc biệt'],'B','Rau củ = vitamins và chất xơ.'),
    q('"Strawberry" nghĩa là?',['Việt quất','Mâm xôi','Dâu tây','Cherry'],'C','Strawberry = dâu tây.'),
    q('"Corn/Maize" nghĩa là?',['Đậu bắp','Ngô/Bắp','Khoai lang','Sắn'],'B','Corn = ngô/bắp.'),
    q('"Lettuce" nghĩa là?',['Cải bó xôi','Xà lách','Rau muống','Cải thảo'],'B','Lettuce = xà lách.'),
    q('Quả nào màu đỏ?',['Banana','Apple or strawberry','Mango','Pineapple'],'B','Apple và strawberry đều đỏ.'),
    q('"Garlic" nghĩa là?',['Hành lá','Hành tây','Tỏi','Gừng'],'C','Garlic = tỏi.'),
    q('Ăn nhiều rau củ giúp?',['Béo phì','Sức khỏe tốt, nhiều vitamin','Buồn ngủ','Đau bụng'],'B','Rau củ = sức khỏe tốt.'),
    q('"Broccoli" nghĩa là?',['Cải xanh','Bông cải xanh','Bắp cải','Súp lơ trắng'],'B','Broccoli = bông cải xanh.'),
    q('"Peach" nghĩa là?',['Lê','Mận','Đào','Mơ'],'C','Peach = đào.'),
    q('Quả nào có múi (segments)?',['Apple','Orange','Banana','Watermelon'],'B','Orange = cam có múi.'),
    q('"Spinach" nghĩa là?',['Xà lách','Cải bó xôi','Rau muống','Bắp cải'],'B','Spinach = cải bó xôi.'),
    q('Màu của cà rốt (carrot)?',['Red','Green','Orange','Yellow'],'C','Carrot = màu cam.'),
    q('"Cherry" nghĩa là?',['Nho','Quả anh đào','Dâu tây','Việt quất'],'B','Cherry = quả anh đào.'),
    q('Ăn ___ mỗi ngày tốt cho sức khỏe (theo WHO)',['No fruits/veggies','5 portions of fruits and veggies','Only meat','Only sweets'],'B','WHO khuyến cáo ăn 5 phần rau củ quả/ngày.'),
    q('"Pear" nghĩa là?',['Táo','Quả lê','Đào','Mận'],'B','Pear = quả lê.'),
    q('Quả nào KHÔNG có hạt bên trong?',['Watermelon','Banana (most cultivated have no seeds)','Orange','Apple'],'B','Chuối thương mại thường không có hạt.'),
    q('Cà chua và dưa leo thường dùng trong?',['Salad','Soup only','Dessert','Juice only'],'A','Cà chua và dưa leo thường dùng trong salad.'),
  ]},

  { name: 'Phonics A-M — Phát âm A-M', questions: [
    q('"A" sounds like ___ in "Apple"',['ei (like "age")','æ (short, like in "cat")','ah (like "father")','ay (like "play")'],'B','Short A = /æ/ như trong "apple", "cat".'),
    q('"B" sounds like ___ in "Ball"',['P sound','D sound','B (voiced, like "baby")','V sound'],'C','B = /b/ âm có giọng.'),
    q('"C" sounds like ___ in "Cat"',['S','K','Ch','G'],'B','C trước a,o,u = /k/ như "cat", "cup".'),
    q('"D" sounds like ___ in "Dog"',['T','G','D (voiced)','B'],'C','D = /d/ như "dog", "dad".'),
    q('"E" sounds like ___ in "Elephant"',['Long ee','Short e (like "bed")','uh','ay'],'B','Short E = /ɛ/ như "elephant", "bed".'),
    q('"F" sounds like ___ in "Fish"',['V','Ph/F (like "fun")','S','B'],'B','F = /f/ như "fish", "fun".'),
    q('"G" sounds like ___ in "Go"',['J','G (hard, like "game")','K','Ch'],'B','G trước a,o,u = /g/ cứng như "go", "game".'),
    q('"H" sounds like ___ in "Hat"',['Silent','Breathed H (like "hello")','Ch','Wh'],'B','H = /h/ hơi thở như "hat", "hello".'),
    q('"I" sounds like ___ in "Igloo"',['Long i (like "ice")','Short i (like "sit")','ee','uh'],'B','Short I = /ɪ/ như "igloo", "sit".'),
    q('"J" sounds like ___ in "Jump"',['Y','Ch','J (like "jam")','G'],'C','J = /dʒ/ như "jump", "jam".'),
    q('"K" sounds like ___ in "Kite"',['S','G','K (like "key")','Ch'],'C','K = /k/ như "kite", "key".'),
    q('"L" sounds like ___ in "Lion"',['R','W','L (like "love")','N'],'C','L = /l/ như "lion", "love".'),
    q('"M" sounds like ___ in "Mouse"',['N','M (like "mom")','B','W'],'B','M = /m/ như "mouse", "mom".'),
    q('Which word starts with "A"?',['Ball','Apple','Car','Dog'],'B','Apple bắt đầu bằng A.'),
    q('Which word starts with "B"?',['Apple','Cat','Ball','Dog'],'C','Ball bắt đầu bằng B.'),
    q('Which word starts with "C"?',['Dog','Bird','Cat','Apple'],'C','Cat bắt đầu bằng C.'),
    q('Which word starts with "D"?',['Cat','Fish','Apple','Dog'],'D','Dog bắt đầu bằng D.'),
    q('Which word starts with "E"?',['Apple','Elephant','Cat','Dog'],'B','Elephant bắt đầu bằng E.'),
    q('Which word starts with "F"?',['Dog','Apple','Fish','Cat'],'C','Fish bắt đầu bằng F.'),
    q('Which word starts with "G"?',['Cat','Apple','Dog','Goat'],'D','Goat bắt đầu bằng G.'),
    q('Which word starts with "H"?',['Apple','Cat','Hat','Dog'],'C','Hat bắt đầu bằng H.'),
    q('Which word starts with "I"?',['Apple','Igloo','Cat','Dog'],'B','Igloo bắt đầu bằng I.'),
    q('Which word starts with "J"?',['Cat','Apple','Dog','Jump'],'D','Jump bắt đầu bằng J.'),
    q('Which word starts with "K"?',['Apple','Cat','Kite','Dog'],'C','Kite bắt đầu bằng K.'),
    q('Which word starts with "L"?',['Cat','Dog','Lion','Apple'],'C','Lion bắt đầu bằng L.'),
    q('Which word starts with "M"?',['Cat','Apple','Dog','Mouse'],'D','Mouse bắt đầu bằng M.'),
    q('What letter does "Ant" start with?',['B','A','C','D'],'B','Ant bắt đầu bằng A.'),
    q('What letter does "Mango" start with?',['N','B','A','M'],'D','Mango bắt đầu bằng M.'),
    q('What letter does "Kite" start with?',['K','C','G','T'],'A','Kite bắt đầu bằng K.'),
    q('Which pair matches the same starting letter?',['Apple – Dog','Ball – Bear','Cat – Dog','Fish – Goat'],'B','Ball và Bear đều bắt đầu bằng B.'),
  ]},

  { name: 'Phonics N-Z — Phát âm N-Z', questions: [
    q('"N" sounds like ___ in "Nose"',['M','L','N (like "name")','NG'],'C','N = /n/ như "nose", "name".'),
    q('"O" sounds like ___ in "On"',['Long o (like "go")','Short o (like "hot")','oo (like "boot")','ow (like "how")'],'B','Short O = /ɒ/ như "on", "hot".'),
    q('"P" sounds like ___ in "Pencil"',['B','F','P (like "pen")','T'],'C','P = /p/ như "pencil", "pen".'),
    q('"Q" is usually followed by?',['A','E','I','U'],'D','Q thường đi với U: "qu" = /kw/ như "queen".'),
    q('"R" sounds like ___ in "Red"',['L','W','R (like "run")','D'],'C','R = /r/ như "red", "run".'),
    q('"S" sounds like ___ in "Sun"',['Z','S (like "sit")','Sh','Ch'],'B','S = /s/ như "sun", "sit".'),
    q('"T" sounds like ___ in "Toy"',['D','T (like "top")','Ch','Th'],'B','T = /t/ như "toy", "top".'),
    q('"U" sounds like ___ in "Under"',['Long u (like "use")','Short u (like "cut")','oo','uh'],'B','Short U = /ʌ/ như "under", "cut".'),
    q('"V" sounds like ___ in "Violin"',['F','B','V (voiced, like "van")','W'],'C','V = /v/ như "violin", "van".'),
    q('"W" sounds like ___ in "Water"',['V','W (like "wind")','U','R'],'B','W = /w/ như "water", "wind".'),
    q('"X" at the end sounds like ___ in "Fox"',['Z','Ks (like "fox")','Ch','G'],'B','X = /ks/ như "fox", "box".'),
    q('"Y" sounds like ___ in "Yes"',['J','I','Y (like "yellow")','E'],'C','Y = /j/ như "yes", "yellow".'),
    q('"Z" sounds like ___ in "Zebra"',['S','Z (voiced, like "zoo")','Ch','X'],'B','Z = /z/ như "zebra", "zoo".'),
    q('Which word starts with "N"?',['Mango','Kite','Nose','Apple'],'C','Nose bắt đầu bằng N.'),
    q('Which word starts with "O"?',['Apple','Nose','Orange','Plum'],'C','Orange bắt đầu bằng O.'),
    q('Which word starts with "P"?',['Apple','Orange','Nose','Pencil'],'D','Pencil bắt đầu bằng P.'),
    q('Which word starts with "R"?',['Sun','Toy','Rainbow','Pencil'],'C','Rainbow bắt đầu bằng R.'),
    q('Which word starts with "S"?',['Toy','Sun','Rainbow','Pencil'],'B','Sun bắt đầu bằng S.'),
    q('Which word starts with "T"?',['Sun','Tiger','Pencil','Rain'],'B','Tiger bắt đầu bằng T.'),
    q('Which word starts with "V"?',['Violin','Sun','Tiger','Rainbow'],'A','Violin bắt đầu bằng V.'),
    q('Which word starts with "W"?',['Violin','Sun','Water','Tiger'],'C','Water bắt đầu bằng W.'),
    q('Which word starts with "Y"?',['Water','Violin','Tiger','Yellow'],'D','Yellow bắt đầu bằng Y.'),
    q('Which word starts with "Z"?',['Yellow','Water','Zebra','Violin'],'C','Zebra bắt đầu bằng Z.'),
    q('What letter does "Umbrella" start with?',['A','O','U','I'],'C','Umbrella bắt đầu bằng U.'),
    q('What letter does "Rain" start with?',['L','R','N','W'],'B','Rain bắt đầu bằng R.'),
    q('What letter does "Violin" start with?',['W','U','B','V'],'D','Violin bắt đầu bằng V.'),
    q('What letter does "Zebra" start with?',['S','X','Z','Y'],'C','Zebra bắt đầu bằng Z.'),
    q('Which pair matches the same starting letter?',['Sun – Tiger','Nose – Nail','Water – Violet','Zoo – Yarn'],'B','Nose và Nail đều bắt đầu bằng N.'),
    q('Arrange A-Z: which comes first — T, R, S?',['T, R, S','R, S, T','S, R, T','T, S, R'],'B','R(18), S(19), T(20) → R, S, T.'),
    q('How many letters are in the English alphabet?',['24','25','26','27'],'C','Bảng chữ cái tiếng Anh có 26 chữ.'),
  ]},

  { name: 'Story Time — Đọc truyện vui', questions: [
    q('In a story, the main character is called?',['The author','The setting','The protagonist/hero','The title'],'C','Protagonist/Hero = nhân vật chính.'),
    q('The beginning of a story starts with?',['The end','Once upon a time...','To be continued...','The moral'],'B','Once upon a time = Ngày xửa ngày xưa (câu mở đầu).'),
    q('In "The Three Little Pigs", who is the villain?',['The pig','The wolf','The farmer','The spider'],'B','The Big Bad Wolf = kẻ phản diện.'),
    q('"The Tortoise and the Hare" teaches us?',['Fast always wins','Slow and steady wins the race','Never give up and stay fast','Skip the race'],'B','Chăm chỉ, kiên nhẫn thắng nhanh nhẹn.'),
    q('What is the "setting" of a story?',['The main character','Where and when the story happens','The ending','The author'],'B','Setting = bối cảnh câu chuyện.'),
    q('In "Cinderella", what turns into a carriage?',['An apple','A pumpkin','A shoe','A cat'],'B','Quả bí ngô biến thành cỗ xe.'),
    q('A "fairy tale" usually has?',['Machines and robots','Magic and happy ending','Sad ending only','No characters'],'B','Fairy tale = truyện cổ tích có phép thuật và kết có hậu.'),
    q('In "Snow White", the magic object is?',['A shoe','A mirror','A lamp','A flower'],'B','Magic mirror = gương thần.'),
    q('What is the "moral" of a story?',['The title','The beginning','The lesson or message','The setting'],'C','Moral = bài học từ câu chuyện.'),
    q('In "Goldilocks", she enters whose house?',['Wolves','Three Bears','Seven Dwarfs','Giants'],'B','Three Bears = nhà ba con gấu.'),
    q('What does a story need to have?',['Only pictures','Beginning, middle, and end','Only dialogue','Only a title'],'B','Câu chuyện cần có đầu, giữa, cuối.'),
    q('"Aladdin" has a magic?',['Hat','Mirror','Lamp','Ring'],'C','Đèn thần = magic lamp.'),
    q('In "Little Red Riding Hood", she visits?',['Her friend','Her grandmother','Her teacher','Her cousin'],'B','Little Red Riding Hood thăm bà.'),
    q('Who wrote "The Ugly Duckling"?',['Brothers Grimm','Charles Perrault','Hans Christian Andersen','Aesop'],'C','Hans Christian Andersen viết The Ugly Duckling.'),
    q('In a story, the "plot" is?',['The pictures','The series of events','The author\'s name','The setting'],'B','Plot = cốt truyện, chuỗi sự kiện.'),
    q('In "Jack and the Beanstalk", what does Jack trade his cow for?',['Gold','Magic beans','A lamp','A harp'],'B','Jack đổi bò lấy đậu thần.'),
    q('A character who is good and helps others is called?',['Villain','Hero/Heroine','Monster','Narrator'],'B','Hero/Heroine = nhân vật tốt, anh hùng.'),
    q('What is the "climax" of a story?',['The beginning','The most exciting moment','The moral','The author'],'B','Climax = điểm kịch tính nhất.'),
    q('"The Lion and the Mouse" teaches?',['Big animals are always right','Even small creatures can help others','Lions are scary','Mice are useless'],'B','Dù nhỏ cũng có thể giúp người khác.'),
    q('Stories help children?',['Only learn words','Develop imagination, vocabulary, and values','Only memorize facts','Only practice writing'],'B','Truyện giúp phát triển trí tưởng tượng, từ vựng, và giá trị.'),
    q('In "Sleeping Beauty", the princess falls asleep after?',['Eating an apple','Pricking her finger on a spinning wheel','Drinking a potion','Touching a mirror'],'B','Nàng ngủ vì chạm vào kim xe chỉ.'),
    q('A "narrator" in a story is?',['The hero','The villain','The person telling the story','The setting'],'C','Narrator = người kể chuyện.'),
    q('"Hansel and Gretel" find a house made of?',['Gold','Candy/gingerbread','Straw','Wood'],'B','Ngôi nhà làm bằng kẹo gừng.'),
    q('What type of story teaches a lesson through animal characters?',['Fairy tale','Fable','Legend','Myth'],'B','Fable = ngụ ngôn, thường có nhân vật là động vật.'),
    q('In "The Little Mermaid", Ariel wants to become?',['A bird','A human','A mermaid queen','A witch'],'B','Ariel muốn trở thành người.'),
    q('Which animal changes color to hide?',['Dog','Elephant','Chameleon','Tiger'],'C','Chameleon thay đổi màu ngụy trang.'),
    q('A story with pictures for young children is called?',['Novel','Comic','Picture book','Encyclopedia'],'C','Picture book = sách tranh cho trẻ nhỏ.'),
    q('In "The Ant and the Grasshopper", who works hard?',['The grasshopper','The ant','Both','Neither'],'B','The ant = con kiến chăm chỉ chuẩn bị cho mùa đông.'),
    q('What makes a story interesting?',['No characters','Exciting plot, interesting characters','Only description','Only dialogue'],'B','Cốt truyện hấp dẫn và nhân vật thú vị.'),
    q('If a story ends "happily ever after", it means?',['Bad ending','The hero dies','Everyone lives happily','The story continues'],'C','Happily ever after = sống hạnh phúc mãi mãi.'),
  ]},
];
