// Python Lớp 3-5 — 20 subjects × 30 questions
function q(c, opts, k, e) {
  return { content: c, options: [{key:'A',text:opts[0]},{key:'B',text:opts[1]},{key:'C',text:opts[2]},{key:'D',text:opts[3]}], correctAnswer: k, explanation: e };
}

module.exports = [
  { name: 'Python là gì? Lập trình viên nhỏ tuổi', questions: [
    q('Python là gì?',['Loài rắn','Ngôn ngữ lập trình','Trò chơi điện tử','Phần mềm vẽ'],'B','Python là ngôn ngữ lập trình phổ biến.'),
    q('Python được tạo ra bởi ai?',['Bill Gates','Guido van Rossum','Steve Jobs','Elon Musk'],'B','Guido van Rossum tạo Python năm 1991.'),
    q('Python thường được dùng để làm gì?',['Chỉ game','Website, AI, phân tích dữ liệu, tự động hóa','Chỉ vẽ','Chỉ âm nhạc'],'B','Python đa năng: web, AI, data, automation.'),
    q('Để chạy Python, ta cần cài đặt gì?',['Microsoft Word','Python interpreter','Photoshop','Notepad'],'B','Cần cài Python interpreter (python.org).'),
    q('IDE nào phổ biến để học Python cho trẻ em?',['IDLE (Python built-in), Thonny','Scratch only','Photoshop','Word'],'A','IDLE và Thonny = IDE thân thiện cho người mới.'),
    q('File Python có đuôi mở rộng nào?',['*.doc','*.py','*.jpg','*.exe'],'B','File Python lưu với đuôi .py.'),
    q('Python dùng thụt lề (indentation) để làm gì?',['Trang trí','Xác định khối code (block)','Đổi màu chữ','Tốc độ chạy'],'B','Indentation = xác định phạm vi block code.'),
    q('Comment trong Python bắt đầu bằng ký hiệu gì?',['//','/*','#','<!--'],'C','# = ký hiệu comment trong Python.'),
    q('Lập trình viên làm gì?',['Chơi game','Viết code để máy tính thực hiện tác vụ','Vẽ tranh','Hát nhạc'],'B','Lập trình viên viết code điều khiển máy tính.'),
    q('Python có kiểu gõ (typing) như thế nào?',['Static typing (khai báo kiểu trước)','Dynamic typing (tự nhận kiểu)','No typing','Manual typing only'],'B','Python = dynamic typing, không cần khai báo kiểu.'),
    q('Khi gặp lỗi (error), lập trình viên nên làm gì?',['Bỏ cuộc','Đọc thông báo lỗi, debug, tìm giải pháp','Xóa file','Tắt máy'],'B','Debug = đọc lỗi và tìm cách sửa.'),
    q('Python version hiện tại phổ biến nhất?',['Python 1','Python 2','Python 3','Python 10'],'C','Python 3 là phiên bản hiện đại.'),
    q('Lệnh nào đầu tiên nhiều người học Python?',['import sys','print("Hello World")','exit()','input()'],'B','Hello World = bài đầu tiên truyền thống.'),
    q('Python so với Scratch khác nhau thế nào?',['Giống nhau','Python = text-based, Scratch = block-based','Python dễ hơn','Scratch mạnh hơn'],'B','Text vs block = sự khác biệt chính.'),
    q('Tại sao Python phù hợp cho người mới học?',['Syntax phức tạp','Cú pháp đơn giản, dễ đọc như tiếng Anh','Rất khó','Chỉ cho chuyên gia'],'B','Python = syntax gần giống tiếng Anh tự nhiên.'),
    q('IDLE là gì?',['Idle time','IDE tích hợp cùng Python','Tên lỗi','Loại variable'],'B','IDLE = Integrated Development and Learning Environment đi kèm Python.'),
    q('Để chạy file Python từ terminal/cmd?',['python file.py','run file.py','execute file.py','start file.py'],'A','python file.py = chạy script Python.'),
    q('Python được dùng trong AI như thế nào?',['Không dùng','Viết thuật toán ML với TensorFlow, scikit-learn...','Chỉ game AI','Chỉ robot'],'B','Python = ngôn ngữ chính cho AI/ML.'),
    q('Lỗi SyntaxError trong Python nghĩa là?',['Lỗi logic','Lỗi cú pháp (viết code sai quy tắc)','Lỗi kết nối','Lỗi file'],'B','SyntaxError = viết code không đúng cú pháp Python.'),
    q('print() trong Python dùng để làm gì?',['Đọc input','In/Hiển thị nội dung ra màn hình','Tính toán','Lưu file'],'B','print() = in ra console/terminal.'),
    q('Python có thể làm game không?',['Không','Có, với thư viện pygame','Chỉ Scratch mới làm game','Chỉ C++ mới làm game'],'B','Pygame = thư viện làm game với Python.'),
    q('Bug trong lập trình là gì?',['Côn trùng trong máy tính','Lỗi trong code','Loại biến','Tên hàm'],'B','Bug = lỗi trong code gây ra hành vi không mong muốn.'),
    q('Thuật toán (algorithm) là gì?',['Loại variable','Tập hợp bước giải quyết vấn đề','Tên file','Loại lỗi'],'B','Algorithm = chuỗi bước có thứ tự giải quyết vấn đề.'),
    q('Python có thể chạy trên hệ điều hành nào?',['Chỉ Windows','Chỉ Mac','Windows, Mac, Linux - đa nền tảng','Chỉ Linux'],'C','Python = cross-platform, chạy mọi OS.'),
    q('Điều đầu tiên nên học trong Python là?',['AI phức tạp','print(), variable, input() cơ bản','Database','Web server'],'B','Bắt đầu với print, variable, input = nền tảng.'),
    q('Python vs Java khác nhau điểm gì?',['Giống nhau','Python đơn giản hơn, ít code hơn cho cùng tác vụ','Java dễ hơn','Python chậm hơn nhiều'],'B','Python = ít code hơn để làm cùng việc.'),
    q('Thư viện (library) trong Python là gì?',['Thư viện sách','Bộ code sẵn có để tái sử dụng','Loại variable','Tên file'],'B','Library = code sẵn có, import để dùng.'),
    q('import trong Python dùng để làm gì?',['In ra màn hình','Nhập dữ liệu từ file','Nạp thư viện/module','Xóa biến'],'C','import = nạp module/thư viện vào chương trình.'),
    q('Python community (cộng đồng) như thế nào?',['Nhỏ và khép kín','Lớn, friendly, nhiều tài liệu miễn phí','Chỉ có người nói tiếng Anh','Rất đắt để gia nhập'],'B','Python community = lớn, thân thiện, nhiều tài nguyên miễn phí.'),
    q('Lập trình giúp trẻ em phát triển kỹ năng gì?',['Chỉ kỹ thuật','Tư duy logic, giải quyết vấn đề, sáng tạo','Chỉ toán học','Chỉ tiếng Anh'],'B','Coding = logic + problem-solving + creativity.'),
  ]},

  { name: 'print() — Cho máy tính nói chuyện', questions: [
    q('Cú pháp đúng để in "Hello"?',['print Hello','print("Hello")','Print("Hello")','echo "Hello"'],'B','print("Hello") - dùng dấu ngoặc đơn và ngoặc kép.'),
    q('Kết quả của print(2 + 3)?',['23','5','2+3','Error'],'B','Python tính 2+3=5 rồi in ra.'),
    q('Kết quả của print("2 + 3")?',['5','2+3','Error','23'],'B','Chuỗi "2 + 3" in ra nguyên văn.'),
    q('print("Xin chào", "Python") in ra gì?',['XinchàoPython','Xin chào Python','Xin chào, Python','Error'],'B','print với nhiều arg cách nhau bằng dấu cách.'),
    q('Cú pháp nào SAI?',['print("Hello")','print(42)','print(3.14)','print Hello'],'D','print Hello thiếu dấu ngoặc = SyntaxError.'),
    q('Để in nhiều dòng, ta dùng?',['Nhiều lệnh print()','print("line1\nline2")','Cả hai cách đều đúng','Không thể in nhiều dòng'],'C','Cả 2 cách đều in nhiều dòng.'),
    q('\\n trong chuỗi Python có nghĩa là?',['Ký tự n','Newline (xuống dòng)','Tab','Dấu gạch chéo'],'B','\\n = newline = xuống dòng mới.'),
    q('\\t trong chuỗi Python có nghĩa là?',['Tab (khoảng cách)','Ký tự t','Newline','Dấu ngoặc'],'A','\\t = tab = khoảng cách đầu dòng.'),
    q('print("*" * 5) in ra gì?',['*5','* * * * *','*****','55555'],'C','"*" * 5 = lặp 5 lần = *****.'),
    q('Kết quả của print(10 / 3)?',['3','3.333...','3.33333...333','Error'],'C','10/3 = 3.3333... (float division).'),
    q('Kết quả của print(10 // 3)?',['3.333','3','4','Error'],'B','// = floor division, 10//3 = 3.'),
    q('Kết quả của print(10 % 3)?',['3','0','1','10'],'C','% = phép chia lấy dư: 10%3=1.'),
    q('Kết quả của print(2 ** 3)?',['6','9','8','23'],'C','** = lũy thừa: 2**3 = 8.'),
    q('sep=" , " trong print làm gì?',['In dấu phẩy','Đổi dấu phân cách giữa các argument','Dừng in','Xóa dòng'],'B','sep = separator giữa các args.'),
    q('end="" trong print làm gì?',['Kết thúc chương trình','Đổi ký tự cuối dòng (mặc định là \\n)','Xóa output','Không làm gì'],'B','end="" = không xuống dòng sau khi in.'),
    q('print(type(42)) in ra gì?',["<class 'int'>","<class 'str'>","42","int"],'A','type(42) = <class \'int\'>.'),
    q('print(type("hello")) in ra gì?',["<class 'str'>","<class 'int'>","hello","str"],'A','type("hello") = <class \'str\'>.'),
    q('Để in tên biến name có giá trị "Minh"?',['print("name")','print(name)','print name','show name'],'B','print(name) in giá trị biến, không in chuỗi "name".'),
    q('f-string là gì trong Python?',['Loại float','Chuỗi có thể nhúng biến: f"Hello {name}"','Loại function','Tên file'],'B','f-string = formatted string, nhúng biến vào chuỗi.'),
    q('print(f"Tôi tên {name}, {age} tuổi") với name="Lan", age=8 in ra gì?',['Tôi tên {name}, {age} tuổi','Tôi tên Lan, 8 tuổi','Error','f-string error'],'B','f-string thay thế {name} và {age} bằng giá trị biến.'),
    q('Kết quả print("Ha" * 3)?',['Ha Ha Ha','HaHaHa','Ha*3','3Ha'],'B','"Ha" * 3 = "HaHaHa".'),
    q('print(True) in ra gì?',['true','1','True','TRUE'],'C','Python in "True" (chữ hoa T).'),
    q('print(False) in ra gì?',['false','0','False','FALSE'],'C','Python in "False" (chữ hoa F).'),
    q('print(None) in ra gì?',['null','undefined','None','0'],'C','Python in "None".'),
    q('print(abs(-5)) in ra gì?',['5','-5','abs(-5)','Error'],'A','abs() = giá trị tuyệt đối: abs(-5) = 5.'),
    q('print(max(3, 7, 1)) in ra gì?',['3','1','7','11'],'C','max() trả về giá trị lớn nhất = 7.'),
    q('print(min(3, 7, 1)) in ra gì?',['3','1','7','11'],'B','min() trả về giá trị nhỏ nhất = 1.'),
    q('print(len("Python")) in ra gì?',['5','6','7','Python'],'B','len("Python") = 6 ký tự.'),
    q('print(round(3.7)) in ra gì?',['3','4','3.7','3.5'],'B','round(3.7) = 4 (làm tròn).'),
    q('Lệnh print() có thể in kiểu dữ liệu nào?',['Chỉ chuỗi','Chỉ số','Tất cả: int, float, str, bool, list...','Chỉ int'],'C','print() in được mọi kiểu dữ liệu.'),
    q('Sự khác biệt print("3") và print(3)?',['Không khác','print("3") in chuỗi 3; print(3) in số 3; kết quả nhìn giống nhau nhưng type khác','print("3") sai','print(3) sai'],'B','type khác: str vs int, dù nhìn giống nhau.'),
  ]},

  { name: 'Biến số — Hộp lưu trữ thông tin', questions: [
    q('Biến (variable) trong Python là gì?',['Hộp chứa dữ liệu có thể thay đổi','Một loại hàm','Tên file','Lệnh print'],'A','Variable = ô nhớ lưu trữ dữ liệu.'),
    q('Cú pháp đặt biến đúng?',['int age = 10','age = 10','var age = 10','age := 10'],'B','age = 10 = cú pháp Python cơ bản.'),
    q('Tên biến nào hợp lệ trong Python?',['2name','my-name','my_name','class'],'C','my_name hợp lệ. Không bắt đầu bằng số, không chứa -, không dùng từ khóa.'),
    q('Kết quả: x = 5; x = 10; print(x)?',['5','10','15','Error'],'B','x bị gán lại = 10.'),
    q('x = 3; y = x; x = 7; print(y) kết quả?',['7','3','10','Error'],'B','y lưu giá trị 3 tại thời điểm gán, không thay đổi khi x đổi.'),
    q('Kiểu dữ liệu của x = 10 là?',['float','str','int','bool'],'C','10 = số nguyên = int.'),
    q('Kiểu dữ liệu của x = 3.14 là?',['int','float','str','bool'],'B','3.14 = số thực = float.'),
    q('Kiểu dữ liệu của x = "hello" là?',['int','float','str','bool'],'C','"hello" = chuỗi = str.'),
    q('Kiểu dữ liệu của x = True là?',['int','str','float','bool'],'D','True = giá trị logic = bool.'),
    q('x = 5; x += 3; print(x) kết quả?',['5','3','8','15'],'C','x += 3 tương đương x = x + 3 = 8.'),
    q('x = 10; x -= 4; print(x) kết quả?',['10','4','6','14'],'C','x -= 4 = x = x - 4 = 6.'),
    q('x = 2; x *= 5; print(x) kết quả?',['7','25','10','2'],'C','x *= 5 = x = x * 5 = 10.'),
    q('Cách đặt nhiều biến cùng lúc?',['a = b = c = 0','a,b,c = 1,2,3','Cả hai đều đúng','Không thể'],'C','Python hỗ trợ cả 2 cách.'),
    q('a, b = 5, 10; a, b = b, a; print(a, b) kết quả?',['5 10','10 5','5 5','Error'],'B','Hoán đổi giá trị: a=10, b=5.'),
    q('Tên biến có phân biệt hoa thường không?',['Không','Có: age, Age, AGE là 3 biến khác nhau','Không, luôn viết thường','Chỉ viết hoa'],'B','Python phân biệt hoa thường trong tên biến.'),
    q('Biến x = None nghĩa là?',['x = 0','x không có giá trị (null)','x = False','x = ""'],'B','None = không có giá trị, tương tự null.'),
    q('Kết quả: x = "5"; y = 3; print(x + y)?',['8','53','Error','5+3'],'C','Không thể cộng str và int → TypeError.'),
    q('Kết quả: x = "5"; y = "3"; print(x + y)?',['8','53','5+3','Error'],'B','"5" + "3" = string concatenation = "53".'),
    q('int("42") chuyển đổi gì?',['Chuỗi "42" thành số nguyên 42','Số 42 thành chuỗi','Không làm gì','Error'],'A','int() chuyển string thành integer.'),
    q('str(100) chuyển đổi gì?',['Chuỗi "100" thành số','Số 100 thành chuỗi "100"','Không làm gì','Error'],'B','str() chuyển số thành string.'),
    q('float("3.14") kết quả?',['3','3.14','Error','"3.14"'],'B','float() chuyển string thành số thực.'),
    q('Biến global và local khác nhau thế nào?',['Giống nhau','Global: dùng toàn bộ file; Local: chỉ trong hàm','Local mạnh hơn','Global chỉ đọc'],'B','Global = toàn file; local = chỉ trong block/function.'),
    q('x = [1, 2, 3]; y = x; y.append(4); print(x) kết quả?',['[1,2,3]','[1,2,3,4]','Error','[4]'],'B','List gán theo tham chiếu, x và y cùng trỏ đến 1 list.'),
    q('Để copy list mà không bị ảnh hưởng?',['y = x','y = x.copy()','y = x[:]','Cả B và C đều đúng'],'D','copy() và slicing [:] đều tạo bản sao độc lập.'),
    q('Tên biến nên đặt theo quy ước nào?',['camelCase (myVar)','snake_case (my_var) - Python convention','UPPER_CASE','Bất kỳ'],'B','Python convention = snake_case cho biến.'),
    q('Constant (hằng số) trong Python quy ước đặt tên thế nào?',['lowercase','snake_case','UPPER_CASE (PI = 3.14)','camelCase'],'C','UPPER_CASE = quy ước cho hằng số.'),
    q('del x làm gì?',['In giá trị x','Xóa biến x','Đặt x = 0','Đổi tên x'],'B','del = xóa biến khỏi bộ nhớ.'),
    q('id(x) trong Python trả về gì?',['Giá trị của x','Kiểu của x','Địa chỉ bộ nhớ của x','Tên của x'],'C','id() = địa chỉ bộ nhớ (identity) của object.'),
    q('x = 5; y = 5; x is y kết quả?',['False','True (vì Python cache small integers)','Error','None'],'B','Python cache số nhỏ, x và y cùng trỏ 1 object.'),
    q('Biến giúp chương trình linh hoạt vì?',['Không giúp gì','Lưu trữ giá trị thay đổi được, tái sử dụng code','Chạy nhanh hơn','Đẹp hơn'],'B','Variable = linh hoạt, không hardcode giá trị.'),
  ]},

  { name: 'input() — Hỏi người dùng', questions: [
    q('Lệnh input() dùng để làm gì?',['In dữ liệu','Nhận dữ liệu từ bàn phím','Đọc file','Lưu biến'],'B','input() = nhận input từ người dùng.'),
    q('Kiểu dữ liệu input() trả về luôn là?',['int','float','str','bool'],'C','input() luôn trả về string.'),
    q('Để hỏi tuổi và tính toán, cần làm gì?',['age = input("Tuổi?")','age = int(input("Tuổi?"))','age = input(int)','int(age)'],'B','Cần int() để chuyển string thành số.'),
    q('name = input("Tên bạn là: "); print("Hello", name) — cách dùng đúng?',['Đúng','Sai vì thiếu int()','Sai vì print sai','Sai vì input sai'],'A','input() cho chuỗi tên, print hiển thị = đúng.'),
    q('Kết quả: x = input("Số: "); print(x * 2) nếu nhập "5"?',['10','55','5*2','Error'],'B','"5" * 2 = string repeat = "55".'),
    q('Kết quả: x = int(input()); print(x * 2) nếu nhập 5?',['55','10','5*2','Error'],'B','int(5) * 2 = 10.'),
    q('Để nhập số thực (decimal)?',['int(input())','float(input())','str(input())','bool(input())'],'B','float() chuyển string thành số thực.'),
    q('input("Hỏi? ") — dấu cách sau "?" để làm gì?',['Bắt buộc','Tạo khoảng trống đẹp trước khi gõ','Lỗi cú pháp','Không tác dụng gì'],'B','Dấu cách = UX tốt hơn, tách prompt và input.'),
    q('Nếu người dùng nhập "abc" khi cần int, điều gì xảy ra?',['Trả về 0','ValueError','Bỏ qua','Trả về "abc"'],'B','int("abc") → ValueError.'),
    q('Để xử lý lỗi nhập sai, dùng?',['try-except','if-else','for loop','while loop'],'A','try-except bắt ValueError khi input sai.'),
    q('Chương trình hỏi tên và tuổi, dùng mấy lần input()?',['1','2','3','0'],'B','1 input() cho tên + 1 input() cho tuổi = 2 lần.'),
    q('Để nhập nhiều số trên 1 dòng (cách nhau bởi space)?',['a, b = map(int, input().split())','a = input(); b = input()','a,b = input()','split(input())'],'A','map(int, input().split()) = nhập nhiều số 1 dòng.'),
    q('Kết quả: a,b = map(int,"3 5".split()); print(a+b)?',['35','8','3','5'],'B','a=3, b=5; 3+5=8.'),
    q('Lệnh input() dừng chương trình chờ người dùng không?',['Không, chạy tiếp','Có, chờ đến khi người dùng nhấn Enter','Chờ 5 giây','Chạy ngầm'],'B','input() chặn (blocking) đến khi nhấn Enter.'),
    q('Chương trình tính diện tích hình chữ nhật cần input gì?',['Chỉ chiều dài','Chỉ chiều rộng','Chiều dài và chiều rộng','Không cần input'],'C','Diện tích = dài × rộng → cần 2 input.'),
    q('Để nhập list số cách nhau bởi phẩy?',['nums = list(map(int, input().split(",")))','nums = input()','nums = int(input())','split(",")'],'A','split(",") và map(int) = nhập list số.'),
    q('getpass module dùng để làm gì?',['Input nhanh hơn','Input ẩn (nhập mật khẩu không hiện ký tự)','Input nhiều dòng','Xóa input'],'B','getpass.getpass() = nhập mật khẩu ẩn ký tự.'),
    q('strip() sau input() dùng để làm gì?',['Xóa toàn bộ input','Xóa khoảng trắng đầu và cuối chuỗi','Đổi kiểu','Tính độ dài'],'B','strip() loại bỏ whitespace thừa.'),
    q('input().lower() làm gì?',['In thường','Chuyển input thành chữ thường','Chuyển thành chữ hoa','Xóa input'],'B','lower() = viết thường toàn bộ chuỗi.'),
    q('Để validation input (kiểm tra hợp lệ)?',['Không cần','if not name.isalpha(): print error; else: accept','input only','print only'],'B','Kiểm tra điều kiện hợp lệ trước khi dùng.'),
    q('Vòng lặp nào hỏi lại nếu input sai?',['for i in range(3)','while True: try input; if valid break; else try again','if-else','No loop needed'],'B','while True với break khi hợp lệ = retry loop.'),
    q('int(input()) vs input() khác nhau thế nào?',['Giống nhau','int(input()) = số để tính toán; input() = chuỗi','input() nhanh hơn','int() bắt buộc'],'B','int() = tính toán được; input() = chuỗi.'),
    q('Để hỏi Yes/No từ người dùng?',['answer = input("Yes/No? ").lower().strip(); if answer == "yes": ...','input("yes")','ask yes or no','bool(input())'],'A','lower().strip() chuẩn hóa để so sánh.'),
    q('Chương trình "tính BMI" cần input gì?',['Chỉ cân nặng','Chỉ chiều cao','Cân nặng (kg) và chiều cao (m)','Không cần input'],'C','BMI = cân nặng / chiều cao² → cần 2 float inputs.'),
    q('Để nhập ngày tháng năm dạng "DD/MM/YYYY"?',['date = input("Ngày: ").split("/"); day,month,year = date','date = int(input())','date = input() only','split() only'],'A','split("/") tách chuỗi ngày thành [day, month, year].'),
    q('Lệnh sys.stdin.readline() khác input() thế nào?',['Giống nhau','sys.stdin.readline() nhanh hơn cho input lớn','input() nhanh hơn','sys.stdin không tồn tại'],'B','sys.stdin.readline() thường nhanh hơn cho competitive programming.'),
    q('Để lưu input vào file?',['with open("file.txt","w") as f: f.write(input())','input to file','save(input())','write(input())'],'A','Kết hợp input() và file write.'),
    q('Chương trình greeting đơn giản cần?',['Không cần input','name = input("Tên?"); print("Xin chào", name)','print only','No output'],'B','input tên → print chào = chương trình đầu tay.'),
    q('Tại sao cần int(input()) khi hỏi số?',['Không cần','Vì input() luôn trả về str; cần int() để tính toán','input đã là int','int() chỉ cho tốc độ'],'B','input() = str → phải chuyển đổi để tính toán.'),
    q('Chương trình tính tiền nhà hàng cần input gì?',['Không input','Giá món + số lượng + % thuế','Chỉ giá','Chỉ số lượng'],'B','Cần đủ thông tin để tính tổng tiền.'),
  ]},

  { name: 'Phép tính toán học (+, -, *, /)', questions: [
    q('Kết quả 7 + 3?',['10','73','4','Error'],'A','7 + 3 = 10.'),
    q('Kết quả 15 - 8?',['7','158','23','Error'],'A','15 - 8 = 7.'),
    q('Kết quả 6 * 4?',['10','64','24','Error'],'A','6 * 4 = 24.'),
    q('Kết quả 20 / 4?',['5.0','5','80','Error'],'A','20 / 4 = 5.0 (float division trong Python 3).'),
    q('Kết quả 20 // 4?',['5.0','5','80','Error'],'B','20 // 4 = 5 (integer division).'),
    q('Kết quả 17 % 5?',['3','2','1','5'],'B','17 % 5 = dư 2 (17 = 3*5 + 2).'),
    q('Kết quả 2 ** 8?',['16','256','28','2*8'],'B','2**8 = 2^8 = 256.'),
    q('Thứ tự ưu tiên: 2 + 3 * 4?',['20','14','24','Error'],'B','* trước + theo PEMDAS: 3*4=12, 12+2=14.'),
    q('Kết quả (2 + 3) * 4?',['20','14','24','Error'],'A','Ngoặc trước: (2+3)=5, 5*4=20.'),
    q('math.sqrt(16) kết quả?',['2','4','8','16'],'B','sqrt(16) = căn bậc hai = 4.'),
    q('math.floor(3.9) kết quả?',['4','3','3.9','Error'],'B','floor() = làm tròn xuống = 3.'),
    q('math.ceil(3.1) kết quả?',['3','4','3.1','Error'],'B','ceil() = làm tròn lên = 4.'),
    q('round(2.567, 2) kết quả?',['2.5','2.56','2.57','2.6'],'C','round(2.567, 2) làm tròn 2 chữ số thập phân = 2.57.'),
    q('abs(-15) kết quả?',['15','-15','0','Error'],'A','abs() = giá trị tuyệt đối = 15.'),
    q('max(3, 1, 7, 5) kết quả?',['3','1','7','5'],'C','max() = giá trị lớn nhất = 7.'),
    q('min(3, 1, 7, 5) kết quả?',['3','1','7','5'],'B','min() = giá trị nhỏ nhất = 1.'),
    q('sum([1, 2, 3, 4, 5]) kết quả?',['12','15','5','Error'],'B','sum() tổng danh sách = 1+2+3+4+5=15.'),
    q('Để tính diện tích hình tròn r=5 (π≈3.14)?',['3.14 * 5','3.14 * 5 * 5','3.14 * 2 * 5','5 * 5'],'B','S = π*r² = 3.14 * 25 = 78.5.'),
    q('Kết quả 10 / 3 trong Python 3?',['3','3.333...','3.0','Error'],'B','/ luôn trả float: 10/3 ≈ 3.333...'),
    q('pow(3, 4) kết quả?',['12','81','34','Error'],'B','pow(3,4) = 3^4 = 81.'),
    q('Kết quả 5 * 0?',['5','0','1','Error'],'B','Bất kỳ số * 0 = 0.'),
    q('Kết quả 7 / 0 trong Python?',['0','7','Infinity','ZeroDivisionError'],'D','Chia cho 0 → ZeroDivisionError.'),
    q('Để tính % giảm giá (discount): gốc=100, giảm=30%?',['100 * 30','100 * 0.30','100 * 30 / 100','Cả B và C đúng'],'D','30% = 0.30 hoặc 30/100.'),
    q('import math; math.pi cho ra giá trị nào?',['3','3.14','3.14159...','Error'],'C','math.pi ≈ 3.141592653589793.'),
    q('divmod(17, 5) trả về gì?',['3','2','(3, 2) — quotient và remainder','17/5'],'C','divmod() trả về tuple (thương, dư).'),
    q('Thứ tự PEMDAS: 2 ** 3 + 4 * 2?',['28','32','16','24'],'C','2**3=8; 4*2=8; 8+8=16.'),
    q('Kết quả -5 ** 2?',['25','-25','-10','Error'],'B','Python tính -(5**2) = -25, không phải (-5)**2.'),
    q('Kết quả (-5) ** 2?',['25','-25','-10','Error'],'A','(-5)**2 = 25.'),
    q('Để tính lãi suất đơn giản: P=1000, r=10%, t=2 năm?',['1000*0.1','1000*0.1*2','1000*(1+0.1)**2','1000/0.1'],'B','Lãi đơn = P*r*t = 1000*0.1*2 = 200.'),
    q('math module cần import không?',['Không','Có: import math trước khi dùng','Tự động import','math không tồn tại'],'B','Cần import math để dùng math.sqrt, math.pi...'),
  ]},

  { name: 'if - else — Máy tính ra quyết định', questions: [
    q('Cú pháp if-else đúng trong Python?',['if x > 0: print("dương") else: print("không dương")','if (x > 0) { } else { }','if x > 0 then else','if x > 0: ... else: ...'],'D','if x > 0: ... else: ... (dấu chấm : sau điều kiện).'),
    q('Kết quả: if 5 > 3: print("A") else: print("B")?',['B','A','Error','Không in gì'],'B','5 > 3 là True → print("A").'),
    q('Kết quả: if 2 > 5: print("A") else: print("B")?',['A','B','Error','Không in gì'],'B','2 > 5 là False → print("B").'),
    q('elif dùng để làm gì?',['Kết thúc if','Thêm điều kiện phụ giữa if và else','Lặp lại','Xóa biến'],'B','elif = else if = thêm trường hợp.'),
    q('Cú pháp if-elif-else đúng?',['if A: ... elif B: ... else: ...','if A {} elif B {} else {}','if A; elif B; else','if A then elif B then else'],'A','Python dùng : và indentation.'),
    q('Kết quả: x=5; if x<0: print("âm") elif x==0: print("0") else: print("dương")?',['âm','0','dương','Error'],'C','x=5 > 0 → else → print("dương").'),
    q('Toán tử so sánh == nghĩa là?',['Gán giá trị','So sánh bằng','Lớn hơn','Nhỏ hơn'],'B','== = so sánh bằng (không phải gán =).'),
    q('Toán tử != nghĩa là?',['Bằng nhau','Không bằng nhau','Lớn hơn hoặc bằng','Nhỏ hơn hoặc bằng'],'B','!= = không bằng.'),
    q('Toán tử >= nghĩa là?',['Lớn hơn','Nhỏ hơn hoặc bằng','Lớn hơn hoặc bằng','Bằng nhau'],'C','>= = lớn hơn hoặc bằng.'),
    q('and trong if nghĩa là?',['Hoặc','Và (cả hai điều kiện phải đúng)','Không','Chỉ một đúng là đủ'],'B','and = both conditions must be True.'),
    q('or trong if nghĩa là?',['Và','Ít nhất một điều kiện đúng','Không','Cả hai phải sai'],'B','or = at least one condition True.'),
    q('not True kết quả?',['True','False','None','Error'],'B','not đảo ngược giá trị bool.'),
    q('Kết quả: if True and False: print("A") else: print("B")?',['A','B','Error','Không in'],'B','True and False = False → print("B").'),
    q('Kết quả: if True or False: print("A") else: print("B")?',['A','B','Error','Không in'],'A','True or False = True → print("A").'),
    q('if trong Python cần thụt lề (indent) không?',['Không cần','Có, body phải thụt vào','Tùy ý','Chỉ khi có else'],'B','Indentation bắt buộc trong Python.'),
    q('Nested if là gì?',['if lỗi','if lồng trong if khác','if không có else','if với nhiều elif'],'B','Nested if = if bên trong if.'),
    q('Kết quả: x=10; if x>5: if x>8: print("A") else: print("B") else: print("C")?',['A','B','C','Error'],'A','x=10>5: vào if ngoài; x=10>8: vào if trong → print A.'),
    q('Cú pháp if một dòng (ternary)?',['x = A if condition else B','x = condition ? A : B','x = if condition then A else B','x = A when condition'],'A','Python ternary: value if condition else other_value.'),
    q('Kết quả: x=5; result = "lớn" if x > 3 else "nhỏ"; print(result)?',['nhỏ','lớn','5','Error'],'B','x=5>3 → "lớn".'),
    q('isinstance(x, int) kiểm tra điều gì?',['x có phải là int không','x lớn hơn int','x bằng int','x nhỏ hơn int'],'A','isinstance() kiểm tra kiểu dữ liệu.'),
    q('Để kiểm tra số chẵn lẻ?',['if x % 2 == 0: print("chẵn") else: print("lẻ")','if x/2 == 0','if x ** 2 == 0','if x + 2 == 0'],'A','x % 2 == 0 → chẵn; != 0 → lẻ.'),
    q('Để kiểm tra năm nhuận (divisible by 4)?',['if year % 4 == 0: print("nhuận")','if year * 4','if year + 4','if year / 4'],'A','Năm nhuận chia hết cho 4.'),
    q('Kết quả: if "hello": print("A") else: print("B")?',['B','A','Error','Không in'],'B','Chuỗi không rỗng = Truthy → print("A").'),
    q('Kết quả: if "": print("A") else: print("B")?',['A','B','Error','Không in'],'B','Chuỗi rỗng = Falsy → print("B").'),
    q('Kết quả: if 0: print("A") else: print("B")?',['A','B','Error','Không in'],'B','0 = Falsy → print("B").'),
    q('Kết quả: if []: print("A") else: print("B")?',['A','B','Error','Không in'],'B','List rỗng [] = Falsy → print("B").'),
    q('Kết quả: if [1,2,3]: print("A") else: print("B")?',['B','A','Error','Không in'],'B','List không rỗng = Truthy → print("A").'),
    q('Để kiểm tra điểm: >=90→A, >=80→B, >=70→C, else→D?',['if-elif-elif-else','if-if-if','switch-case','match-case'],'A','if-elif-elif-else xử lý nhiều trường hợp.'),
    q('pass trong if làm gì?',['Bỏ qua','Không làm gì (placeholder)','Dừng chương trình','Error'],'B','pass = placeholder, không làm gì.'),
    q('if-else giúp chương trình làm gì?',['Chạy nhanh hơn','Ra quyết định dựa trên điều kiện','Tiết kiệm bộ nhớ','Đẹp hơn'],'B','if-else = decision making trong code.'),
  ]},

  { name: 'Vòng lặp for — Làm việc nhiều lần', questions: [
    q('Vòng lặp for dùng để làm gì?',['Dừng chương trình','Lặp qua các phần tử hoặc range','Khai báo biến','In kết quả'],'B','for = lặp qua iterable (range, list, string...).'),
    q('for i in range(5): print(i) in ra gì?',['1 2 3 4 5','0 1 2 3 4','5 lần 5','0 1 2 3 4 5'],'B','range(5) = 0,1,2,3,4 (0 đến 4).'),
    q('range(1, 6) tạo ra dãy?',['0 1 2 3 4 5','1 2 3 4 5 6','1 2 3 4 5','0 1 2 3 4'],'C','range(1,6) = 1,2,3,4,5.'),
    q('range(0, 10, 2) tạo ra dãy?',['0 1 2 3 4 5 6 7 8 9','0 2 4 6 8','2 4 6 8 10','0 2 4 6 8 10'],'B','range(start,stop,step=2) = 0,2,4,6,8.'),
    q('for i in range(5, 0, -1) in ra gì?',['5 4 3 2 1','1 2 3 4 5','5 4 3 2 1 0','0 1 2 3 4 5'],'A','range(5,0,-1) = 5,4,3,2,1 (đếm ngược).'),
    q('for ch in "hello": print(ch) in ra gì?',['hello','h e l l o (mỗi ký tự 1 dòng)','5','Error'],'B','Lặp qua từng ký tự của chuỗi.'),
    q('for x in [1,2,3]: print(x*2) in ra gì?',['1 2 3','2 4 6','123','246'],'B','2*1=2, 2*2=4, 2*3=6.'),
    q('Kết quả: total=0; for i in range(1,6): total+=i; print(total)?',['15','10','5','1 2 3 4 5'],'A','1+2+3+4+5=15.'),
    q('break trong vòng lặp for dùng để làm gì?',['Tiếp tục vòng lặp','Thoát khỏi vòng lặp ngay lập tức','Tăng biến','Dừng chương trình'],'B','break = thoát khỏi vòng lặp.'),
    q('continue trong vòng lặp for dùng để làm gì?',['Thoát vòng lặp','Bỏ qua lần lặp hiện tại, đi đến lần tiếp theo','Lặp lại từ đầu','Dừng chương trình'],'B','continue = bỏ qua lần lặp hiện tại.'),
    q('for i in range(10): if i==5: break; print(i) in ra đến số nào?',['10','5','4','0 1 2 3 4'],'D','break khi i=5 → in 0,1,2,3,4.'),
    q('for i in range(5): if i%2==0: continue; print(i) in ra gì?',['0 2 4','1 3','0 1 2 3 4','Error'],'B','Bỏ qua chẵn → in lẻ: 1, 3.'),
    q('Vòng lặp lồng (nested for) là?',['for bị lỗi','for trong for','for cùng dòng','for liên tiếp'],'B','Nested for = for bên trong for.'),
    q('for i in range(3): for j in range(2): print(i,j) — in ra bao nhiêu dòng?',['5','6','3','2'],'B','3*2=6 cặp (i,j).'),
    q('else sau for lặp chạy khi nào?',['Không bao giờ','Khi vòng lặp kết thúc bình thường (không gặp break)','Luôn luôn','Khi có break'],'B','for-else: else chạy khi for kết thúc tự nhiên.'),
    q('enumerate([a,b,c]) trả về gì?',['[a,b,c]','[(0,a),(1,b),(2,c)]','[0,1,2]','Error'],'B','enumerate() thêm index vào mỗi phần tử.'),
    q('for i, val in enumerate(["a","b","c"]): print(i, val) in ra gì?',['a b c','0 a / 1 b / 2 c','abc','0 1 2'],'B','enumerate cho tuple (index, value).'),
    q('zip([1,2],[a,b]) trả về gì?',['[1,2,a,b]','[(1,a),(2,b)]','[1,a,2,b]','Error'],'B','zip() ghép song song 2 iterable.'),
    q('List comprehension [x**2 for x in range(5)] kết quả?',['[0,1,4,9,16]','[1,4,9,16,25]','[0,1,2,3,4]','Error'],'A','0²,1²,2²,3²,4² = [0,1,4,9,16].'),
    q('[x for x in range(10) if x%2==0] kết quả?',['[0,2,4,6,8]','[2,4,6,8,10]','[1,3,5,7,9]','[0,1,2,3,4]'],'A','Lọc số chẵn từ 0-9.'),
    q('for _ in range(5): print("Hi") in ra "Hi" mấy lần?',['Một lần','Năm lần','Không lần','Error'],'B','range(5) = 5 lần lặp.'),
    q('_ trong for _ in range(5) nghĩa là?',['Lỗi cú pháp','Tên biến đặc biệt khi không cần dùng biến lặp','Khoảng trắng','Số âm'],'B','_ = convention: không cần dùng biến loop.'),
    q('range() tối đa có mấy argument?',['1','2','3','4'],'C','range(start, stop, step) = 3 args.'),
    q('for i in range(3,3): print(i) in ra gì?',['3','Không in gì','Error','0 1 2'],'B','range(3,3) rỗng = không lặp.'),
    q('Tổng các số lẻ từ 1 đến 9?',['sum([i for i in range(1,10,2)])','sum(range(9))','sum(1+3+5+7+9)','Cả A và C đúng'],'D','Cả list comprehension và hardcode đều cho 25.'),
    q('Kết quả: [str(i) for i in range(3)]?',["['0','1','2']","[0,1,2]","['0 1 2']","Error"],'A','Chuyển mỗi int thành str.'),
    q('for name in ["Lan","Minh","Nam"]: print(f"Chào {name}") in ra mấy dòng?',['1','2','3','4'],'C','3 phần tử → 3 lần lặp → 3 dòng.'),
    q('Vòng lặp for phù hợp khi?',['Không biết số lần lặp','Biết trước số lần lặp hoặc lặp qua danh sách','Lặp mãi mãi','Chỉ khi có list'],'B','for = biết trước số lần hoặc có iterable.'),
    q('Kết quả sorted([3,1,4,1,5]) là?',['[1,1,3,4,5]','[5,4,3,1,1]','[3,1,4,1,5]','Error'],'A','sorted() sắp xếp tăng dần.'),
    q('for i in reversed(range(5)): print(i) in ra gì?',['0 1 2 3 4','4 3 2 1 0','5 4 3 2 1','Error'],'B','reversed() đảo ngược → 4,3,2,1,0.'),
  ]},

  { name: 'Vòng lặp while — Lặp đến khi xong', questions: [
    q('Vòng lặp while dùng khi nào?',['Khi biết trước số lần','Khi không biết trước số lần, lặp đến khi điều kiện sai','Chỉ với số','Không bao giờ'],'B','while = lặp khi điều kiện True, không biết trước số lần.'),
    q('Cú pháp while đúng?',['while x > 0 { }','while x > 0:','while (x > 0)','while x > 0 do:'],'B','while condition: (dấu hai chấm).'),
    q('Infinite loop (vòng lặp vô hạn) xảy ra khi?',['Điều kiện luôn True, không có break','Điều kiện luôn False','break ngay đầu','range() rỗng'],'A','Điều kiện không bao giờ sai → vô hạn.'),
    q('while True: break — chạy mấy lần?',['Vô hạn','1 lần','0 lần','Error'],'B','break ngay sau 1 lần = chạy 1 lần.'),
    q('x=1; while x<=5: print(x); x+=1 — in ra gì?',['1 2 3 4','1 2 3 4 5','1 2 3 4 5 6','Vô hạn'],'B','x từ 1 đến 5 (<=5).'),
    q('Nếu quên x+=1 trong vòng lặp x=1;while x<=5?',['Chạy 5 lần','Vòng lặp vô hạn','Error','Chạy 1 lần'],'B','Không tăng x → điều kiện luôn True → vô hạn.'),
    q('Để thoát vòng lặp while, dùng?',['continue','break','pass','return'],'B','break = thoát khỏi vòng lặp.'),
    q('while-else trong Python: else chạy khi nào?',['Không bao giờ','Khi while kết thúc tự nhiên (không break)','Luôn luôn','Khi break'],'B','while-else: else chạy khi điều kiện False tự nhiên.'),
    q('Chương trình đoán số (number guessing game) dùng while thế nào?',['while guess != secret: ask again','for i in range(10)','if guess == secret','No loop needed'],'A','while not correct → hỏi lại = retry loop.'),
    q('Kết quả: count=0; while count<3: count+=1; print(count)?',['0 1 2','1 2 3','3','0 1 2 3'],'B','count tăng trước print: 1,2,3.'),
    q('do-while tương đương trong Python là?',['while True: ... if not condition: break','do ... while','repeat ... until','loop ... end'],'A','Python không có do-while, dùng while True + break.'),
    q('Vòng lặp "nhập đến khi hợp lệ"?',['while True: x=input(); if x.isdigit(): break','if input valid: go','for i in range(5)','No loop'],'A','while True + break khi hợp lệ = validation loop.'),
    q('sum=0; i=1; while i<=100: sum+=i; i+=1; print(sum) kết quả?',['100','5050','1000','Error'],'B','Tổng 1..100 = 5050.'),
    q('while vs for khác nhau thế nào?',['Giống nhau','while dùng khi không biết số lần; for khi biết trước','for mạnh hơn','while đẹp hơn'],'B','while = unknown iterations; for = known/iterable.'),
    q('Phím nào dừng chương trình Python đang chạy vô hạn?',['F5','Ctrl+C','Escape','Alt+F4'],'B','Ctrl+C = KeyboardInterrupt = dừng chương trình.'),
    q('x=10; while x>0: x-=3; print(x) — giá trị cuối cùng in ra?',['0','-2','-1','1'],'B','10→7→4→1→-2 (-2<0 thì dừng, in -2).'),
    q('while len(items) > 0: items.pop() — làm gì?',['Thêm phần tử','Xóa từng phần tử đến khi list rỗng','In list','Sort list'],'B','pop() xóa phần tử cuối; lặp đến rỗng.'),
    q('Để tạo game "đoán số" cho phép thử 3 lần?',['attempts=3; while attempts>0: try guess; if correct: break; attempts-=1','while True: guess','for i: guess','if guess: game'],'A','Biến attempts đếm ngược = giới hạn số lần thử.'),
    q('n=1; while n<32: n*=2; print(n) kết quả?',['32','64','16','31'],'A','1→2→4→8→16→32; 32<32=False → dừng → print(32) = 32.'),
    q('while True với try-except thường dùng để làm gì?',['Không dùng','Nhập dữ liệu lặp lại đến khi đúng','Vòng lặp vô hạn chủ đích','Cả B và C'],'D','Vừa retry khi lỗi, vừa chạy mãi là patterns phổ biến.'),
    q('i=0; while i<5: i+=1; if i==3: continue; print(i) in ra gì?',['1 2 3 4 5','1 2 4 5','0 1 2 3 4','Error'],'B','continue khi i=3 → bỏ qua print(3): 1,2,4,5.'),
    q('Vòng while kiểm tra điều kiện ở đâu?',['Cuối mỗi lần lặp','Đầu mỗi lần lặp','Giữa','Không kiểm tra'],'B','while kiểm tra điều kiện TRƯỚC khi thực hiện body.'),
    q('Nếu điều kiện while sai ngay từ đầu?',['Chạy 1 lần','Không chạy lần nào','Chạy mãi','Error'],'B','Điều kiện sai → body không chạy lần nào.'),
    q('Để in bảng cửu chương 2?',['i=1; while i<=10: print(f"2x{i}={2*i}"); i+=1','print 2x table','for only','No loop'],'A','while i từ 1 đến 10, in 2*i.'),
    q('Fibonacci bằng while: a,b=0,1; while a<100: print(a); a,b=b,a+b kết quả?',['Dãy Fibonacci < 100','0 1','100','Error'],'A','In dãy Fibonacci nhỏ hơn 100.'),
    q('while dùng trong trò chơi bảng điều khiển (console game) vì?',['Không dùng','Game loop cần chạy mãi đến khi thoát','Game có số màn cố định','Console không có while'],'B','Game loop = while True: update_game(); if quit: break.'),
    q('Sentinel value là gì trong while?',['Giá trị lỗi','Giá trị đặc biệt báo hiệu kết thúc vòng lặp','Biến bool','Giá trị mặc định'],'B','Sentinel = giá trị tín hiệu dừng, VD: nhập -1 để thoát.'),
    q('while 1: trong Python nghĩa là?',['Error','Vòng lặp vô hạn (1 = True)','Chạy 1 lần','Syntax error'],'B','while 1: tương đương while True:.'),
    q('Kết quả total: total=0;n=int(input());while n!=-1:total+=n;n=int(input()) với input 3,5,2,-1?',['10','8','3','Error'],'A','3+5+2=10 (-1 là sentinel, không cộng).'),
    q('while phù hợp nhất cho bài toán nào?',['Tổng 1..100','Lặp qua list','Nhập đến khi hợp lệ','Bảng cửu chương'],'C','Không biết số lần trước = while.'),
  ]},

  { name: 'Hàm (def) — Đóng gói tác vụ', questions: [
    q('Hàm (function) trong Python dùng để làm gì?',['Khai báo biến','Đóng gói code tái sử dụng','In kết quả','Lặp lại'],'B','Function = đóng gói code để gọi lại nhiều lần.'),
    q('Cú pháp định nghĩa hàm đúng?',['function greet(): ...','def greet(): ...','func greet(): ...','define greet(): ...'],'B','def = từ khóa định nghĩa hàm.'),
    q('Kết quả: def say_hi(): print("Hi"); say_hi()?',['Không gì','Hi','def say_hi','Error'],'B','Gọi hàm say_hi() → thực thi body.'),
    q('Parameter (tham số) là gì?',['Giá trị trả về','Biến nhận giá trị khi hàm được gọi','Tên hàm','Kiểu hàm'],'B','Parameter = biến trong định nghĩa hàm.'),
    q('Argument (đối số) là gì?',['Giá trị trả về','Tên hàm','Giá trị truyền vào khi gọi hàm','Biến trong hàm'],'C','Argument = giá trị thực tế truyền khi gọi.'),
    q('def add(a,b): return a+b; print(add(3,5)) kết quả?',['3','5','8','Error'],'C','add(3,5) = 3+5 = 8.'),
    q('return trong hàm dùng để làm gì?',['In kết quả','Trả về giá trị cho nơi gọi hàm','Dừng chương trình','Khai báo biến'],'B','return = trả kết quả về caller.'),
    q('Hàm không có return trả về gì?',['0','""','None','Error'],'C','Hàm không return → trả về None.'),
    q('def square(x): return x**2; y=square(4) — y bằng?',['4','8','16','Error'],'C','square(4) = 4**2 = 16.'),
    q('Default parameter là gì?',['Parameter bắt buộc','Parameter có giá trị mặc định nếu không truyền','Parameter đặc biệt','Parameter tự động'],'B','Default param = giá trị khi không truyền argument.'),
    q('def greet(name="bạn"): print(f"Hi {name}"); greet() in ra?',['Hi','Hi bạn','Error','name'],'B','Không truyền → dùng default "bạn".'),
    q('greet("Lan") khi def greet(name="bạn") in ra?',['Hi bạn','Hi Lan','Error','Lan'],'B','Truyền "Lan" ghi đè default.'),
    q('*args trong hàm nghĩa là?',['Error','Nhận nhiều argument vô định','1 argument','Không có arg'],'B','*args = tuple nhiều positional arguments.'),
    q('**kwargs trong hàm nghĩa là?',['Lỗi','Nhận nhiều keyword argument','Không có kwargs','1 kwargs'],'B','**kwargs = dict nhiều keyword arguments.'),
    q('def f(*args): print(sum(args)); f(1,2,3) kết quả?',['1','3','6','Error'],'C','sum((1,2,3)) = 6.'),
    q('Docstring trong hàm là gì?',['Tên hàm','Chuỗi mô tả hàm trong triple quotes','Giá trị return','Parameter'],'B','Docstring = """...""" sau def, mô tả hàm.'),
    q('Lambda function là gì?',['Hàm thông thường','Hàm ẩn danh 1 dòng: lambda x: x*2','Hàm vô hạn','Hàm lỗi'],'B','Lambda = anonymous function ngắn gọn.'),
    q('f = lambda x: x**2; print(f(5)) kết quả?',['10','25','5','Error'],'B','lambda x: x**2 → f(5) = 25.'),
    q('Recursive function (đệ quy) là gì?',['Hàm lặp mãi','Hàm gọi chính nó','Hàm không có return','Hàm lồng nhau'],'B','Recursion = hàm tự gọi lại.'),
    q('def factorial(n): if n<=1: return 1; return n*factorial(n-1); factorial(4) kết quả?',['4','24','10','Error'],'B','4! = 4*3*2*1 = 24.'),
    q('Scope (phạm vi) trong Python là?',['Tên hàm','Nơi biến có thể được truy cập','Kiểu biến','Số lần gọi'],'B','Scope = phạm vi biến hiệu lực (local/global/built-in).'),
    q('Biến local trong hàm có thể truy cập từ ngoài không?',['Có','Không','Tùy trường hợp','Chỉ khi return'],'B','Local var = chỉ trong hàm, không truy cập từ ngoài.'),
    q('global x trong hàm dùng để?',['Xóa biến','Khai báo dùng biến global x trong hàm','Tạo biến mới','Copy biến'],'B','global = thay đổi biến global từ trong hàm.'),
    q('DRY principle là gì?',['Delete Redundant code','Do not Repeat Yourself - tái sử dụng code','Define Recursive Yield','None'],'B','DRY = không lặp lại code → dùng function.'),
    q('Tại sao nên dùng hàm?',['Làm code dài hơn','Code ngắn hơn, tái sử dụng, dễ debug','Chạy chậm hơn','Phức tạp hơn'],'B','Function = tái sử dụng, dễ maintain.'),
    q('Hàm có thể return nhiều giá trị không?',['Không','Có: return a, b → tuple','Chỉ 1 giá trị','Phải dùng list'],'B','return a,b = trả tuple, Python hỗ trợ.'),
    q('def f(): pass — hàm này làm gì khi gọi?',['Error','Không làm gì','Return 0','Print something'],'B','pass = placeholder, không làm gì.'),
    q('Gọi hàm trước khi định nghĩa trong Python?',['Được','Không được - phải định nghĩa trước khi gọi','Tùy module','Được nếu dùng lambda'],'B','Python thực thi từ trên xuống, phải def trước.'),
    q('map(function, list) dùng để làm gì?',['Lọc list','Áp dụng hàm cho mỗi phần tử','Sort list','Tính tổng'],'B','map = áp dụng function cho từng phần tử.'),
    q('filter(function, list) dùng để làm gì?',['Áp dụng hàm','Lọc phần tử thỏa điều kiện','Sort','Map'],'B','filter = giữ phần tử mà function trả True.'),
  ]},

  { name: 'Danh sách (List) — Kho chứa nhiều thứ', questions: [
    q('List trong Python là gì?',['1 giá trị','Tập hợp nhiều giá trị theo thứ tự, có thể thay đổi','Hàm','Biến boolean'],'B','List = ordered, mutable collection.'),
    q('Khai báo list đúng?',['list = (1,2,3)','list = [1,2,3]','list = {1,2,3}','list = <1,2,3>'],'B','List dùng dấu ngoặc vuông [].'),
    q('nums=[10,20,30,40]; print(nums[0]) kết quả?',['10','20','0','Error'],'A','Index bắt đầu từ 0 → nums[0] = 10.'),
    q('nums=[10,20,30,40]; print(nums[-1]) kết quả?',['10','40','30','-1'],'B','Index âm: -1 = phần tử cuối = 40.'),
    q('nums=[10,20,30,40]; print(nums[1:3]) kết quả?',['[10,20]','[20,30]','[20,30,40]','[10,20,30]'],'B','Slicing [1:3] = index 1 đến 2 = [20,30].'),
    q('nums=[1,2,3]; nums.append(4); print(nums) kết quả?',['[1,2,3]','[1,2,3,4]','[4,1,2,3]','Error'],'B','append() thêm vào cuối.'),
    q('nums=[1,2,3]; nums.insert(1,99); print(nums) kết quả?',['[1,99,2,3]','[99,1,2,3]','[1,2,99,3]','Error'],'A','insert(1,99) = chèn 99 vào index 1.'),
    q('nums=[1,2,3,2]; nums.remove(2); print(nums) kết quả?',['[1,3,2]','[1,2,3]','[1,3]','Error'],'A','remove() xóa lần xuất hiện đầu tiên.'),
    q('nums=[1,2,3]; last=nums.pop(); print(last,nums)?',['1 [2,3]','3 [1,2]','3 [1,2,3]','Error'],'B','pop() lấy và xóa phần tử cuối.'),
    q('len([1,2,3,4,5]) kết quả?',['4','5','6','Error'],'B','len() đếm số phần tử = 5.'),
    q('sorted([3,1,4,1,5]) kết quả?',['[3,1,4,1,5]','[1,1,3,4,5]','[5,4,3,1,1]','Error'],'B','sorted() sắp xếp tăng dần.'),
    q('[1,2,3].sort(reverse=True) sắp xếp thế nào?',['Tăng dần','Giảm dần','Không đổi','Error'],'B','reverse=True → giảm dần.'),
    q('3 in [1,2,3,4] kết quả?',['False','True','3','Error'],'B','3 in list → True.'),
    q('5 not in [1,2,3,4] kết quả?',['False','True','5','Error'],'B','5 không trong list → True.'),
    q('[1,2] + [3,4] kết quả?',['[1,2],[3,4]','[1,2,3,4]','Error','[4,6]'],'B','+ nối 2 list.'),
    q('[0] * 5 kết quả?',['[0,0,0,0,0]','0','[5]','Error'],'A','[0] * 5 = lặp 5 lần = [0,0,0,0,0].'),
    q('nums=[1,2,3]; nums[1]=99; print(nums)?',['[1,2,3]','[1,99,3]','[99,2,3]','Error'],'B','List mutable, thay đổi trực tiếp bằng index.'),
    q('sum([1,2,3,4,5]) kết quả?',['5','10','15','Error'],'C','sum() tổng tất cả = 15.'),
    q('max([3,1,7,2]) kết quả?',['1','2','3','7'],'D','max() = giá trị lớn nhất = 7.'),
    q('nums=[1,2,3]; print(nums.count(2))?',['0','1','2','Error'],'B','count() đếm số lần xuất hiện = 1.'),
    q('[1,2,3].index(2) kết quả?',['2','1','0','Error'],'B','index() trả về vị trí = 1.'),
    q('list(range(5)) kết quả?',['range(5)','[0,1,2,3,4]','[1,2,3,4,5]','Error'],'B','list() chuyển range thành list.'),
    q('nums=[1,2,3]; nums.clear(); print(nums)?',['[1,2,3]','[]','None','Error'],'B','clear() xóa toàn bộ phần tử.'),
    q('nums=[1,2,3]; nums2=nums.copy(); nums2.append(4); print(nums)?',['[1,2,3,4]','[1,2,3]','Error','[]'],'B','copy() = bản sao độc lập.'),
    q('[1,[2,3],4] là list gì?',['Flat list','Nested list (list lồng)','Error','Tuple'],'B','List lồng chứa list khác.'),
    q('matrix=[[1,2],[3,4]]; print(matrix[1][0])?',['1','2','3','4'],'C','matrix[1] = [3,4]; [0] = 3.'),
    q('Tuple khác List ở điểm nào?',['Giống nhau','Tuple không thể thay đổi (immutable)','Tuple nhanh hơn','Tuple dùng {}'],'B','Tuple = immutable; List = mutable.'),
    q('Khai báo tuple: t = (1,2,3) hay t = 1,2,3?',['Chỉ (1,2,3)','Cả hai đều tạo tuple','Chỉ 1,2,3','Không được khai báo vậy'],'B','Cả hai cú pháp đều tạo tuple.'),
    q('Slice nums[::2] làm gì?',['Lấy 2 phần tử đầu','Lấy phần tử ở vị trí chẵn (step=2)','Đảo ngược','Lấy nửa'],'B','[::2] = lấy mỗi 2 phần tử 1.'),
    q('nums[::-1] làm gì?',['Sort giảm dần','Đảo ngược list','Lấy phần tử chẵn','Error'],'B','[::-1] = reverse list.'),
  ]},

  { name: 'Chuỗi ký tự (String)', questions: [
    q('String trong Python là gì?',['Một số','Dãy ký tự, đặt trong "" hoặc \'\'','Một hàm','Một list'],'B','String = chuỗi ký tự.'),
    q('len("Python") kết quả?',['5','6','7','Error'],'B','6 ký tự: P,y,t,h,o,n.'),
    q('"hello"[0] kết quả?',['h','e','hello','Error'],'A','Index 0 = ký tự đầu = \'h\'.'),
    q('"hello"[-1] kết quả?',['h','e','o','Error'],'C','Index -1 = ký tự cuối = \'o\'.'),
    q('"hello"[1:4] kết quả?',['hel','ell','ello','hello'],'B','Slice [1:4] = "ell".'),
    q('"hello".upper() kết quả?',['hello','HELLO','Hello','ERROR'],'B','upper() = chữ hoa toàn bộ.'),
    q('"PYTHON".lower() kết quả?',['PYTHON','python','Python','Error'],'B','lower() = chữ thường toàn bộ.'),
    q('"  hello  ".strip() kết quả?',['  hello  ','hello','HELLO','Error'],'B','strip() = xóa khoảng trắng đầu cuối.'),
    q('"hello world".split() kết quả?',["['hello world']","['hello','world']","hello world","Error"],'B','split() tách theo khoảng trắng.'),
    q('" ".join(["a","b","c"]) kết quả?',['abc','a b c','a,b,c','Error'],'B','join() nối với dấu cách.'),
    q('"-".join(["a","b","c"]) kết quả?',['abc','a-b-c','a b c','Error'],'B','join với "-".'),
    q('"hello".replace("l","r") kết quả?',['hello','herro','helo','Error'],'B','replace tất cả "l" bằng "r".'),
    q('"hello world".find("world") kết quả?',['0','5','6','Error'],'C','find() trả về index bắt đầu = 6.'),
    q('"hello".startswith("he") kết quả?',['False','True','he','Error'],'B','startswith() = True nếu bắt đầu bằng "he".'),
    q('"hello".endswith("lo") kết quả?',['False','True','lo','Error'],'B','endswith() = True nếu kết thúc bằng "lo".'),
    q('"hello world".count("l") kết quả?',['2','3','4','Error'],'B','Đếm "l" trong "hello world" = 3.'),
    q('"hello" in "hello world" kết quả?',['False','True','hello','Error'],'B','"hello" nằm trong chuỗi → True.'),
    q('f"Tôi {10+5} tuổi" kết quả?',['Tôi 10+5 tuổi','Tôi 15 tuổi','Error','f-string error'],'B','f-string tính biểu thức {10+5}=15.'),
    q('"abc".isalpha() kết quả?',['False','True','abc','Error'],'B','isalpha() = True nếu toàn chữ cái.'),
    q('"123".isdigit() kết quả?',['False','True','123','Error'],'B','isdigit() = True nếu toàn chữ số.'),
    q('"abc123".isalnum() kết quả?',['False','True','abc123','Error'],'B','isalnum() = True nếu toàn chữ-số.'),
    q('"Python" * 3 kết quả?',['Python*3','PythonPythonPython','Python 3','Error'],'B','Chuỗi * 3 = lặp 3 lần.'),
    q('String có thể thay đổi (mutable) không?',['Có','Không, string immutable','Tùy','Chỉ một phần'],'B','String immutable trong Python.'),
    q('"hello"[0] = "H" có được không?',['Được','Không, TypeError vì string immutable','Được nhưng cần index âm','Chỉ với uppercase'],'B','Không thể thay đổi ký tự trong string.'),
    q('Để đổi ký tự đầu thành hoa?',['s[0]="H"','s.title() hoặc s[0].upper()+s[1:]','s.upper()','s.capitalize()'],'D','capitalize() viết hoa ký tự đầu.'),
    q('"  ".isspace() kết quả?',['False','True','Error','  '],'B','isspace() = True nếu chỉ có whitespace.'),
    q('chr(65) kết quả?',['65','A','a','Error'],'B','chr(65) = ký tự ASCII 65 = \'A\'.'),
    q('ord("A") kết quả?',['A','65','97','Error'],'B','ord() = mã ASCII = 65 cho \'A\'.'),
    q('string.format() dùng để làm gì?',['Xóa string','Format chuỗi với giá trị: "Hello {}".format("Lan")','Đổi kiểu','Sort chuỗi'],'B','format() = nhúng giá trị vào chuỗi.'),
    q('"hello world".title() kết quả?',['hello world','HELLO WORLD','Hello World','Error'],'C','title() viết hoa đầu mỗi từ.'),
  ]},

  { name: 'Turtle — Vẽ hình bằng Python', questions: [
    q('Thư viện Turtle trong Python dùng để làm gì?',['Tính toán','Vẽ hình học bằng lệnh điều khiển con rùa','Đọc file','Kết nối internet'],'B','Turtle = vẽ hình bằng cách điều khiển con rùa.'),
    q('Cách import Turtle?',['include turtle','import turtle','using turtle','require turtle'],'B','import turtle = nạp thư viện.'),
    q('turtle.forward(100) làm gì?',['Vẽ đường 100 đơn vị về phía trước','Xoay 100 độ','Di chuyển không vẽ','Vẽ hình tròn 100'],'A','forward() = đi về phía trước và vẽ đường.'),
    q('turtle.right(90) làm gì?',['Xoay trái 90°','Xoay phải 90°','Di chuyển phải','Vẽ góc 90°'],'B','right(90) = xoay phải 90 độ.'),
    q('turtle.left(45) làm gì?',['Xoay phải 45°','Xoay trái 45°','Vẽ 45 đơn vị','Không làm gì'],'B','left(45) = xoay trái 45 độ.'),
    q('turtle.penup() làm gì?',['Xuống bút (bắt đầu vẽ)','Nhấc bút (di chuyển không vẽ)','Đổi màu','Xóa hình'],'B','penup() = nhấc bút, không vẽ khi di chuyển.'),
    q('turtle.pendown() làm gì?',['Nhấc bút','Đặt bút xuống (bắt đầu vẽ khi di chuyển)','Xóa bút','Không làm gì'],'B','pendown() = đặt bút, vẽ khi di chuyển.'),
    q('Để vẽ hình vuông bằng Turtle?',['for i in range(4): turtle.forward(100); turtle.right(90)','turtle.square(100)','4 lần forward(100)','turtle.shape("square")'],'A','4 cạnh × (tiến 100 + rẽ phải 90°) = hình vuông.'),
    q('turtle.color("red") làm gì?',['Đổi màu nền','Đổi màu bút/đường vẽ sang đỏ','Xóa hình đỏ','Vẽ hình đỏ'],'B','color() = đổi màu bút.'),
    q('turtle.pensize(5) làm gì?',['Vẽ 5 đường','Đặt độ굵 nét bút = 5','Di chuyển 5','Xoay 5°'],'B','pensize() = độ굵 nét bút.'),
    q('turtle.goto(100, 50) làm gì?',['Di chuyển về (0,0)','Di chuyển đến tọa độ (100,50)','Vẽ đến (100,50)','Xoay đến (100,50)'],'B','goto() = di chuyển đến tọa độ.'),
    q('turtle.home() làm gì?',['Thoát chương trình','Về vị trí và hướng ban đầu (0,0, hướng phải)','Xóa hình','Đổi màu'],'B','home() = về (0,0) hướng phải.'),
    q('turtle.clear() làm gì?',['Thoát','Xóa tất cả hình vẽ','Xóa con rùa','Đổi màu nền'],'B','clear() = xóa hình vẽ, giữ con rùa.'),
    q('turtle.reset() làm gì?',['Chỉ xóa hình','Xóa hình và reset về vị trí ban đầu','Thoát chương trình','Đổi màu'],'B','reset() = clear() + home().'),
    q('turtle.circle(50) làm gì?',['Vẽ đường thẳng 50','Vẽ hình tròn bán kính 50','Xoay 50°','Di chuyển 50'],'B','circle(r) = vẽ hình tròn bán kính r.'),
    q('turtle.speed(0) nghĩa là?',['Dừng con rùa','Tốc độ nhanh nhất','Tốc độ chậm nhất','Vô hiệu hóa animation'],'B','speed(0) = nhanh nhất (không có animation).'),
    q('turtle.hideturtle() làm gì?',['Xóa con rùa','Ẩn hình con rùa trên màn hình','Dừng vẽ','Đổi hình dạng con rùa'],'B','hideturtle() = ẩn icon con rùa.'),
    q('turtle.fillcolor("blue") và turtle.begin_fill() dùng để?',['Xóa màu','Bắt đầu tô màu xanh cho hình tiếp theo','Đổi màu nền','Vẽ hình tròn'],'B','begin_fill() + end_fill() = tô màu vùng kín.'),
    q('Để vẽ tam giác đều bằng Turtle?',['for i in range(3): forward(100); right(120)','for i in range(4): forward(100); right(90)','forward(300)','circle(100)'],'A','3 cạnh × rẽ 120° = tam giác đều.'),
    q('turtle.write("Hello") làm gì?',['Xóa text','Viết text "Hello" tại vị trí con rùa','Di chuyển đến Hello','Đổi tên con rùa'],'B','write() = in text lên canvas.'),
    q('screen = turtle.Screen() và screen.bgcolor("black") làm gì?',['Xóa màn hình','Đổi màu nền màn hình thành đen','Đổi màu con rùa','Error'],'B','Screen().bgcolor() = đổi màu nền.'),
    q('Để vẽ ngôi sao 5 cánh bằng Turtle?',['for i in range(5): forward(100); right(144)','for i in range(5): forward(100); right(72)','for i in range(6): forward(100); right(60)','circle(100)'],'A','5 cánh × rẽ 144° = ngôi sao.'),
    q('turtle.shape("turtle") làm gì?',['Đổi hình vẽ thành rùa','Đổi hình dạng icon con rùa thành hình rùa','Vẽ hình rùa','Error'],'B','shape() = đổi hình dạng cursor.'),
    q('Turtle module dựa trên gì?',['pygame','tkinter (GUI library)','wxPython','PyQt'],'B','Turtle sử dụng tkinter phía sau.'),
    q('turtle.done() hay mainloop() dùng để làm gì?',['Thoát ngay','Giữ cửa sổ mở sau khi vẽ xong','Xóa hình','Reset'],'B','done()/mainloop() = giữ cửa sổ hiển thị.'),
    q('Để vẽ hình lục giác đều?',['for i in range(6): forward(80); right(60)','for i in range(6): forward(80); right(120)','for i in range(5): forward(80); right(72)','circle(80)'],'A','6 cạnh × 60° = lục giác đều.'),
    q('turtle.setheading(90) làm gì?',['Xoay 90°','Đặt hướng con rùa = 90° (lên trên)','Di chuyển 90','Vẽ 90°'],'B','setheading() = đặt góc hướng tuyệt đối.'),
    q('Turtle hướng 0° là hướng nào?',['Lên','Phải','Xuống','Trái'],'B','Turtle mặc định: 0° = phải.'),
    q('t = turtle.Turtle() vs import turtle khác nhau?',['Giống nhau','t = Turtle() tạo đối tượng rùa riêng; import turtle dùng module functions','import nhanh hơn','Turtle() lỗi'],'B','OOP style vs module style.'),
    q('Tại sao Turtle phù hợp để học lập trình cho trẻ?',['Quá khó','Kết quả hình ảnh ngay lập tức, thú vị, dễ hiểu','Chỉ vẽ được đường','Không interactive'],'B','Visual feedback tức thì = dễ học.'),
  ]},

  { name: 'Vẽ hình học bằng Turtle', questions: [
    q('Để vẽ hình vuông cạnh 100, góc phải bao nhiêu độ?',['45°','60°','90°','120°'],'C','Hình vuông có 4 góc 90°.'),
    q('Để vẽ hình tam giác đều, mỗi lần rẽ bao nhiêu độ?',['60°','90°','120°','180°'],'C','360° / 3 = 120°.'),
    q('Để vẽ hình ngũ giác đều (5 cạnh), góc rẽ?',['60°','72°','90°','108°'],'B','360° / 5 = 72°.'),
    q('Để vẽ hình lục giác đều, góc rẽ?',['45°','60°','72°','90°'],'B','360° / 6 = 60°.'),
    q('Để vẽ hình tám giác (octagon), góc rẽ?',['30°','40°','45°','50°'],'C','360° / 8 = 45°.'),
    q('Công thức góc rẽ cho n-gon đều?',['180°/n','360°/n','90°/n','270°/n'],'B','Mỗi góc ngoài = 360°/n.'),
    q('Để vẽ hình chữ nhật 150×80?',['for i in range(2): forward(150); right(90); forward(80); right(90)','forward(150); right(90); forward(80)','circle(150,80)','square(150,80)'],'A','2 lần (dài 150 + rẽ + ngắn 80 + rẽ) = hình chữ nhật.'),
    q('Để vẽ ngôi sao 5 cánh, góc rẽ?',['72°','108°','144°','160°'],'C','Sao 5 cánh: rẽ 144° mỗi nét.'),
    q('Để vẽ ngôi sao 6 cánh?',['Vẽ 2 tam giác chồng nhau','for i in range(6): forward(100); right(60)','circle(100)','for 5 in range: right(144)'],'A','Sao 6 cánh = 2 tam giác chồng ngược nhau.'),
    q('turtle.circle(50, 180) làm gì?',['Vẽ hình tròn bán kính 50','Vẽ nửa hình tròn bán kính 50','Xoay 180°','Di chuyển 50'],'B','circle(r, extent) = vẽ cung extent độ.'),
    q('Để vẽ hình trái tim đơn giản bằng Turtle?',['2 nửa vòng tròn + 2 đường xiên','circle(50)','forward(100); right(90) × 4','square(100)'],'A','Trái tim = 2 cung tròn + đường chéo kết hợp.'),
    q('Để vẽ spiral (xoắn ốc)?',['for i in range(50): forward(i*5); right(91)','circle(100)','forward(100); right(90)','for i in range(4): forward(100)'],'A','Forward tăng dần + rẽ hơi hơn 90° = xoắn ốc.'),
    q('turtle.circle(r) vẽ theo hướng nào mặc định?',['Theo chiều kim đồng hồ','Ngược chiều kim đồng hồ','Lên trên','Xuống dưới'],'B','circle() mặc định = CCW (counter-clockwise).'),
    q('turtle.circle(-50) khác circle(50) thế nào?',['Giống nhau','Đổi chiều quay: bán kính âm = theo chiều kim đồng hồ','Nhỏ hơn','Lớn hơn'],'B','Bán kính âm = đổi chiều quay.'),
    q('Để vẽ bông hoa 6 cánh?',['for i in range(6): circle(50,60); right(60)','circle(50)×6','for i in 3: forward(100)','square(50)'],'A','6 cung 60° + xoay 60° mỗi lần = bông hoa.'),
    q('Để vẽ hình chữ nhật nghiêng 45°?',['setheading(45); forward(150); right(90); forward(80); right(90); forward(150); right(90); forward(80)','forward(150); right(45)','goto(45,45)','rotate(45)'],'A','Đặt hướng 45° rồi vẽ hình chữ nhật.'),
    q('Để vẽ nhiều hình cùng màu sắc khác nhau?',['for color in colors: pencolor(color); draw_shape()','1 màu cố định','color("random")','No colors'],'A','Dùng list màu + vòng lặp đổi màu.'),
    q('Để vẽ pattern hoa văn lặp lại?',['for i in range(36): draw_shape(); right(10)','draw once','circle(100)','goto(0,0)'],'A','Vẽ 1 hình + xoay 10° × 36 lần = pattern tròn.'),
    q('Toạ độ (0,0) trong Turtle ở đâu?',['Góc trái trên','Giữa màn hình','Góc phải dưới','Góc trái dưới'],'B','Turtle (0,0) = giữa canvas.'),
    q('turtle.setx(100) làm gì?',['Xoay 100°','Di chuyển đến x=100 (giữ y)','Vẽ đến x=100','Đặt tốc độ'],'B','setx() = đặt tọa độ X, giữ Y.'),
    q('turtle.sety(-50) làm gì?',['Di chuyển đến y=-50 (giữ x)','Xoay âm 50°','Vẽ đến y=-50','Tốc độ -50'],'A','sety() = đặt tọa độ Y.'),
    q('turtle.xcor() và turtle.ycor() trả về gì?',['Góc quay','Tọa độ X và Y hiện tại của con rùa','Màu hiện tại','Tốc độ'],'B','xcor()/ycor() = tọa độ hiện tại.'),
    q('turtle.towards(x,y) trả về gì?',['Khoảng cách đến (x,y)','Góc hướng đến điểm (x,y)','Màu tại (x,y)','None'],'B','towards() = góc cần quay để hướng về (x,y).'),
    q('turtle.distance(x,y) trả về gì?',['Góc','Khoảng cách từ rùa đến (x,y)','Màu','None'],'B','distance() = khoảng cách Euclid.'),
    q('Để vẽ hình thoi (rhombus)?',['for i in range(2): forward(100); right(60); forward(100); right(120)','circle(100)','square(100)','rectangle(100,50)'],'A','2 cặp cạnh + 2 góc nhọn = hình thoi.'),
    q('Để in tên hình vẽ bằng Turtle?',['turtle.write("Hình vuông", align="center", font=("Arial",12,"normal"))','print("Hình vuông")','turtle.say("Hình vuông")','forward("text")'],'A','turtle.write() với font setting.'),
    q('Để dừng animation xem kết quả?',['turtle.done()','turtle.stop()','turtle.exit()','turtle.wait()'],'A','done() hoặc mainloop() giữ cửa sổ.'),
    q('Màu sắc Turtle có thể dùng dạng nào?',['Chỉ tên màu tiếng Anh','Tên màu, hex (#FF0000), RGB tuple','Chỉ RGB','Chỉ hex'],'B','Turtle hỗ trợ tên, hex, và RGB.'),
    q('Turtle phù hợp để học khái niệm nào trong lập trình?',['Chỉ vẽ','Vòng lặp, hàm, tọa độ, giải quyết vấn đề qua hình ảnh','Chỉ tọa độ','Chỉ màu sắc'],'B','Turtle = học loops + function + coordinate system.'),
  ]},

    q("Để vẽ pattern ngôi sao lặp 12 lần (mỗi góc 30°)?",["for i in range(12): draw_star(); right(30)","for i in range(5)","circle(100)","No loop"],"A","12 sao × 30° = pattern tròn hoàn chỉnh."),
  ]},

  { name: "Trò chơi đoán số"', questions: [
    q('Game đoán số hoạt động thế nào?',['Máy in số','Máy chọn số bí mật; người chơi đoán đến khi đúng','Người chơi chọn số','Không có số'],'B','Computer chọn số bí mật → user đoán.'),
    q('Để tạo số ngẫu nhiên trong Python?',['random.randint(1,100)','import random; random.randint(1,100)','randint(100)','random(1,100)'],'B','Cần import random trước.'),
    q('random.randint(1,10) tạo số trong khoảng nào?',['0 đến 9','1 đến 10','1 đến 9','0 đến 10'],'B','randint(a,b) = số nguyên từ a đến b (bao gồm cả hai đầu).'),
    q('Vòng lặp nào phù hợp cho game đoán số?',['for i in range(5)','while guess != secret','if guess == secret','No loop'],'B','while không đúng → hỏi lại = while loop.'),
    q('Cấu trúc chính của game đoán số?',['secret = random; while True: guess = input; if guess==secret: break; elif guess<secret: "thấp hơn"; else: "cao hơn"','print number','input only','random only'],'A','Cấu trúc đầy đủ của game đoán số.'),
    q('Khi guess < secret, hiển thị gì?',['Đúng rồi','Cao hơn','Thấp hơn','Không gì'],'C','Đoán thấp hơn secret → gợi ý "thấp hơn".'),
    q('Khi guess > secret, hiển thị gì?',['Thấp hơn','Cao hơn','Đúng rồi','Error'],'B','Đoán cao hơn secret → gợi ý "cao hơn".'),
    q('Để giới hạn số lần thử (vd: 5 lần)?',['attempts=5; while attempts>0: guess; attempts-=1; if correct: break','while True: guess','for 5 tries','No limit'],'A','Đếm ngược attempts = giới hạn số lần.'),
    q('Nếu hết số lần thử, thông báo gì?',['Tiếp tục','Thông báo thua và hiện số bí mật','Chơi lại tự động','Không gì'],'B','Hết lần thử → "Bạn thua! Số là X"'),
    q('Để hỏi chơi lại sau mỗi game?',['play_again = input("Chơi lại? y/n"); if play_again=="y": restart','print game over','stop','No replay'],'A','input("Chơi lại?") → y/n → restart hoặc quit.'),
    q('Binary search nghĩa là gì trong game đoán số?',['Đoán ngẫu nhiên','Luôn đoán giữa khoảng → thu hẹp dần → chiến lược tối ưu','Đoán từ 1 lên','Đoán từ 100 xuống'],'B','Binary search = luôn đoán điểm giữa → tối ưu nhất.'),
    q('Nếu khoảng 1-100, cần tối đa bao nhiêu lần đoán với binary search?',['50','10','7','100'],'C','log₂(100) ≈ 7 lần đoán.'),
    q('Để track số lần đoán?',['Biến attempt_count, tăng sau mỗi lần đoán','Không cần track','print "đoán lần X"','timer'],'A','count++ mỗi lần đoán = track số lần.'),
    q('Sau khi đoán đúng, thông báo?',['Im lặng','Chúc mừng + số lần đoán','Thông báo lỗi','Số bí mật'],'B','Chúc mừng + "bạn đoán đúng sau X lần".'),
    q('Để kiểm tra input hợp lệ (phải là số)?',['try: guess=int(input()) except ValueError: print("Nhập số!")','if input: guess','guess = int','No check'],'A','try-except xử lý ValueError khi nhập sai.'),
    q('random.seed(42) trong Python dùng để làm gì?',['Tạo số 42','Cố định "hạt giống" ngẫu nhiên để kết quả tái hiện','Tốc độ nhanh hơn','Xóa số cũ'],'B','seed() = reproducible randomness.'),
    q('Để máy tính tự đoán số người dùng (reversed)?',['while True: computer_guess = (low+high)//2; if hint=="cao": low=guess+1; elif hint=="thấp": high=guess-1; else: found','random.randint()','print number','No loop'],'A','Binary search với hints từ người dùng.'),
    q('Độ khó của game có thể điều chỉnh bằng?',['Không thể','Thay đổi khoảng (1-10 dễ, 1-1000 khó) và số lần thử','Chỉ giao diện','Chỉ màu sắc'],'B','Khoảng rộng + ít lần thử = khó hơn.'),
    q('Điểm số game đoán số có thể tính thế nào?',['Không tính điểm','Điểm = (max_attempts - attempts_used) * 10','Điểm = 100 mãi','Điểm ngẫu nhiên'],'B','Đoán ít lần hơn → điểm cao hơn.'),
    q('Để thêm hint "rất nóng / ấm / lạnh"?',['if |guess-secret| < 5: "rất nóng"; elif <20: "ấm"; else: "lạnh"','No hints','print only','random hints'],'A','Khoảng cách nhỏ = gần (nóng); lớn = xa (lạnh).'),
    q('try-except ImportError khi import random?',['random không tồn tại','random là built-in, không cần try','Luôn cần try-except','Error thường gặp'],'B','random là thư viện built-in, luôn có sẵn.'),
    q('Để lưu kỷ lục (high score - ít lần đoán nhất)?',['if attempts < best_attempts: best_attempts = attempts','No record','print best','random best'],'A','So sánh và cập nhật kỷ lục.'),
    q('Game đoán số dạy kỹ năng lập trình nào?',['Chỉ random','while loop, if-elif-else, input validation, try-except','Chỉ if-else','Chỉ input'],'B','Tổng hợp nhiều kỹ năng Python.'),
    q('Để chơi nhiều ván liên tiếp?',['while True: play_game(); if not play_again: break','1 ván thôi','No loop','for i in range(5)'],'A','Outer while loop cho nhiều ván.'),
    q('Hiển thị lịch sử đoán cho người dùng?',['guesses = []; khi đoán → guesses.append(guess); in guesses cuối','No history','Print each guess separately','Random history'],'A','List lưu lịch sử đoán.'),
    q('Nếu người dùng nhập ngoài khoảng cho phép?',['Chấp nhận','Thông báo "Số phải trong khoảng 1-100"','Game over','Error'],'B','Validate range của input.'),
    q('Phiên bản nâng cao: máy tự chơi vs máy?',['Không thể','Computer A chọn số; Computer B dùng binary search để đoán','Cần nhiều máy','Random'],'B','AI đoán = binary search algorithm.'),
    q('random.choice([a,b,c]) làm gì?',['Tạo số ngẫu nhiên','Chọn ngẫu nhiên 1 phần tử từ list','Sort list','Error'],'B','choice() = chọn ngẫu nhiên từ iterable.'),
    q('Game đoán số đơn giản nhưng hay vì?',['Không hay','Áp dụng đầy đủ: logic, loop, condition, input, output','Chỉ vui','Chỉ dễ'],'B','Simple game + powerful concepts = học hay.'),
  ]},

    q("Để tính số lần đoán tối ưu nhất trong khoảng 1-1000?",["~10 lần (log₂(1000)≈10)","500 lần","1000 lần","Vô hạn"],"A","log₂(1000)≈10 lần với binary search."),
  ]},

  { name: "Từ điển (Dictionary)"', questions: [
    q('Dictionary trong Python là gì?',['Danh sách có thứ tự','Tập hợp cặp key-value (từ khóa-giá trị)','Hàm đặc biệt','Tuple 2 chiều'],'B','Dict = {key: value} pairs.'),
    q('Khai báo dict đúng?',['dict = [name: "Lan"]','dict = {name: "Lan"}','dict = {"name": "Lan"}','dict = ("name", "Lan")'],'C','Dict dùng {} với cặp "key": value.'),
    q('d={"name":"Lan","age":8}; print(d["name"]) kết quả?',['Lan','8','name','Error'],'A','d["name"] = giá trị của key "name" = "Lan".'),
    q('d={"age":8}; d["age"]=10; print(d["age"]) kết quả?',['8','10','age','Error'],'B','Thay đổi giá trị của key có sẵn = 10.'),
    q('d={}; d["city"]="HN"; print(d) kết quả?',['{}','{"city":"HN"}','["city"]','Error'],'B','Thêm key mới vào dict.'),
    q('d={"a":1,"b":2}; del d["a"]; print(d) kết quả?',['{"a":1,"b":2}','{"b":2}','{"a":1}','Error'],'B','del xóa cặp key-value.'),
    q('"name" in {"name":"Lan","age":8} kết quả?',['False','True','Lan','Error'],'B','in kiểm tra key trong dict.'),
    q('d={"a":1,"b":2}; print(d.keys()) kết quả?',['[1,2]','dict_keys(["a","b"])','{"a","b"}','Error'],'B','keys() = view các key.'),
    q('d={"a":1,"b":2}; print(d.values()) kết quả?',['dict_keys(["a","b"])','dict_values([1,2])','[1,2]','Error'],'B','values() = view các value.'),
    q('d.items() trả về gì?',['Chỉ keys','Chỉ values','Các cặp (key,value)','Số phần tử'],'C','items() = view các cặp (key,value).'),
    q('d={"a":1}; print(d.get("b","N/A")) kết quả?',['Error','None','N/A','1'],'C','get(key, default) = trả default nếu key không có.'),
    q('dict.update({"c":3}) làm gì?',['Xóa dict','Thêm/cập nhật các key-value từ dict khác','Print dict','Sort dict'],'B','update() = merge dict.'),
    q('len({"a":1,"b":2,"c":3}) kết quả?',['3','2','1','Error'],'A','len() = số cặp key-value = 3.'),
    q('for key in {"a":1,"b":2}: print(key) in ra gì?',['1 2','a b','a 1 b 2','Error'],'B','Lặp qua dict = lặp qua keys.'),
    q('for k,v in d.items(): in ra key và value thế nào?',['k và v riêng biệt','Cặp (k,v) cho mỗi phần tử','Chỉ k','Chỉ v'],'B','items() + tuple unpacking = k, v.'),
    q('Dict comprehension {k:v for k,v in items}?',['Lỗi','Cách tạo dict ngắn gọn từ iterable','Tạo list','Tạo tuple'],'B','Dict comprehension = tạo dict nhanh.'),
    q('{str(i):i**2 for i in range(3)} kết quả?',["{'0':0,'1':1,'2':4}","{'0':0,'1':1,'2':4}","[0,1,4]","Error"],'A','Dict comprehension tạo {str(i): i²}.'),
    q("d.pop(\"key\") làm gì?",["Thêm key","Xóa và trả về value của key","Chỉ xóa key","Print key"],"B","pop(key) = xóa key và trả về value tương ứng."),
    q("d.popitem() làm gì?",["Xóa key đầu","Xóa và trả về cặp (key,value) cuối cùng","Xóa tất cả","Sort dict"],"B","popitem() xóa và trả về cặp cuối (Python 3.7+)."),
    q("\"a\" not in {\"b\":1} kết quả?",["False","True","None","Error"],"B","\"a\" không là key trong dict → True."),
    q("dict(name=\"Lan\", age=8) tạo dict gì?",["{\"name\",\"age\"}","{\"name\":\"Lan\",\"age\":8}","[name,age]","Error"],"B","dict() với kwargs tạo dict."),
    q("Đếm tần suất ký tự trong chuỗi bằng dict?",["freq={};for c in s:freq[c]=freq.get(c,0)+1","No dict needed","list counting","string only"],"A","dict.get(c,0)+1 = đếm tần suất."),
    q("Dict có thể là value của dict khác không?",["Không","Có: nested dict","Chỉ list","Chỉ số"],"B","Nested dict = dict trong dict."),
    q("Để merge 2 dict trong Python 3.9+?",["dict1.update(dict2)","dict1 | dict2","Cả hai đều đúng","dict.merge()"],"C","Cả update() và | operator đều merge được."),
    q("OrderedDict và dict thường khác nhau thế nào?",["Giống nhau hoàn toàn từ Python 3.7+","OrderedDict luôn nhanh hơn","dict không có thứ tự","OrderedDict cũ hơn"],"A","Từ Python 3.7+, dict thường cũng giữ insertion order."),
    q("defaultdict từ collections module dùng để làm gì?",["Sort dict","Dict với giá trị mặc định cho key mới","Delete dict","Copy dict"],"B","defaultdict(int) = key mới tự có giá trị 0."),
    q("Counter từ collections dùng để làm gì?",["Copy dict","Đếm tần suất phần tử trong iterable","Sort","Filter"],"B","Counter(\"hello\") = {h:1,e:1,l:2,o:1}."),
    q("Khi nào dùng dict thay vì list?",["Khi muốn truy cập theo index số","Khi cần tra cứu nhanh theo key có ý nghĩa","List luôn tốt hơn","Dict luôn tốt hơn"],"B","Dict tốt khi key có ý nghĩa (tên, mã...) thay vì số thứ tự."),
    q("Dict giúp giải quyết bài toán nào hiệu quả?",["Bài toán tuyến tính","Tra cứu nhanh O(1), đếm tần suất, nhóm dữ liệu","Sort nhanh","Math phức tạp"],"B","Hash map O(1) lookup = dict ứng dụng hiệu quả."),
  ]},

  { name: "Xử lý lỗi đơn giản (try-except)", questions: [
    q("try-except dùng để làm gì?",["Bắt và xử lý ngoại lệ (exception)","Vòng lặp","Khai báo biến","In dữ liệu"],"A","try-except = bắt lỗi để chương trình không bị crash."),
    q("Cú pháp try-except đúng?",["try { } except { }","try: ... except: ...","try: except:","catch() {}"],"B","try: (code) except: (xử lý lỗi)."),
    q("ZeroDivisionError xảy ra khi nào?",["Chia cho âm","Chia cho 0","Chia số thực","import lỗi"],"B","10/0 → ZeroDivisionError."),
    q("ValueError xảy ra khi nào?",["Chia cho 0","int(\"abc\") — chuyển đổi kiểu sai","Biến không tồn tại","File không có"],"B","int(\"abc\") → ValueError."),
    q("TypeError xảy ra khi nào?",["Biến sai","\"5\" + 5 — phép toán sai kiểu","Chia cho 0","File lỗi"],"B","\"5\" + 5 → TypeError."),
    q("NameError xảy ra khi nào?",["Chia cho 0","Dùng biến chưa khai báo","Kiểu sai","File sai"],"B","Dùng biến x chưa assign → NameError."),
    q("except Exception as e: — e là gì?",["Tên exception","Object chứa thông tin lỗi","Biến số","Không quan trọng"],"B","e = exception object với message."),
    q("finally trong try-except chạy khi nào?",["Chỉ khi có lỗi","Luôn chạy dù có lỗi hay không","Chỉ khi không lỗi","Không bao giờ"],"B","finally = luôn chạy (cleanup code)."),
    q("raise ValueError(\"Message\") làm gì?",["Bắt lỗi","Ném lỗi ValueError với message","In message","Xóa lỗi"],"B","raise = tự tạo exception."),
    q("Nhiều except cho nhiều loại lỗi?",["except Error1, Error2: ...","Không thể","except Error1: ... except Error2: ...","try multiple"],"C","Nhiều except block cho nhiều loại lỗi."),
    q("except (TypeError, ValueError): — nghĩa là?",["Chỉ bắt TypeError","Bắt cả TypeError lẫn ValueError","Chỉ bắt ValueError","Error"],"B","Tuple trong except = bắt nhiều loại lỗi cùng lúc."),
    q("Để bắt mọi loại exception?",["except: hoặc except Exception:","except all:","catch all:","No way"],"B","except Exception: bắt tất cả non-system exceptions."),
    q("try-except giúp chương trình trở nên?",["Chậm hơn","Robust hơn — không crash khi gặp lỗi","Phức tạp hơn","Kém hiệu quả"],"B","Robust = chương trình xử lý được lỗi."),
    q("Thực hành tốt: except quá rộng (bare except:) có nên không?",["Nên dùng luôn","Không nên — bắt cả lỗi system, khó debug","Tốt nhất","Bắt buộc"],"B","Bare except quá rộng, khó biết lỗi gì — nên cụ thể."),
    q("IndexError xảy ra khi nào?",["Chia cho 0","Biến sai","Truy cập list/string với index ngoài phạm vi","File lỗi"],"C","list[10] khi list có 5 phần tử → IndexError."),
    q("KeyError xảy ra khi nào?",["Dict key không tồn tại","List index sai","Chia cho 0","Import lỗi"],"A","d[\"key\"] khi key không trong dict → KeyError."),
    q("FileNotFoundError xảy ra khi nào?",["File đầy","Mở file không tồn tại","File quá lớn","Quyền truy cập"],"B","open(\"missing.txt\") → FileNotFoundError."),
    q("try-except-else: else chạy khi nào?",["Khi có lỗi","Khi không có lỗi","Luôn chạy","Không bao giờ"],"B","else trong try = chạy khi try thành công không lỗi."),
    q("Lệnh assert nghĩa là?",["Gán biến","Kiểm tra điều kiện; nếu sai → AssertionError","In kết quả","Xóa biến"],"B","assert condition, \"message\" = kiểm tra điều kiện."),
    q("Để validation input số dương?",["try: x=int(input()); if x<0: raise ValueError(\"Phải dương\") except ValueError: print(\"Lỗi\")","input() only","No validation","if x>0 only"],"A","Kết hợp try-except với raise cho validation."),
    q("Custom Exception: class MyError(Exception): pass — dùng thế nào?",["Không dùng được","raise MyError(\"message\") để ném lỗi tùy chỉnh","import MyError","print MyError"],"B","Custom exception kế thừa Exception."),
    q("Stack trace (traceback) trong Python cho biết gì?",["Thứ tự functions được gọi dẫn đến lỗi","Tốc độ chương trình","Tên biến","Số dòng code"],"A","Traceback = chuỗi call stack dẫn đến exception."),
    q("Debugging vs Exception Handling khác nhau thế nào?",["Giống nhau","Debug = tìm lỗi; Exception = xử lý lỗi khi chạy","Debug = chậm hơn","Exception = debug"],"B","Debug = phát triển; Exception handling = production."),
    q("with open(\"file\") as f: tự động làm gì?",["Đọc nhanh hơn","Đóng file sau khi dùng xong (dù có lỗi)","Tạo file mới","Không cần except"],"B","Context manager tự đóng file = safe file handling."),
    q("try block nên chứa?",["Toàn bộ chương trình","Chỉ code có thể gây lỗi","Không code nào","Chỉ print()"],"B","try = bọc code có nguy cơ lỗi, không phải toàn bộ."),
    q("print(e) sau except Exception as e in ra?",["Không in gì","Thông báo lỗi","Loại lỗi","Line số"],"B","e.__str__() = thông báo lỗi."),
    q("str(e) vs repr(e) khác nhau?",["Giống nhau","str(e) = message dễ đọc; repr(e) = chi tiết hơn","repr nhanh hơn","str là chuỗi rỗng"],"B","str() = user-friendly; repr() = developer-friendly."),
    q("Exception Handling giúp UX thế nào?",["Không giúp","Chương trình không crash, hiển thị lỗi thân thiện thay vì traceback","Chậm hơn","Phức tạp hơn"],"B","Tốt cho UX: thông báo lỗi rõ ràng thay vì crash."),
    q("Khi học Python, nên thực hành try-except khi nào?",["Không bao giờ","Khi code có I/O (file, network, input), parse, math phức tạp","Chỉ khi xong dự án","Chỉ cho người pro"],"B","I/O và conversion = hay gây lỗi, cần try-except."),
    q("try-except không nên dùng để thay thế cái gì?",["Logic bình thường (if-else tốt hơn cho kiểm tra điều kiện thông thường)","File operations","User input","Math"],"A","Exception không thay thế if-else cho flow control thông thường."),
  ]},

  { name: "Đọc file văn bản", questions: [
    q("Để mở file trong Python, dùng hàm gì?",["openfile()","open()","readfile()","import file"],"B","open(\"filename\", mode) = mở file."),
    q("Mode \"r\" trong open() nghĩa là?",["Write","Read (đọc)","Append","Read-Write"],"B","\"r\" = read mode (mặc định)."),
    q("Mode \"w\" trong open() nghĩa là?",["Read","Write (ghi, xóa nội dung cũ)","Append","Execute"],"B","\"w\" = write, xóa và tạo mới."),
    q("Mode \"a\" trong open() nghĩa là?",["Read","Write","Append (thêm vào cuối)","All modes"],"C","\"a\" = append, thêm vào cuối file."),
    q("with open(\"file.txt\") as f: giúp gì?",["Đọc nhanh hơn","Tự động đóng file khi xong","Tạo file mới","Không cần close()"],"B","Context manager tự đóng file."),
    q("f.read() trả về gì?",["List các dòng","Toàn bộ nội dung file dưới dạng 1 string","Số dòng","Kích thước file"],"B","read() = toàn bộ file thành 1 string."),
    q("f.readlines() trả về gì?",["1 chuỗi","List các dòng (mỗi dòng là string)","Số dòng","File object"],"B","readlines() = list các dòng."),
    q("f.readline() đọc gì?",["Toàn bộ file","1 dòng mỗi lần gọi","Tất cả dòng","Ký tự đầu"],"B","readline() = 1 dòng, gọi lại để đọc dòng tiếp."),
    q("for line in f: — lặp qua file thế nào?",["Từng ký tự","Từng dòng một (memory efficient)","Từng từ","Toàn bộ 1 lần"],"B","Lặp qua file = từng dòng, hiệu quả bộ nhớ."),
    q("f.write(\"Hello\") ghi gì vào file?",["Xóa file","Ghi chuỗi \"Hello\" vào file","Đọc \"Hello\"","In \"Hello\""],"B","write() = ghi string vào file."),
    q("Cách ghi nhiều dòng vào file?",["f.writelines([\"line1\n\",\"line2\n\"])","f.write multiple","f.multiwrite()","No way"],"A","writelines() = ghi list các dòng."),
    q("Encoding=\"utf-8\" trong open() dùng để làm gì?",["Tốc độ","Mã hóa ký tự (hỗ trợ tiếng Việt)","Size file","Bảo mật"],"B","UTF-8 = encoding hỗ trợ Unicode, tiếng Việt."),
    q("FileNotFoundError xảy ra khi?",["File quá lớn","Mở file không tồn tại với mode \"r\"","Ghi lỗi","Encoding sai"],"B","open(\"missing.txt\",\"r\") → FileNotFoundError."),
    q("os.path.exists(\"file.txt\") kiểm tra gì?",["Kích thước file","File có tồn tại không","Nội dung file","Đường dẫn"],"B","exists() = kiểm tra file/folder có tồn tại."),
    q("import os; os.getcwd() trả về gì?",["Tên file","Thư mục làm việc hiện tại","Danh sách file","Kích thước"],"B","getcwd() = current working directory."),
    q("Để liệt kê tất cả file trong thư mục?",["os.listdir(\".\")","os.files()","ls()","dir()"],"A","os.listdir() = danh sách file/folder."),
    q("Để xóa file?",["del \"file.txt\"","os.remove(\"file.txt\")","remove(\"file.txt\")","delete file"],"B","os.remove() = xóa file."),
    q("CSV file là gì?",["Compressed file","Comma-Separated Values — file dữ liệu dạng bảng","Code file","Custom file"],"B","CSV = dữ liệu phân cách bằng dấu phẩy."),
    q("import csv; csv.reader() dùng để làm gì?",["Ghi CSV","Đọc file CSV","Sort CSV","Xóa CSV"],"B","csv.reader() = đọc file CSV dòng theo dòng."),
    q("Path tuyệt đối vs tương đối khác nhau?",["Giống nhau","Tuyệt đối: từ gốc hệ thống (C:\\); Tương đối: từ thư mục hiện tại","Tuyệt đối ngắn hơn","Tương đối an toàn hơn"],"B","Absolute vs relative path."),
    q("f.seek(0) làm gì?",["Đóng file","Di chuyển con trỏ về đầu file","Xóa file","Đọc từ cuối"],"B","seek(0) = về đầu file để đọc lại."),
    q("f.tell() trả về gì?",["Tên file","Vị trí con trỏ hiện tại trong file","Kích thước","Encoding"],"B","tell() = vị trí byte hiện tại."),
    q("Để đếm số dòng trong file?",["with open(f) as fp: count=sum(1 for line in fp)","len(f)","f.linecount()","No way"],"A","Đếm dòng bằng vòng lặp generator."),
    q("Để tìm kiếm từ trong file?",["with open(f) as fp: for line in fp: if \"word\" in line: print(line)","search(f,\"word\")","grep(f)","No way"],"A","Đọc từng dòng và kiểm tra."),
    q("json.load() và json.dump() dùng để làm gì?",["Load/dump text","Đọc/ghi dữ liệu JSON từ/vào file","Sort JSON","Parse HTML"],"B","json.load() đọc; json.dump() ghi dữ liệu JSON."),
    q("Binary mode \"rb\" và \"wb\" dùng khi nào?",["Text file","Đọc/ghi file nhị phân (ảnh, audio, exe)","Luôn dùng","Không dùng"],"B","rb/wb = binary mode cho file không phải text."),
    q("shutil.copy(\"src\",\"dst\") làm gì?",["Xóa file","Copy file từ src đến dst","Move file","Đổi tên"],"B","shutil.copy() = copy file."),
    q("Để ghi log (nhật ký) ra file?",["with open(\"log.txt\",\"a\") as f: f.write(f\"{datetime}: {message}\n\")","print to file","No logging","sys.log()"],"A","Append mode + datetime + message = logging cơ bản."),
    q("pathlib.Path() cải tiến gì so với os.path?",["Không cải tiến","API hướng đối tượng, dễ đọc hơn, cross-platform","Nhanh hơn","Cũ hơn"],"B","pathlib = modern file path handling."),
    q("Đọc file văn bản tiếng Việt cần chú ý điều gì?",["Không cần chú ý","Encoding UTF-8: open(\"file\", encoding=\"utf-8\")","ASCII only","Không đọc được"],"B","Phải chỉ định encoding=\"utf-8\" cho tiếng Việt."),
  ]},

  { name: "Dự án: Máy tính bỏ túi", questions: [
    q("Máy tính bỏ túi (calculator) thực hiện phép toán nào?",["Chỉ cộng","Cộng, trừ, nhân, chia","Chỉ nhân","Chỉ cộng trừ"],"B","Calculator cơ bản: +, -, *, /."),
    q("Input của máy tính là gì?",["Chỉ số","Hai số và phép toán cần thực hiện","Chỉ phép toán","Không cần input"],"B","Calculator cần: số 1, phép toán, số 2."),
    q("Cách lấy phép toán từ người dùng?",["op = input(\"Phép toán (+,-,*,/): \")","random.choice","No input","Cố định +"],"A","input() lấy ký hiệu phép toán."),
    q("Cấu trúc chính của calculator?",["if-elif-else cho mỗi phép toán","switch-case","match-case (Python 3.10+)","Cả A và C đúng"],"D","if-elif hoặc match-case xử lý các phép toán."),
    q("Xử lý chia cho 0 trong calculator?",["Bỏ qua","try-except ZeroDivisionError","if divisor==0: print lỗi","Cả B và C"],"D","Cả try-except và if-check đều xử lý được."),
    q("Để calculator chạy nhiều phép tính liên tiếp?",["while True: perform calculation; ask again","1 phép tính thôi","for loop","No loop"],"A","while True loop = tính liên tục đến khi thoát."),
    q("Kết quả hiển thị thế nào đẹp?",["print(result)","print(f\"{num1} {op} {num2} = {result}\")","No display","Error message"],"B","f-string format hiển thị phép tính và kết quả."),
    q("Để thoát calculator, người dùng nhập gì?",["Ctrl+C","\"q\" hoặc \"quit\" hoặc \"exit\"","Delete","F5"],"B","Convention: q/quit/exit để thoát."),
    q("Tính phần trăm (%) trong calculator?",["result = num1 * num2 / 100","result = num1 % num2","result = num1 ** num2","Không có"],"A","X% của Y = X * Y / 100."),
    q("Tính lũy thừa trong calculator nâng cao?",["result = num1 ** num2","result = pow(num1,num2)","Cả hai đúng","math.pow(num1,num2)"],"C","** và pow() đều tính lũy thừa."),
    q("Tính căn bậc hai bằng Python?",["import math; result = math.sqrt(num)","result = num ** 0.5","Cả hai đúng","sqrt(num)"],"C","sqrt() và **0.5 đều cho kết quả giống nhau."),
    q("Validation input (đảm bảo nhập số)?",["try: num=float(input()) except ValueError: print(\"Không hợp lệ\")","input() thôi","No validation","if input > 0"],"A","try-except float() = validation số."),
    q("Lịch sử tính toán (history) lưu bằng?",["List: history.append(f\"{a} {op} {b} = {result}\")","Dict","No history","File only"],"A","List lưu lịch sử các phép tính."),
    q("Để hiển thị lịch sử?",["for item in history: print(item)","print(history)","Cả hai OK","No display"],"C","Cả for loop và print() đều hiện được."),
    q("Scientific calculator cần thêm gì?",["sin, cos, tan, log, exp...","Chỉ thêm màu sắc","Không thêm gì","Chỉ âm thanh"],"A","Scientific = thêm hàm toán học: trig, log, exp..."),
    q("Để format kết quả 2 chữ số thập phân?",["print(f\"{result:.2f}\")","round(result,2)","Cả hai đúng","print(result)"],"C",":.2f và round(,2) đều cho 2 decimal."),
    q("GUI calculator có thể làm bằng?",["Chỉ text","tkinter, PyQt, wxPython","Scratch only","No GUI possible"],"B","tkinter = GUI library built-in Python."),
    q("Thiết kế hàm cho calculator tốt nhất?",["Tất cả trong 1 hàm main","Mỗi phép toán là 1 hàm: def add(a,b): return a+b","No functions","Only classes"],"B","Mỗi phép toán = 1 hàm riêng = clean code."),
    q("Để test calculator?",["Không test","Thử các phép tính và edge cases (0, số âm, chia cho 0)","Random test","Run once"],"B","Test = thử cases bình thường + edge cases."),
    q("Calculator dạy Python skills nào?",["Chỉ if-else","Input, output, if-elif, functions, try-except, loops","Chỉ input","Chỉ math"],"B","Calculator = tổng hợp nhiều kỹ năng Python cơ bản."),
    q("Để lưu kết quả vào file?",["with open(\"results.txt\",\"a\") as f: f.write(f\"{expression}={result}\n\")","print to file","No save","Copy paste"],"A","Append mode ghi kết quả vào file."),
    q("Chuyển đổi đơn vị (unit converter) là mở rộng của?",["Game","Calculator - thêm các hệ đơn vị","Editor","Art"],"B","Unit converter = calculator với bảng đổi đơn vị."),
    q("Để tính toán với số phức?",["Python không hỗ trợ","complex(real, imag): z = complex(3, 4)","Dùng list","No way"],"B","Python có built-in complex number support."),
    q("Modular design trong calculator nghĩa là?",["Tất cả 1 file","Mỗi tính năng tách thành module/hàm riêng","No design","Only 1 function"],"B","Modular = tách components = dễ bảo trì và mở rộng."),
    q("Dự án calculator hoàn chỉnh nên có?",["Chỉ tính toán","Tính toán + validation + lịch sử + error handling + UX tốt","Chỉ UI","Chỉ functions"],"B","Hoàn chỉnh = tất cả features + good UX."),
    q("Cách chạy calculator từ terminal?",["python calculator.py","run calculator","execute calc","python3 calc.py"],"A","python filename.py = chạy script."),
    q("Package py2exe/pyinstaller dùng để làm gì?",["Debug","Đóng gói Python app thành file .exe","Import","Test"],"B","pyinstaller = tạo executable từ Python script."),
    q("Chia sẻ calculator với người không có Python?",["Không thể","Dùng pyinstaller tạo .exe","Gửi source code","Không cần share"],"B","pyinstaller = standalone app không cần Python."),
    q("Cải thiện calculator bằng AI?",["Không thể","Nhận lệnh tự nhiên: \"3 cộng 5\" → tự parse và tính","Only voice","Only text"],"B","NLP + calculator = AI-powered calculator."),
    q("Calculator là dự án tốt để học vì?",["Quá đơn giản","Thực tế, áp dụng nhiều kỹ năng, có thể mở rộng vô hạn","Chỉ học if-else","Không thực tế"],"B","Calculator = dự án thiết thực + scalable."),
  ]},

  { name: "Dự án: Game Quiz hỏi đáp", questions: [
    q("Game Quiz Python khác Scratch Quiz ở điểm nào?",["Giống nhau","Python = text-based, mạnh hơn, có thể lưu file, network","Scratch mạnh hơn","Không khác"],"B","Python quiz = text + file I/O + more logic."),
    q("Cách lưu câu hỏi trong Python Quiz?",["List of dicts: [{\"q\":\"...\",\"options\":[...],\"answer\":\"A\"}]","Hardcode","No storage","Variable only"],"A","List of dicts = cấu trúc tốt cho câu hỏi."),
    q("Để hiển thị câu hỏi và options?",["print(q[\"question\"]); for i,opt in enumerate(q[\"options\"]): print(i+1,opt)","say question","print only question","No display"],"A","enumerate() hiển thị options có số thứ tự."),
    q("Nhận câu trả lời từ người dùng?",["answer = input(\"Câu trả lời (A/B/C/D): \").upper().strip()","click button","random answer","No input"],"A","input().upper().strip() = nhận và chuẩn hóa input."),
    q("Kiểm tra đáp án?",["if answer == question[\"answer\"]: score += 1; print(\"Đúng\") else: print(\"Sai\")","No check","Random check","input only"],"A","So sánh answer với correct_answer trong dict."),
    q("Để random thứ tự câu hỏi?",["import random; random.shuffle(questions)","No shuffle","Manual shuffle","sort()"],"A","random.shuffle() xáo trộn list in-place."),
    q("Để giới hạn thời gian trả lời?",["import threading; timer","while loop with timer","No time limit","stop()"],"A","Threading hoặc time module cho timeout."),
    q("Lưu điểm vào file sau mỗi game?",["with open(\"scores.txt\",\"a\") as f: f.write(f\"{name}:{score}\n\")","No save","print only","No file"],"A","Append mode lưu tên và điểm."),
    q("Đọc câu hỏi từ file JSON?",["import json; with open(\"questions.json\") as f: qs=json.load(f)","No file reading","Hardcode","input file"],"A","json.load() đọc câu hỏi từ file ngoài."),
    q("Tính điểm phần trăm?",["percent = (score / total) * 100","score/total","score * total","No calculation"],"A","percent = (đúng / tổng) * 100."),
    q("Xếp loại dựa trên điểm?",["if percent>=90: \"Xuất sắc\" elif >=70: \"Tốt\" elif >=50: \"Trung bình\" else: \"Chưa đạt\"","No grade","Random grade","Fixed grade"],"A","if-elif-else phân loại xếp hạng."),
    q("Hiển thị câu trả lời đúng khi sai?",["if wrong: print(f\"Đáp án đúng là: {correct}\")","No explanation","Say wrong only","Skip"],"A","Học từ sai lầm = pedagogically valuable."),
    q("Countdown timer cho mỗi câu?",["time.time() + 30; while time.time() < deadline: allow answer","No timer","Fixed time","random time"],"A","time.time() đo thời gian thực."),
    q("Câu hỏi bonus (điểm đôi)?",["if bonus_question: score += 2 * correct","score += 1 only","No bonus","Random bonus"],"A","Bonus questions cộng điểm gấp đôi."),
    q("Lifeline \"50:50\" trong Quiz Python?",["Xóa ngẫu nhiên 2 sai → chỉ còn đúng + 1 sai","No lifeline","Remove all wrong","Random"],"A","random.sample() chọn 2 đáp án sai để loại."),
    q("Multiplayer Quiz (2 người cùng chơi)?",["Lần lượt hỏi từng người, so sánh điểm","Không thể","Same screen","Network only"],"A","Turn-based = hỏi A, hỏi B, so sánh điểm."),
    q("Để thêm âm thanh cho quiz?",["import playsound; playsound.playsound(\"correct.mp3\")","print sound","No sound in Python","input sound"],"A","playsound hoặc pygame.mixer cho âm thanh."),
    q("Adaptive quiz (điều chỉnh độ khó)?",["Khó hơn khi đúng nhiều; dễ hơn khi sai nhiều","Fixed difficulty","Random","No adaptation"],"A","Adaptive = difficulty thay đổi theo performance."),
    q("Để quiz có nhiều môn học?",["Dict of categories: {\"Math\": [...], \"Science\": [...]}","1 môn thôi","No categories","List only"],"A","Dict với key là tên môn = đa môn học."),
    q("Lưu tiến độ học (progress tracking)?",["Dict lưu {user: {topic: score}} trong file JSON","No tracking","Print only","Random"],"A","JSON file lưu tiến độ học tập lâu dài."),
    q("Quiz kết hợp với ML để?",["Không thể","Phân tích điểm → đề xuất câu hỏi ôn tập phù hợp","Chỉ tính điểm","No ML needed"],"B","ML + quiz data = personalized learning."),
    q("Chia sẻ quiz online?",["Không thể với Python","Flask/Django web app, hoặc share console link","Email only","File only"],"B","Web framework biến quiz thành web app."),
    q("Game Quiz dạy Python skills gì?",["Chỉ if-else","List of dicts, file I/O, loops, functions, input, random","Chỉ input","Chỉ loops"],"B","Quiz = tổng hợp toàn diện kỹ năng Python."),
    q("Cách test quiz của mình?",["Chỉ chạy 1 lần","Thử nhiều scenarios: đúng/sai/hết giờ/input lạ","No test","Random test"],"B","Comprehensive testing = robust quiz."),
    q("Để quiz có giao diện đẹp trong terminal?",["print(*80)","rich library hoặc colorama cho màu sắc trong terminal","No color possible","tkinter only"],"B","rich/colorama = colored terminal output."),
    q("API để lấy câu hỏi từ internet?",["Không thể","Open Trivia Database API (opentdb.com)","Google API","No API"],"B","opentdb.com = free quiz API."),
    q("import requests để làm gì?",["Import request","Gọi HTTP requests (lấy data từ API/web)","Request input","No use"],"B","requests library = HTTP client cho Python."),
    q("Câu hỏi từ file txt (mỗi dòng là 1 câu)?",["with open(f) as fp: questions=[line.strip() for line in fp]","No file reading","input all","Manual"],"A","List comprehension đọc từng dòng file."),
    q("Dự án Quiz là dự án tốt vì?",["Không tốt","Ứng dụng học tập thực tế, tổng hợp Python, có thể mở rộng","Quá đơn giản","Chỉ dùng 1 lần"],"B","Educational + technical + scalable = great project."),
    q("Bước tiếp theo sau Quiz Python?",["Không cần tiếp","Web quiz (Flask), Database (SQLite), AI recommendations","More input()","Delete project"],"B","Full-stack quiz = Flask + DB + AI."),
  ]},

  { name: "Dự án: Vẽ thành phố bằng Turtle", questions: [
    q("Dự án vẽ thành phố bằng Turtle gồm gì?",["Chỉ 1 tòa nhà","Nhiều tòa nhà, đường, cây, xe, bầu trời...","Chỉ đường","Chỉ cây"],"B","Thành phố = nhiều thành phần kết hợp."),
    q("Để vẽ tòa nhà đơn giản (hình chữ nhật)?",["def draw_building(x,y,w,h): penup; goto(x,y); pendown; for _ in 2: forward(w); left(90); forward(h); left(90)","circle(100)","forward(100)","square(100)"],"A","Hàm vẽ building với tọa độ và kích thước."),
    q("Tại sao dùng hàm để vẽ nhiều tòa nhà?",["Không cần hàm","Hàm tái sử dụng: gọi draw_building() nhiều lần với tham số khác","Copy code","1 hàm thôi"],"B","Function + parameters = DRY principle."),
    q("Để tô màu tòa nhà?",["t.color(\"gray\"); t.begin_fill(); draw_rect(); t.end_fill()","color(\"building\")","No fill","Backdrop"],"A","begin_fill() + draw + end_fill() = tô màu."),
    q("Để vẽ nhiều cửa sổ (windows) trên tòa nhà?",["Nested loop: for mỗi tầng, for mỗi cột, vẽ hình vuông nhỏ","1 cửa sổ","No windows","Random windows"],"A","Nested loop vẽ grid cửa sổ."),
    q("Để vẽ đường (road) nằm ngang?",["t.penup(); t.goto(-240, 0); t.pendown(); t.forward(480)","circle(road)","goto(0,0)","backward(road)"],"A","Đường ngang = penup + goto vị trí + pendown + forward."),
    q("Để vẽ cây (tree) đơn giản?",["Thân cây = hình chữ nhật; tán cây = hình tròn hoặc tam giác","circle(tree)","square(tree)","Tree shape"],"A","Cây = thân + tán (2 hình ghép)."),
    q("Để vẽ bầu trời và mặt trời?",["screen.bgcolor(\"lightblue\"); draw_sun_circle at top","No sky","Backdrop only","Random"],"A","Màu nền = bầu trời; hình tròn vàng = mặt trời."),
    q("Để vẽ xe hơi (car)?",["Thân xe = hình chữ nhật; bánh = 2 hình tròn nhỏ phía dưới","circle(car)","square only","No car"],"A","Car = body rectangle + 2 wheel circles."),
    q("Để thêm hiệu ứng animation (xe đi)?",["Lặp: erase car, move x position, redraw car","Static drawing","No animation","Random move"],"A","Erase + move + redraw = animation."),
    q("Để vẽ các tòa nhà cao thấp khác nhau?",["for building in buildings: draw_building(*building) với buildings = list height/width khác nhau","Same height","1 building","Random"],"A","List các tham số building, vẽ bằng loop."),
    q("Để thêm đèn đường (street lights)?",["Cột = hình chữ nhật dài; đèn = hình tròn nhỏ màu vàng","circle only","No lights","Random"],"A","Street light = pole + circle lamp."),
    q("Để thêm mây (clouds)?",["3 hình tròn chồng nhau màu trắng/xám","1 circle","Rectangle","No cloud"],"A","Cloud = overlapping circles."),
    q("Để scene thay đổi từ ngày sang đêm?",["Đổi bgcolor từ lightblue sang darkblue; đổi màu tòa nhà; thêm sao","No change","Random colors","Stop"],"A","Đổi bgcolor + colors = day/night effect."),
    q("Để thêm sao (stars) vào bầu trời đêm?",["for _ in range(50): goto random; draw small circle/dot","1 star","No stars","circle(stars)"],"A","Vòng lặp vẽ chấm ngẫu nhiên = bầu trời sao."),
    q("Để nhân vật đi bộ trên đường?",["Sprite figure tại y=road_y; lặp thay đổi x + đổi costume bước chân","No character","Random walk","Stop"],"A","Figure + animate walking = nhân vật đi bộ."),
    q("Cấu trúc code tốt cho dự án thành phố?",["1 file dài","Nhiều hàm: draw_sky(), draw_buildings(), draw_road(), draw_trees()","No functions","Random"],"B","Modular functions = organized code."),
    q("Để vẽ cầu (bridge) đơn giản?",["2 trụ cầu + dầm ngang + dây căng","circle(bridge)","rectangle only","No bridge"],"A","Bridge = pillars + deck + cables."),
    q("Để thêm hiệu ứng mưa?",["Lặp vẽ đường dọc ngắn ngẫu nhiên trên màn hình","No rain","bgcolor blue","Stop"],"A","Rain = nhiều đường dọc ngắn ngẫu nhiên."),
    q("Để save hình vẽ thành ảnh?",["import PIL hoặc canvas.postscript() rồi chuyển đổi","turtle.save()","screenshot()","No save"],"A","postscript export hoặc PIL screenshot."),
    q("Để thêm tên thành phố (city name) lên hình?",["turtle.write(\"Hà Nội\", font=(\"Arial\",24,\"bold\")) tại vị trí cụ thể","print(\"Hà Nội\")","No text","backdrop text"],"A","turtle.write() với font formatting."),
    q("Interactive: click để thêm tòa nhà?",["screen.onclick(draw_building_at_click_position)","No click","Random buildings","Manual only"],"A","screen.onclick() = click event handler."),
    q("Màu sắc phù hợp cho đô thị ban ngày?",["Đen trắng","Bầu trời xanh, cây xanh, tòa nhà xám/nâu, đường xám","Neon colors","No color"],"B","Màu realistic cho đô thị."),
    q("Để vẽ phản chiếu trong hồ nước?",["Vẽ thành phố lật ngược (y âm) với màu mờ hơn","No reflection","Mirror only","Random"],"A","Mirrored drawing với màu nhạt = reflection."),
    q("Để thêm bóng (shadow) cho tòa nhà?",["Vẽ hình tối hơn lệch sang phải/dưới trước khi vẽ tòa nhà","No shadow","Random dark","outline only"],"A","Shadow = offset shape với màu tối."),
    q("Dự án thành phố Turtle dạy gì?",["Chỉ vẽ","Functions, loops, coordinates, color, decomposition, creativity","Chỉ màu sắc","Chỉ tọa độ"],"B","Tổng hợp: functions + loops + decomposition + art."),
    q("Decomposition trong dự án thành phố nghĩa là?",["Phá hủy code","Chia bài toán phức tạp thành nhiều hàm nhỏ","Delete functions","No structure"],"B","Computational thinking: decompose complex problem."),
    q("Để vẽ thành phố tương lai (futuristic city)?",["Màu neon, tòa nhà hình học lạ, ánh sáng laser","Standard buildings","No future","Black only"],"A","Futuristic = neon colors + geometric shapes."),
    q("Cách improve project theo thời gian?",["Không cần improve","Thêm chi tiết dần: cây → thêm bóng → thêm xe → thêm animation","Delete and restart","Copy others"],"B","Iterative development = thêm features dần dần."),
    q("Dự án vẽ thành phố ý nghĩa vì?",["Chỉ vẽ tranh","Kết hợp lập trình + nghệ thuật + toán học = STEAM education","Chỉ kỹ thuật","Chỉ nghệ thuật"],"B","STEAM = dự án kết hợp nhiều môn học."),
  ]}
];
